# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [22]:
# your code here

import tensorflow as tf
import pandas as pd
import numpy as np

# Import dataset
df = pd.read_csv('../your-code/tic-tac-toe.csv')

lst_lst = []
for i in df.columns:
    lst_lst.append(list(set(df[i])))
    
lst_lst    

[['x', 'o', 'b'],
 ['x', 'o', 'b'],
 ['x', 'o', 'b'],
 ['x', 'o', 'b'],
 ['x', 'o', 'b'],
 ['x', 'o', 'b'],
 ['x', 'o', 'b'],
 ['x', 'o', 'b'],
 ['x', 'o', 'b'],
 [False, True]]

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [4]:
#https://adamklecz.wordpress.com/2017/10/30/tic-tac-tensorflow/, matematico
#https://programmerbackpack.com/python-neural-network-tutorial/
#https://www.kdnuggets.com/2017/09/neural-networks-tic-tac-toe-keras.html

# your code here

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

#from keras.models import Sequential
#from keras.layers import Dense


X = df.iloc[:, 0:9].values
y = df.iloc[:, 9:10].values

X

array([['x', 'x', 'x', ..., 'x', 'o', 'o'],
       ['x', 'x', 'x', ..., 'o', 'x', 'o'],
       ['x', 'x', 'x', ..., 'o', 'o', 'x'],
       ...,
       ['o', 'x', 'o', ..., 'x', 'o', 'x'],
       ['o', 'x', 'o', ..., 'x', 'o', 'x'],
       ['o', 'o', 'x', ..., 'o', 'x', 'x']], dtype=object)

In [5]:
y

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [6]:
# Encode categorical variables as numeric

labelencoder_X = LabelEncoder()

for _ in range(9):
    X[:, _] = labelencoder_X.fit_transform(X[:, _])
X

array([[2, 2, 2, ..., 2, 1, 1],
       [2, 2, 2, ..., 1, 2, 1],
       [2, 2, 2, ..., 1, 1, 2],
       ...,
       [1, 2, 1, ..., 2, 1, 2],
       [1, 2, 1, ..., 2, 1, 2],
       [1, 1, 2, ..., 1, 2, 2]], dtype=object)

In [12]:
# Onehot encode all dependent categorical variables

categorical_features = [0,1,2,3,4,5,6,7,8] # Sera necesario?

onehotencoder = OneHotEncoder()

X = onehotencoder.fit_transform(X).toarray()

X

array([[0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.]])

In [13]:
# Remove every third column to avoid dummy variable trap
# Only need 2 bits to represent 3 possibilities

X = np.delete(X, [0,3,6,9,12,15,18,21,24], axis=1)

X

array([[0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 1., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 1., ..., 1., 0., 1.]])

In [14]:
# Encode target categorical variable

labelencoder_y = LabelEncoder()
y[:, 0] = labelencoder_y.fit_transform(y[:, 0])

y

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [15]:
# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train

array([[1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [16]:
X_test

array([[1., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 1., 0.],
       [0., 1., 0., ..., 0., 0., 1.]])

In [17]:
y_train

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [

In [18]:
y_test 

array([[False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [25]:
# your code here

# Initialize neural network

model = tf.keras.Sequential()


In [26]:
# Add first hidden layer (and input layer)
model.add(tf.keras.layers.Dense(units=9, kernel_initializer='uniform', activation='relu', input_dim=18))

# Add second hidden layer
model.add(tf.keras.layers.Dense(units=9, kernel_initializer='uniform', activation='relu'))

# Add output layer
model.add(tf.keras.layers.Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

# Compile network
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train network
model.fit(X_train, y_train, batch_size=10, epochs=100)

# Predicting the test set results
y_pred = model.predict(X_test)


Epoch 1/100
77/77 [==============================] - 0s 4ms/step - loss: 0.6863 - accuracy: 0.6488
Epoch 2/100
77/77 [==============================] - 0s 4ms/step - loss: 0.6554 - accuracy: 0.6540
Epoch 3/100
77/77 [==============================] - 0s 5ms/step - loss: 0.6104 - accuracy: 0.6540
Epoch 4/100
77/77 [==============================] - 0s 5ms/step - loss: 0.5745 - accuracy: 0.7102
Epoch 5/100
77/77 [==============================] - 0s 5ms/step - loss: 0.5497 - accuracy: 0.7441
Epoch 6/100
77/77 [==============================] - 0s 5ms/step - loss: 0.5246 - accuracy: 0.7624
Epoch 7/100
77/77 [==============================] - 0s 5ms/step - loss: 0.5042 - accuracy: 0.7676
Epoch 8/100
77/77 [==============================] - 0s 6ms/step - loss: 0.4852 - accuracy: 0.7715
Epoch 9/100
77/77 [==============================] - 0s 5ms/step - loss: 0.4618 - accuracy: 0.7977
Epoch 10/100
77/77 [==============================] - 0s 5ms/step - loss: 0.4355 - accuracy: 0.8055
Epoch 11/

77/77 [==============================] - 0s 5ms/step - loss: 0.0438 - accuracy: 0.9869
Epoch 82/100
77/77 [==============================] - 0s 5ms/step - loss: 0.0446 - accuracy: 0.9869
Epoch 83/100
77/77 [==============================] - 0s 5ms/step - loss: 0.0466 - accuracy: 0.9869
Epoch 84/100
77/77 [==============================] - 0s 5ms/step - loss: 0.0448 - accuracy: 0.9883
Epoch 85/100
77/77 [==============================] - 0s 5ms/step - loss: 0.0434 - accuracy: 0.9869
Epoch 86/100
77/77 [==============================] - 0s 5ms/step - loss: 0.0463 - accuracy: 0.9869
Epoch 87/100
77/77 [==============================] - 0s 5ms/step - loss: 0.0458 - accuracy: 0.9817
Epoch 88/100
77/77 [==============================] - 0s 5ms/step - loss: 0.0449 - accuracy: 0.9869
Epoch 89/100
77/77 [==============================] - 0s 5ms/step - loss: 0.0433 - accuracy: 0.9869
Epoch 90/100
77/77 [==============================] - 0s 5ms/step - loss: 0.0421 - accuracy: 0.9869
Epoch 91/100


In [27]:
y_pred

array([[5.2511692e-04],
       [9.9981165e-01],
       [9.9290836e-01],
       [4.2018294e-04],
       [3.5830736e-03],
       [9.9705648e-01],
       [9.9587440e-01],
       [8.9364308e-01],
       [7.0989978e-01],
       [5.9686303e-03],
       [9.9214405e-01],
       [9.9989253e-01],
       [9.9574399e-01],
       [9.1924071e-01],
       [9.9641502e-01],
       [9.9989796e-01],
       [9.9723828e-01],
       [9.9984729e-01],
       [4.7081709e-04],
       [4.6999156e-03],
       [9.1488063e-03],
       [9.9307501e-01],
       [4.1458905e-03],
       [9.9986434e-01],
       [4.0760636e-04],
       [8.9597225e-01],
       [9.9490201e-01],
       [9.9575329e-01],
       [8.7920707e-01],
       [9.9273300e-01],
       [9.9991548e-01],
       [9.9291992e-01],
       [9.9975944e-01],
       [9.9247235e-01],
       [6.1050057e-03],
       [4.7352910e-04],
       [9.9780560e-01],
       [9.9761283e-01],
       [9.9538314e-01],
       [3.9264560e-04],
       [9.9650168e-01],
       [9.946410

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [ ]:
# your code here

tf.keras.optimizers.Adam(
    learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False,
    name='Adam', **kwargs
)


**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here

#import matplotlib.pyplot as plt

#mnist=tf.keras.datasets.mnist
#(x_train,y_train),(x_test,y_test)= mnist.load_data()
#x_train = tf.keras.utils.normalize(x_train,axis=1)

#plt.imshow(x_train[1]) , a color
#plt.imshow(x_train[1],cmap=plt.cm.binary) #, en blanco y negro

#print(x_train[1]) , en numeros
#print(x_train[1])

(x_train,y_train),(x_test,y_test)= df.load_data()


model = tf.keras.models.Secuential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128,activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128,activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax))

model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

model.fit(x_train,y_train,epochs=3)