# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

In [69]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split
import tensorflow as tf

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [70]:
# your code here
ttt = pd.read_csv('tic-tac-toe.csv')

In [71]:
ttt

TL TM TR ML MM MR BL BM BR  class
0    x  x  x  x  o  o  x  o  o   True
1    x  x  x  x  o  o  o  x  o   True
2    x  x  x  x  o  o  o  o  x   True
3    x  x  x  x  o  o  o  b  b   True
4    x  x  x  x  o  o  b  o  b   True
..  .. .. .. .. .. .. .. .. ..    ...
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

[958 rows x 10 columns]

In [72]:
for col in ttt.columns.to_list():
    ttt[col] = ttt[col].map({'x':1,'o':0,'b':2, True:0, False:1})

In [73]:
ttt.columns.to_list()

['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR', 'class']

In [74]:
cols = ['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR']

In [83]:
X = pd.get_dummies(ttt[cols])
y = ttt['class'].values

In [84]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [85]:
# your code here
scaler = StandardScaler()
X = scaler.fit_transform(X)
X


array([[ 0.1837706 ,  0.10794659,  0.1837706 , ...,  0.1837706 ,
        -1.18471377, -1.17047733],
       [ 0.1837706 ,  0.10794659,  0.1837706 , ..., -1.17047733,
         0.10794659, -1.17047733],
       [ 0.1837706 ,  0.10794659,  0.1837706 , ..., -1.17047733,
        -1.18471377,  0.1837706 ],
       ...,
       [-1.17047733,  0.10794659, -1.17047733, ...,  0.1837706 ,
        -1.18471377,  0.1837706 ],
       [-1.17047733,  0.10794659, -1.17047733, ...,  0.1837706 ,
        -1.18471377,  0.1837706 ],
       [-1.17047733, -1.18471377,  0.1837706 , ..., -1.17047733,
         0.10794659,  0.1837706 ]])

In [86]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=29)

In [87]:
X_train

array([[-1.17047733,  1.40060694, -1.17047733, ...,  0.1837706 ,
         0.10794659,  0.1837706 ],
       [-1.17047733,  0.10794659,  0.1837706 , ...,  1.53801852,
         1.40060694, -1.17047733],
       [ 0.1837706 ,  0.10794659, -1.17047733, ..., -1.17047733,
         0.10794659, -1.17047733],
       ...,
       [ 1.53801852,  0.10794659, -1.17047733, ...,  0.1837706 ,
         0.10794659,  0.1837706 ],
       [ 0.1837706 ,  1.40060694,  0.1837706 , ...,  0.1837706 ,
        -1.18471377, -1.17047733],
       [-1.17047733, -1.18471377,  0.1837706 , ...,  0.1837706 ,
         0.10794659, -1.17047733]])

In [88]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(256, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(64, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(32, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(2, activation=tf.nn.softmax))

In [89]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [90]:
train = model.fit(
  X_train,
  y_train,
    
  epochs=8
)

Epoch 1/8
718/718 [==============================] - 0s 478us/sample - loss: 0.6306 - acc: 0.6435
Epoch 2/8
718/718 [==============================] - 0s 58us/sample - loss: 0.5303 - acc: 0.7047
Epoch 3/8
718/718 [==============================] - 0s 54us/sample - loss: 0.4329 - acc: 0.8050
Epoch 4/8
718/718 [==============================] - 0s 58us/sample - loss: 0.3480 - acc: 0.8440
Epoch 5/8
718/718 [==============================] - 0s 60us/sample - loss: 0.2653 - acc: 0.8858
Epoch 6/8
718/718 [==============================] - 0s 53us/sample - loss: 0.2065 - acc: 0.9150
Epoch 7/8
718/718 [==============================] - 0s 58us/sample - loss: 0.1848 - acc: 0.9276
Epoch 8/8
718/718 [==============================] - 0s 58us/sample - loss: 0.1243 - acc: 0.9526


In [91]:
val_loss, val_acc = model.evaluate(X_test, y_test)
print(val_loss)
print(val_acc)

240/240 [==============================] - 0s 163us/sample - loss: 0.2551 - acc: 0.9125
0.25505194067955017
0.9125


In [92]:
model.save('ttt.model')

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [94]:
# your code here
model = tf.keras.models.load_model('ttt.model')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [96]:
predictions = model.predict(X_test)

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [99]:
# your code here
opt = tf.keras.optimizers.Adam(learning_rate=0.0013)
model.compile(optimizer=opt,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=5)

Epoch 1/5
718/718 [==============================] - 0s 151us/sample - loss: 0.1018 - acc: 0.9721
Epoch 2/5
718/718 [==============================] - 0s 52us/sample - loss: 0.0688 - acc: 0.9805
Epoch 3/5
718/718 [==============================] - 0s 49us/sample - loss: 0.0357 - acc: 0.9930
Epoch 4/5
718/718 [==============================] - 0s 53us/sample - loss: 0.0206 - acc: 0.9972
Epoch 5/5
718/718 [==============================] - 0s 51us/sample - loss: 0.0102 - acc: 1.0000


**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here