# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [57]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [58]:
# your code here
np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [59]:
# Method 1 - This method creates a completely aleatory array
a=np.random.random([2,3,5])
print(a)

[[[0.31313031 0.98917644 0.97252725 0.14961194 0.4421579 ]
  [0.12953396 0.35351112 0.82497948 0.18099624 0.95530824]
  [0.52167721 0.355612   0.67272619 0.03149135 0.32573014]]

 [[0.86420182 0.00548675 0.53263046 0.49554333 0.24779648]
  [0.31268991 0.28088251 0.4382613  0.08455152 0.18952093]
  [0.24573955 0.53966844 0.00168968 0.93832574 0.05262191]]]


In [60]:
# Method 2 - This method creates an array containing random values between 0 and 40
a=np.random.randint(0, 40, size=(2, 3, 5))
print(a)

[[[32 12 35 14 11]
  [ 3  5 19 32 10]
  [22 23 23  4 25]]

 [[35 22 25 32 35]
  [21  1  8 38 36]
  [ 5 17  0 14 18]]]


In [61]:
# Method 3 - This method creates an array containing random values between 0 and 1
a=np.random.rand(2,3,5)
print(a)

[[[0.98763244 0.95547881 0.39682412 0.30157691 0.10835027]
  [0.4976784  0.32080898 0.00126672 0.25742624 0.85905541]
  [0.30488587 0.99864596 0.74249091 0.42054999 0.94616543]]

 [[0.77823011 0.04133921 0.23109496 0.52025313 0.2532823 ]
  [0.73254392 0.16604508 0.49794381 0.94117865 0.9201739 ]
  [0.09270073 0.45253274 0.70309795 0.93229254 0.98657716]]]


#### 4. Print *a*.


In [62]:
# your code here
print(a)

[[[0.98763244 0.95547881 0.39682412 0.30157691 0.10835027]
  [0.4976784  0.32080898 0.00126672 0.25742624 0.85905541]
  [0.30488587 0.99864596 0.74249091 0.42054999 0.94616543]]

 [[0.77823011 0.04133921 0.23109496 0.52025313 0.2532823 ]
  [0.73254392 0.16604508 0.49794381 0.94117865 0.9201739 ]
  [0.09270073 0.45253274 0.70309795 0.93229254 0.98657716]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [63]:
# your code here
b=np.ones([5,2,3])

#### 6. Print *b*.


In [64]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [65]:
# your code here
a.size==b.size


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [66]:
# your answer here - It is possible to add a and b, but we have to reshape them first. We either
# - Transform both of them to one-dimesion arrays and add/concatenate them. If we do not perform the transformation beforehand we get the ValueError showed below
np.concatenate([a,b])
# - Transform one of them to the shape of the other and add both afterwards


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [67]:
# your code here
# It could also be done with c=np.reshape(b, a.size)
c=b.transpose(1,2,0)
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [68]:
# your code/answer here - Now it works because both a and c are in the same dimension/have the same shape
# We could also perform this operation with d=a+c
d=np.add(a,c)
print(d)


[[[1.98763244 1.95547881 1.39682412 1.30157691 1.10835027]
  [1.4976784  1.32080898 1.00126672 1.25742624 1.85905541]
  [1.30488587 1.99864596 1.74249091 1.42054999 1.94616543]]

 [[1.77823011 1.04133921 1.23109496 1.52025313 1.2532823 ]
  [1.73254392 1.16604508 1.49794381 1.94117865 1.9201739 ]
  [1.09270073 1.45253274 1.70309795 1.93229254 1.98657716]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [69]:
# your code/answer here 
# Difference - Array d's values are exactly a values +1 and are located in the same position in both a and d 
# Relation - We should remember that d=a+b and b was made of ones, therefore when you add a and b, d is the expected result
# Array d is equal to array a in size and shape. 
print(a)
print(d)

[[[0.98763244 0.95547881 0.39682412 0.30157691 0.10835027]
  [0.4976784  0.32080898 0.00126672 0.25742624 0.85905541]
  [0.30488587 0.99864596 0.74249091 0.42054999 0.94616543]]

 [[0.77823011 0.04133921 0.23109496 0.52025313 0.2532823 ]
  [0.73254392 0.16604508 0.49794381 0.94117865 0.9201739 ]
  [0.09270073 0.45253274 0.70309795 0.93229254 0.98657716]]]
[[[1.98763244 1.95547881 1.39682412 1.30157691 1.10835027]
  [1.4976784  1.32080898 1.00126672 1.25742624 1.85905541]
  [1.30488587 1.99864596 1.74249091 1.42054999 1.94616543]]

 [[1.77823011 1.04133921 1.23109496 1.52025313 1.2532823 ]
  [1.73254392 1.16604508 1.49794381 1.94117865 1.9201739 ]
  [1.09270073 1.45253274 1.70309795 1.93229254 1.98657716]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [41]:
# your code here
# e=a*c
e=np.multiply(a,c)
print(e)

[[[0.93246989 0.51368706 0.19665959 0.03488091 0.5422121 ]
  [0.53318137 0.38255901 0.76674941 0.99914768 0.74529785]
  [0.63547273 0.6912302  0.67625486 0.12735569 0.88607417]]

 [[0.06983199 0.61245687 0.18894929 0.52547461 0.85697949]
  [0.475741   0.78733272 0.1249335  0.23594992 0.38979379]
  [0.27558928 0.57207197 0.73530651 0.34434226 0.50400647]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
# e is equal to a due to the fact that e is made up of 1 values. Thus, we could state that any array multiply by another array built on 1 values is equal to itself

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max= np.max(d)
print(d_max)
d_min= np.min(d)
print(d_min)
d_mean= np.mean(d)
print(d_mean)

1.9991476750680022
1.0348809059087738
1.5120664063395917


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f=np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [73]:
# your code here
import re

for x np.nditer(d):
    if x re.sub()
   

IndexError: arrays used as indices must be of integer (or boolean) type

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [31]:
# your code here
print(d)
print(f)

[[[1.93246989 1.51368706 1.19665959 1.03488091 1.5422121 ]
  [1.53318137 1.38255901 1.76674941 1.99914768 1.74529785]
  [1.63547273 1.6912302  1.67625486 1.12735569 1.88607417]]

 [[1.06983199 1.61245687 1.18894929 1.52547461 1.85697949]
  [1.475741   1.78733272 1.1249335  1.23594992 1.38979379]
  [1.27558928 1.57207197 1.73530651 1.34434226 1.50400647]]]
[[[0.93246989 0.51368706 0.19665959 0.03488091 0.5422121 ]
  [0.53318137 0.38255901 0.76674941 0.99914768 0.74529785]
  [0.63547273 0.6912302  0.67625486 0.12735569 0.88607417]]

 [[0.06983199 0.61245687 0.18894929 0.52547461 0.85697949]
  [0.475741   0.78733272 0.1249335  0.23594992 0.38979379]
  [0.27558928 0.57207197 0.73530651 0.34434226 0.50400647]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here