# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2, 3, 5))
a

array([[[0.07302016, 0.14068097, 0.85168024, 0.31402511, 0.81682676],
        [0.57887618, 0.07358813, 0.51366157, 0.81403425, 0.26237493],
        [0.30928831, 0.58619172, 0.10382303, 0.96677951, 0.57529164]],

       [[0.43621062, 0.67920671, 0.35562442, 0.27614906, 0.50868366],
        [0.95796447, 0.14813888, 0.74000685, 0.04776147, 0.4029495 ],
        [0.24915927, 0.20263675, 0.7441292 , 0.238334  , 0.42776602]]])

In [4]:
# Method 2
a = np.random.random(30).reshape(2, 3, 5)
a.shape

(2, 3, 5)

In [5]:
# Method 3
a = np.random.randint(0, 100,(2, 3, 5))
a

array([[[84, 88, 46, 20, 46],
        [51, 36, 56, 11, 57],
        [14, 98, 30, 99, 26]],

       [[ 7, 58, 30, 88, 92],
        [12, 83, 89, 15, 69],
        [96, 37, 95, 58, 13]]])

#### 4. Print *a*.


In [6]:
# your code here
a

array([[[84, 88, 46, 20, 46],
        [51, 36, 56, 11, 57],
        [14, 98, 30, 99, 26]],

       [[ 7, 58, 30, 88, 92],
        [12, 83, 89, 15, 69],
        [96, 37, 95, 58, 13]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5, 3, 2))

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.size == b.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your code here
print("Different shape")
print(a+b)

Different shape


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.T
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
# it still didn't work. changed b.shape to (5, 3, 2) in order for this exercise to work
d = a + c
print("same shape", d)

same shape [[[ 85.  89.  47.  21.  47.]
  [ 52.  37.  57.  12.  58.]
  [ 15.  99.  31. 100.  27.]]

 [[  8.  59.  31.  89.  93.]
  [ 13.  84.  90.  16.  70.]
  [ 97.  38.  96.  59.  14.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print()
print(d)

[[[84 88 46 20 46]
  [51 36 56 11 57]
  [14 98 30 99 26]]

 [[ 7 58 30 88 92]
  [12 83 89 15 69]
  [96 37 95 58 13]]]

[[[ 85.  89.  47.  21.  47.]
  [ 52.  37.  57.  12.  58.]
  [ 15.  99.  31. 100.  27.]]

 [[  8.  59.  31.  89.  93.]
  [ 13.  84.  90.  16.  70.]
  [ 97.  38.  96.  59.  14.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
print(a)
print(c)
e = a*c

[[[84 88 46 20 46]
  [51 36 56 11 57]
  [14 98 30 99 26]]

 [[ 7 58 30 88 92]
  [12 83 89 15 69]
  [96 37 95 58 13]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print(e==a, "they are equal because array c is full of ones")

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]] they are equal because array c is full of ones


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [41]:
# your code here
print(d)
d_min = min(d.reshape(d.size))
d_max = max(d.reshape(d.size))
d_mean = np.mean(d.reshape(d.size))

[[[ 85.  89.  47.  21.  47.]
  [ 52.  37.  57.  12.  58.]
  [ 15.  99.  31. 100.  27.]]

 [[  8.  59.  31.  89.  93.]
  [ 13.  84.  90.  16.  70.]
  [ 97.  38.  96.  59.  14.]]]


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [42]:
# your code here
f = np.empty((2, 3, 5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [43]:
print(d)
print()
print(d_min)
print(d_max)
print(d_mean)

[[[ 85.  89.  47.  21.  47.]
  [ 52.  37.  57.  12.  58.]
  [ 15.  99.  31. 100.  27.]]

 [[  8.  59.  31.  89.  93.]
  [ 13.  84.  90.  16.  70.]
  [ 97.  38.  96.  59.  14.]]]

8.0
100.0
54.46666666666667


In [44]:
# your code here

for index, element in np.ndenumerate(d):
    if element > d_min and element < d_mean:
        f[index] = 25
    elif element > d_mean and element < d_max:
        f[index] = 75
    elif element == d_mean:
        f[index] = 50
    elif element == d_min:
        f[index] = 0
    elif element == d_max:
        f[index] = 100
print(f)

[[[ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  25.  75.]
  [ 25.  75.  25. 100.  25.]]

 [[  0.  75.  25.  75.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 75.  25.  75.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [45]:
# your code here
print(d)
print()
print(f)

[[[ 85.  89.  47.  21.  47.]
  [ 52.  37.  57.  12.  58.]
  [ 15.  99.  31. 100.  27.]]

 [[  8.  59.  31.  89.  93.]
  [ 13.  84.  90.  16.  70.]
  [ 97.  38.  96.  59.  14.]]]

[[[ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  25.  75.]
  [ 25.  75.  25. 100.  25.]]

 [[  0.  75.  25.  75.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 75.  25.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [46]:
# your code here
f = f.astype(str)
for index, element in np.ndenumerate(d):
    if element > d_min and element < d_mean:
        f[index] = "A"
    elif element > d_mean and element < d_max:
        f[index] = "B"
    elif element == d_mean:
        f[index] = "C"
    elif element == d_min:
        f[index] = "D"
    elif element == d_max:
        f[index] = "E"
print(f)

[[['B' 'B' 'A' 'A' 'A']
  ['A' 'A' 'B' 'A' 'B']
  ['A' 'B' 'A' 'E' 'A']]

 [['D' 'B' 'A' 'B' 'B']
  ['A' 'B' 'B' 'A' 'B']
  ['B' 'A' 'B' 'B' 'A']]]
