# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__


'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.randint(0, 2, size=(2, 3, 5)) #only integers
print(a)

[[[1 0 0 0 1]
  [0 1 1 0 1]
  [1 1 1 1 0]]

 [[0 0 1 1 0]
  [0 1 0 0 0]
  [1 0 1 1 0]]]


In [4]:
# Method 2
a = np.random.random((2,3,5)) #flots admitted
a

array([[[0.67448802, 0.09066304, 0.89861514, 0.69612728, 0.37898204],
        [0.87703149, 0.08658549, 0.33045749, 0.80787954, 0.63642241],
        [0.78271567, 0.88497126, 0.04837985, 0.52584781, 0.76153239]],

       [[0.06262703, 0.82859009, 0.79542958, 0.8613605 , 0.35828973],
        [0.00987296, 0.69388062, 0.06536772, 0.65064019, 0.54616789],
        [0.41177846, 0.63559856, 0.65699941, 0.26606913, 0.40088256]]])

In [5]:
# Method 3

a= np.random.rand ( 2,3,5)
a

array([[[0.98613998, 0.50273359, 0.29271566, 0.33341757, 0.44363935],
        [0.38068508, 0.79965542, 0.39026905, 0.33903468, 0.72764023],
        [0.43559984, 0.41188203, 0.73090106, 0.84999047, 0.16926153]],

       [[0.96025388, 0.56438926, 0.33497493, 0.76793525, 0.70772927],
        [0.90561825, 0.32736568, 0.36607556, 0.47085054, 0.12693903],
        [0.38448776, 0.27193883, 0.4829352 , 0.29049642, 0.36256111]]])

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.98613998 0.50273359 0.29271566 0.33341757 0.44363935]
  [0.38068508 0.79965542 0.39026905 0.33903468 0.72764023]
  [0.43559984 0.41188203 0.73090106 0.84999047 0.16926153]]

 [[0.96025388 0.56438926 0.33497493 0.76793525 0.70772927]
  [0.90561825 0.32736568 0.36607556 0.47085054 0.12693903]
  [0.38448776 0.27193883 0.4829352  0.29049642 0.36256111]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b=np.ones((5,2,3))



#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print("This is a:", a.shape)
print("This is b:", b.shape)
#they have different sizes

This is a: (2, 3, 5)
This is b: (5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
print("This is a:",a)
print("This is b:",b)
print("This is a+b",a + b)
#ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3

This is a: [[[0.98613998 0.50273359 0.29271566 0.33341757 0.44363935]
  [0.38068508 0.79965542 0.39026905 0.33903468 0.72764023]
  [0.43559984 0.41188203 0.73090106 0.84999047 0.16926153]]

 [[0.96025388 0.56438926 0.33497493 0.76793525 0.70772927]
  [0.90561825 0.32736568 0.36607556 0.47085054 0.12693903]
  [0.38448776 0.27193883 0.4829352  0.29049642 0.36256111]]]
This is b: [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = np.transpose(b,(1,2,0))

print(a.shape)
print(b.shape)
print(c.shape)

#np.transpose(x, (1, 0, 2)).shape
#(2, 1, 3)

(2, 3, 5)
(5, 2, 3)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = a+c
d

array([[[1.98613998, 1.50273359, 1.29271566, 1.33341757, 1.44363935],
        [1.38068508, 1.79965542, 1.39026905, 1.33903468, 1.72764023],
        [1.43559984, 1.41188203, 1.73090106, 1.84999047, 1.16926153]],

       [[1.96025388, 1.56438926, 1.33497493, 1.76793525, 1.70772927],
        [1.90561825, 1.32736568, 1.36607556, 1.47085054, 1.12693903],
        [1.38448776, 1.27193883, 1.4829352 , 1.29049642, 1.36256111]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)
#They are the same size, d is the result of a +  one matrix

[[[0.98613998 0.50273359 0.29271566 0.33341757 0.44363935]
  [0.38068508 0.79965542 0.39026905 0.33903468 0.72764023]
  [0.43559984 0.41188203 0.73090106 0.84999047 0.16926153]]

 [[0.96025388 0.56438926 0.33497493 0.76793525 0.70772927]
  [0.90561825 0.32736568 0.36607556 0.47085054 0.12693903]
  [0.38448776 0.27193883 0.4829352  0.29049642 0.36256111]]]
[[[1.98613998 1.50273359 1.29271566 1.33341757 1.44363935]
  [1.38068508 1.79965542 1.39026905 1.33903468 1.72764023]
  [1.43559984 1.41188203 1.73090106 1.84999047 1.16926153]]

 [[1.96025388 1.56438926 1.33497493 1.76793525 1.70772927]
  [1.90561825 1.32736568 1.36607556 1.47085054 1.12693903]
  [1.38448776 1.27193883 1.4829352  1.29049642 1.36256111]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = a*c
e

array([[[0.98613998, 0.50273359, 0.29271566, 0.33341757, 0.44363935],
        [0.38068508, 0.79965542, 0.39026905, 0.33903468, 0.72764023],
        [0.43559984, 0.41188203, 0.73090106, 0.84999047, 0.16926153]],

       [[0.96025388, 0.56438926, 0.33497493, 0.76793525, 0.70772927],
        [0.90561825, 0.32736568, 0.36607556, 0.47085054, 0.12693903],
        [0.38448776, 0.27193883, 0.4829352 , 0.29049642, 0.36256111]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print("This is a",a)
print("This is e",e)
print("This is c",c)

#They are equal because c is a 1 MATRIX

This is a [[[0.98613998 0.50273359 0.29271566 0.33341757 0.44363935]
  [0.38068508 0.79965542 0.39026905 0.33903468 0.72764023]
  [0.43559984 0.41188203 0.73090106 0.84999047 0.16926153]]

 [[0.96025388 0.56438926 0.33497493 0.76793525 0.70772927]
  [0.90561825 0.32736568 0.36607556 0.47085054 0.12693903]
  [0.38448776 0.27193883 0.4829352  0.29049642 0.36256111]]]
This is e [[[0.98613998 0.50273359 0.29271566 0.33341757 0.44363935]
  [0.38068508 0.79965542 0.39026905 0.33903468 0.72764023]
  [0.43559984 0.41188203 0.73090106 0.84999047 0.16926153]]

 [[0.96025388 0.56438926 0.33497493 0.76793525 0.70772927]
  [0.90561825 0.32736568 0.36607556 0.47085054 0.12693903]
  [0.38448776 0.27193883 0.4829352  0.29049642 0.36256111]]]
This is c [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)
print("This is d:",d)

1.986139979051302
1.1269390303058395
1.503937216814979
This is d: [[[1.98613998 1.50273359 1.29271566 1.33341757 1.44363935]
  [1.38068508 1.79965542 1.39026905 1.33903468 1.72764023]
  [1.43559984 1.41188203 1.73090106 1.84999047 1.16926153]]

 [[1.96025388 1.56438926 1.33497493 1.76793525 1.70772927]
  [1.90561825 1.32736568 1.36607556 1.47085054 1.12693903]
  [1.38448776 1.27193883 1.4829352  1.29049642 1.36256111]]]


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f = np.empty([2,3,5])
f



array([[[1.98613998, 1.50273359, 1.29271566, 1.33341757, 1.44363935],
        [1.38068508, 1.79965542, 1.39026905, 1.33903468, 1.72764023],
        [1.43559984, 1.41188203, 1.73090106, 1.84999047, 1.16926153]],

       [[1.96025388, 1.56438926, 1.33497493, 1.76793525, 1.70772927],
        [1.90561825, 1.32736568, 1.36607556, 1.47085054, 1.12693903],
        [1.38448776, 1.27193883, 1.4829352 , 1.29049642, 1.36256111]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

# your code here





- d_min < i < d_mean = 25
- d_mean < i < d_max = 75
- i == d_mean = 50
- i == d_mean = 0
- i == dm_max = 100


In [22]:
f = [[
         [25 if d_min<item<d_mean 
          else 75 if d_mean<item< d_max 
          else 0 if item == d_min 
          else 50 if item == d_mean
          else 100 for item in in_list] #tercer nivel de iteración, donde estan los valores y donde tenemos que meter las condiciones
        for in_list in out_list] #segundo nivel de iteración
        for out_list in d] #primer nivel de iteración

f

[[[100, 25, 25, 25, 25], [25, 75, 25, 25, 75], [25, 25, 75, 75, 25]],
 [[75, 75, 25, 75, 75], [75, 25, 25, 25, 0], [25, 25, 25, 25, 25]]]

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [21]:
# your code here
print(d)
print(f)

[[[1.98613998 1.50273359 1.29271566 1.33341757 1.44363935]
  [1.38068508 1.79965542 1.39026905 1.33903468 1.72764023]
  [1.43559984 1.41188203 1.73090106 1.84999047 1.16926153]]

 [[1.96025388 1.56438926 1.33497493 1.76793525 1.70772927]
  [1.90561825 1.32736568 1.36607556 1.47085054 1.12693903]
  [1.38448776 1.27193883 1.4829352  1.29049642 1.36256111]]]
[[[100, 25, 25, 25, 25], [25, 75, 25, 25, 75], [25, 25, 75, 75, 25]], [[75, 75, 25, 75, 75], [75, 25, 25, 25, 0], [25, 25, 25, 25, 25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [23]:
# your code here
f = [[
         [ 'B' if d_min<item<d_mean 
          else 'D' if d_mean<item< d_max 
          else 'A' if item == d_min 
          else 'C' if item == d_mean
          else 'E' for item in in_list] #tercer nivel de iteración, donde estan los valores y donde tenemos que meter las condiciones
        for in_list in out_list] #segundo nivel de iteración
        for out_list in d] #primer nivel de iteración

f

[[['E', 'B', 'B', 'B', 'B'],
  ['B', 'D', 'B', 'B', 'D'],
  ['B', 'B', 'D', 'D', 'B']],
 [['D', 'D', 'B', 'D', 'D'],
  ['D', 'B', 'B', 'B', 'A'],
  ['B', 'B', 'B', 'B', 'B']]]