# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
matrix_a1 = np.random.random((2,3,5))

In [4]:
# Method 2
matrix_a2 = np.random.randint(0, 10, size=(2,3,5))

In [5]:
# Method 3
matrix_a3 = np.random.rand(2,3,5)

#### 4. Print *a*.


In [6]:
# your code here
print(matrix_a1); print(np.sum(matrix_a1))
print('\n')
print(matrix_a2); print(np.sum(matrix_a2))
print('\n')
print(matrix_a3); print(np.sum(matrix_a3))

[[[0.63738609 0.51900223 0.48170354 0.79620774 0.24801222]
  [0.52389055 0.51962959 0.20853137 0.67102843 0.79062783]
  [0.94432205 0.09672956 0.59041362 0.07885209 0.1130005 ]]

 [[0.4482097  0.32917091 0.65512199 0.01687548 0.77570553]
  [0.88740604 0.52204082 0.38703411 0.91822614 0.79666041]
  [0.8870472  0.71302038 0.24458975 0.64363166 0.71817414]]]
16.16225168014717


[[[1 9 7 2 4]
  [0 0 6 3 9]
  [2 2 2 7 4]]

 [[4 4 4 6 4]
  [4 2 2 0 0]
  [8 0 6 2 1]]]
105


[[[0.39640163 0.55832255 0.27379814 0.66002391 0.05904733]
  [0.43202153 0.37592617 0.11776592 0.77278702 0.81400713]
  [0.44151475 0.76414261 0.724871   0.30365962 0.76459904]]

 [[0.75139016 0.81346157 0.3024834  0.70852028 0.7060878 ]
  [0.51962688 0.81416602 0.70055224 0.29831637 0.10603844]
  [0.34147629 0.96627762 0.95868496 0.28726037 0.26186293]]]
15.995093678445276


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
matrix_b1 = np.full((5,2,3), 1)

#### 6. Print *b*.


In [8]:
# your code here
print(matrix_b1)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(np.size(matrix_a1) == np.size(matrix_b1))
print(np.size(matrix_a2) == np.size(matrix_b1))
print(np.size(matrix_a3) == np.size(matrix_b1))

True
True
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
""" matrix_c = matrix_a1 + matrix_b1 """
# Not possible: ValueError operands could not be broadcast together with shapes (2,3,5) & (5,2,3)

print("It is not possible to apply Operation Overload with different sized arrays")

It is not possible to apply Operation Overload with different sized arrays


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
matrix_b2 = (matrix_b1.transpose(1,2,0))
print(matrix_b2)
print('\n')
print(matrix_a1)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


[[[0.63738609 0.51900223 0.48170354 0.79620774 0.24801222]
  [0.52389055 0.51962959 0.20853137 0.67102843 0.79062783]
  [0.94432205 0.09672956 0.59041362 0.07885209 0.1130005 ]]

 [[0.4482097  0.32917091 0.65512199 0.01687548 0.77570553]
  [0.88740604 0.52204082 0.38703411 0.91822614 0.79666041]
  [0.8870472  0.71302038 0.24458975 0.64363166 0.71817414]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
matrix_d = matrix_a1 + matrix_b2

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(matrix_a1)
print('\n')
print(matrix_d)

"""Sum overload has added each item with each item between matrices"""

[[[0.63738609 0.51900223 0.48170354 0.79620774 0.24801222]
  [0.52389055 0.51962959 0.20853137 0.67102843 0.79062783]
  [0.94432205 0.09672956 0.59041362 0.07885209 0.1130005 ]]

 [[0.4482097  0.32917091 0.65512199 0.01687548 0.77570553]
  [0.88740604 0.52204082 0.38703411 0.91822614 0.79666041]
  [0.8870472  0.71302038 0.24458975 0.64363166 0.71817414]]]


[[[1.63738609 1.51900223 1.48170354 1.79620774 1.24801222]
  [1.52389055 1.51962959 1.20853137 1.67102843 1.79062783]
  [1.94432205 1.09672956 1.59041362 1.07885209 1.1130005 ]]

 [[1.4482097  1.32917091 1.65512199 1.01687548 1.77570553]
  [1.88740604 1.52204082 1.38703411 1.91822614 1.79666041]
  [1.8870472  1.71302038 1.24458975 1.64363166 1.71817414]]]


'Sum overload has added each item with each item between matrices'

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
matrix_e = matrix_a1 * matrix_b2
print(matrix_e)

[[[0.63738609 0.51900223 0.48170354 0.79620774 0.24801222]
  [0.52389055 0.51962959 0.20853137 0.67102843 0.79062783]
  [0.94432205 0.09672956 0.59041362 0.07885209 0.1130005 ]]

 [[0.4482097  0.32917091 0.65512199 0.01687548 0.77570553]
  [0.88740604 0.52204082 0.38703411 0.91822614 0.79666041]
  [0.8870472  0.71302038 0.24458975 0.64363166 0.71817414]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print(matrix_e == matrix_a1)

"""Matrix are the same since matrix_b2 is a matrix formed by ones and its multiplication is the same matrix_a1"""

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


'Matrix are the same since matrix_b2 is a matrix formed by ones and its multiplication is the same matrix_a1'

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
# matrix_d = matrix_a1 + matrix_b2 (should be c)

d_max = matrix_d.max()
d_mean = matrix_d.mean()
d_min = matrix_d.min()

print(f'max is {d_max}')
print(f'mean is {d_mean}')
print(f'min is {d_min}')
print('\n')
print(matrix_d)



max is 1.9443220454559498
mean is 1.5387417226715725
min is 1.016875479273204


[[[1.63738609 1.51900223 1.48170354 1.79620774 1.24801222]
  [1.52389055 1.51962959 1.20853137 1.67102843 1.79062783]
  [1.94432205 1.09672956 1.59041362 1.07885209 1.1130005 ]]

 [[1.4482097  1.32917091 1.65512199 1.01687548 1.77570553]
  [1.88740604 1.52204082 1.38703411 1.91822614 1.79666041]
  [1.8870472  1.71302038 1.24458975 1.64363166 1.71817414]]]


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
matrix_f = np.empty((2,3,5), dtype=float)
print(matrix_f)

[[[1.63738609 1.51900223 1.48170354 1.79620774 1.24801222]
  [1.52389055 1.51962959 1.20853137 1.67102843 1.79062783]
  [1.94432205 1.09672956 1.59041362 1.07885209 1.1130005 ]]

 [[1.4482097  1.32917091 1.65512199 1.01687548 1.77570553]
  [1.88740604 1.52204082 1.38703411 1.91822614 1.79666041]
  [1.8870472  1.71302038 1.24458975 1.64363166 1.71817414]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
print(f'Before matrix_f: \n{matrix_f}')
print('\n')
# This has to be rerrun with code in 15

matrix_f = np.where(matrix_d == d_min, 0, 
                    np.where(matrix_d < d_mean, 25., 
                             np.where(matrix_d == d_mean, 50., 
                                      np.where(matrix_d < d_max, 75., 
                                               np.where(matrix_d == d_max, 100., 'something is wrong')))))

print(f'After matrix_f: \n{matrix_f}')


Before matrix_f: 
[[[1.63738609 1.51900223 1.48170354 1.79620774 1.24801222]
  [1.52389055 1.51962959 1.20853137 1.67102843 1.79062783]
  [1.94432205 1.09672956 1.59041362 1.07885209 1.1130005 ]]

 [[1.4482097  1.32917091 1.65512199 1.01687548 1.77570553]
  [1.88740604 1.52204082 1.38703411 1.91822614 1.79666041]
  [1.8870472  1.71302038 1.24458975 1.64363166 1.71817414]]]


After matrix_f: 
[[['75.0' '25.0' '25.0' '75.0' '25.0']
  ['25.0' '25.0' '25.0' '75.0' '75.0']
  ['100.0' '25.0' '75.0' '25.0' '25.0']]

 [['25.0' '25.0' '75.0' '0' '75.0']
  ['75.0' '25.0' '25.0' '75.0' '75.0']
  ['75.0' '75.0' '25.0' '75.0' '75.0']]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(f'Matrix_d:\n {matrix_d}')
print('\n')
print(f'Matrix_f:\n {matrix_f}')

Matrix_d:
 [[[1.63738609 1.51900223 1.48170354 1.79620774 1.24801222]
  [1.52389055 1.51962959 1.20853137 1.67102843 1.79062783]
  [1.94432205 1.09672956 1.59041362 1.07885209 1.1130005 ]]

 [[1.4482097  1.32917091 1.65512199 1.01687548 1.77570553]
  [1.88740604 1.52204082 1.38703411 1.91822614 1.79666041]
  [1.8870472  1.71302038 1.24458975 1.64363166 1.71817414]]]


Matrix_f:
 [[['75.0' '25.0' '25.0' '75.0' '25.0']
  ['25.0' '25.0' '25.0' '75.0' '75.0']
  ['100.0' '25.0' '75.0' '25.0' '25.0']]

 [['25.0' '25.0' '75.0' '0' '75.0']
  ['75.0' '25.0' '25.0' '75.0' '75.0']
  ['75.0' '75.0' '25.0' '75.0' '75.0']]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
matrix_g = np.where(matrix_d == d_min, 'A', 
                    np.where(matrix_d < d_mean, 'B', 
                             np.where(matrix_d == d_mean, 'C', 
                                      np.where(matrix_d < d_max, 'D', 
                                               np.where(matrix_d == d_max, 'E', 'something is wrong')))))

print(f'Matrix_g: \n{matrix_g}')


Matrix_g: 
[[['D' 'B' 'B' 'D' 'B']
  ['B' 'B' 'B' 'D' 'D']
  ['E' 'B' 'D' 'B' 'B']]

 [['B' 'B' 'D' 'A' 'D']
  ['D' 'B' 'B' 'D' 'D']
  ['D' 'D' 'B' 'D' 'D']]]
