# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np


#### 2. Print your NumPy version.

In [20]:
# your code here

! pip list | grep numpy


numpy            1.18.1             


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [13]:
# Method 1

a = np.random.random((2,3,5))

a


array([[[0.86161477, 0.9073734 , 0.45415957, 0.41713121, 0.32620773],
        [0.01605977, 0.1657595 , 0.8237766 , 0.84691774, 0.63438353],
        [0.99868636, 0.27934115, 0.9454686 , 0.89111929, 0.39640198]],

       [[0.61494395, 0.00153142, 0.26356006, 0.92861815, 0.99045421],
        [0.84070194, 0.18097144, 0.55202818, 0.79438257, 0.50684355],
        [0.42862373, 0.33112073, 0.90557245, 0.54581046, 0.88733657]]])

In [56]:
# Method 2

a = np.random.choice(range(100), size = (2,3,5))

a


array([[[39, 26, 81, 41, 53],
        [74, 10, 92, 50, 59],
        [33, 46, 64, 42,  0]],

       [[20, 67, 36, 63, 99],
        [85, 34, 94, 25, 88],
        [20, 59, 45, 58, 14]]])

In [50]:
# Method 3

a = np.random.randint(100,size = (2,3,5))

a

array([[[39, 29, 83,  5, 96],
        [89, 63,  6, 79, 23],
        [73, 52, 59, 53,  9]],

       [[95,  3,  9, 64, 71],
        [93, 98, 61, 61, 31],
        [77, 99, 77, 42, 87]]])

#### 4. Print *a*.


In [57]:
# your code here

print(a)

[[[39 26 81 41 53]
  [74 10 92 50 59]
  [33 46 64 42  0]]

 [[20 67 36 63 99]
  [85 34 94 25 88]
  [20 59 45 58 14]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [70]:
# your code here

b = np.ones((5,2,3))


#### 6. Print *b*.


In [59]:
# your code here

b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [62]:
# your code here

print(a.size == b.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [63]:
# your answer here

#They have the same size but not the same shape.

print(a.shape == b.shape)

False


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [75]:
# your code here

c = np.transpose(b,(1,2,0))

c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [77]:
# your code/answer here

d = a + c

print(a.shape == c.shape)

True


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [84]:
# your code/answer here

print(d)
print(a)

d == a + 1


[[[ 40.  27.  82.  42.  54.]
  [ 75.  11.  93.  51.  60.]
  [ 34.  47.  65.  43.   1.]]

 [[ 21.  68.  37.  64. 100.]
  [ 86.  35.  95.  26.  89.]
  [ 21.  60.  46.  59.  15.]]]
[[[39 26 81 41 53]
  [74 10 92 50 59]
  [33 46 64 42  0]]

 [[20 67 36 63 99]
  [85 34 94 25 88]
  [20 59 45 58 14]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [85]:
# your code here

e = a * c

e

array([[[39., 26., 81., 41., 53.],
        [74., 10., 92., 50., 59.],
        [33., 46., 64., 42.,  0.]],

       [[20., 67., 36., 63., 99.],
        [85., 34., 94., 25., 88.],
        [20., 59., 45., 58., 14.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [81]:
# your code/answer here

print(e == a)

'''
Numpy doesn't make the mathematical multiplication by default,it just multiplies each element by the one in
their similar position in the other matrix.
'''

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [97]:
# your code here

d_min = d.min()
d_max = d.max()
d_mean = np.mean(d)

print(d_min)
print(d_max)
print(d_mean)

1.0
100.0
51.56666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [105]:
# your code here

f = np.empty((2,3,5))



numpy.ndarray

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [119]:
# your code here

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i,j])):
            if d_min < d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d_mean < d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [126]:
# your code here

print('d is:\n', d)

print('f is:\n', f)

d is:
 [[[ 40.  27.  82.  42.  54.]
  [ 75.  11.  93.  51.  60.]
  [ 34.  47.  65.  43.   1.]]

 [[ 21.  68.  37.  64. 100.]
  [ 86.  35.  95.  26.  89.]
  [ 21.  60.  46.  59.  15.]]]
f is:
 [[[ 25.  25.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  25.  75.  25.   0.]]

 [[ 25.  75.  25.  75. 100.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [135]:
# your code here

f = np.array(np.empty((2,3,5)), dtype = object)

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i,j])):
            if d_min < d[i,j,k] < d_mean:
                f[i,j,k] = 'B'
            elif d_mean < d[i,j,k] < d_max:
                f[i,j,k] = 'D'
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 'C'
            elif d[i,j,k] == d_min:
                f[i,j,k] = 'A'
            elif d[i,j,k] == d_max:
                f[i,j,k] = 'E'


print(f)

[[['B' 'B' 'D' 'B' 'D']
  ['D' 'B' 'D' 'B' 'D']
  ['B' 'B' 'D' 'B' 'A']]

 [['B' 'D' 'B' 'D' 'E']
  ['D' 'B' 'D' 'B' 'D']
  ['B' 'D' 'B' 'D' 'B']]]
