# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [177]:
import numpy as np

#### 2. Print your NumPy version.

In [178]:
np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [179]:
a = np.random.random((2,3,5))
a

array([[[0.68425031, 0.83498602, 0.86684128, 0.55277872, 0.04760245],
        [0.83839272, 0.23032824, 0.36835613, 0.934139  , 0.04709137],
        [0.60841448, 0.51685508, 0.41433599, 0.11785733, 0.07370011]],

       [[0.06922728, 0.59418865, 0.8386293 , 0.09939473, 0.76106222],
        [0.64521466, 0.43219667, 0.03465112, 0.11287647, 0.09706602],
        [0.28421456, 0.94346525, 0.57360763, 0.79460823, 0.41075272]]])

In [180]:
a = np.random.rand(2,3,5)
a

array([[[0.51193263, 0.99532388, 0.41821934, 0.13145257, 0.68269857],
        [0.93930849, 0.92412262, 0.18699939, 0.25821252, 0.63089543],
        [0.8004733 , 0.97605637, 0.85090199, 0.95256526, 0.30036984]],

       [[0.49799339, 0.14720801, 0.53525827, 0.04859456, 0.96850084],
        [0.80910465, 0.37655071, 0.12621581, 0.51318137, 0.59560873],
        [0.2722631 , 0.9405629 , 0.48563593, 0.43981819, 0.15325878]]])

#### 4. Print *a*.


In [181]:
print(a)

[[[0.51193263 0.99532388 0.41821934 0.13145257 0.68269857]
  [0.93930849 0.92412262 0.18699939 0.25821252 0.63089543]
  [0.8004733  0.97605637 0.85090199 0.95256526 0.30036984]]

 [[0.49799339 0.14720801 0.53525827 0.04859456 0.96850084]
  [0.80910465 0.37655071 0.12621581 0.51318137 0.59560873]
  [0.2722631  0.9405629  0.48563593 0.43981819 0.15325878]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [182]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [183]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [184]:
a.size == b.size


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [185]:
# We can NOT add those two arrays cause they dont have the same shape.
a.shape == b.shape

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [186]:
c = np.transpose(b,(1,2,0))
c



array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [187]:
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [188]:
d # We have the same A array but adding one for each number. The sum of arrays respects the order of echa number.

array([[[1.51193263, 1.99532388, 1.41821934, 1.13145257, 1.68269857],
        [1.93930849, 1.92412262, 1.18699939, 1.25821252, 1.63089543],
        [1.8004733 , 1.97605637, 1.85090199, 1.95256526, 1.30036984]],

       [[1.49799339, 1.14720801, 1.53525827, 1.04859456, 1.96850084],
        [1.80910465, 1.37655071, 1.12621581, 1.51318137, 1.59560873],
        [1.2722631 , 1.9405629 , 1.48563593, 1.43981819, 1.15325878]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [189]:
e = np.multiply(a,c)
display(a)
e


array([[[0.51193263, 0.99532388, 0.41821934, 0.13145257, 0.68269857],
        [0.93930849, 0.92412262, 0.18699939, 0.25821252, 0.63089543],
        [0.8004733 , 0.97605637, 0.85090199, 0.95256526, 0.30036984]],

       [[0.49799339, 0.14720801, 0.53525827, 0.04859456, 0.96850084],
        [0.80910465, 0.37655071, 0.12621581, 0.51318137, 0.59560873],
        [0.2722631 , 0.9405629 , 0.48563593, 0.43981819, 0.15325878]]])

array([[[0.51193263, 0.99532388, 0.41821934, 0.13145257, 0.68269857],
        [0.93930849, 0.92412262, 0.18699939, 0.25821252, 0.63089543],
        [0.8004733 , 0.97605637, 0.85090199, 0.95256526, 0.30036984]],

       [[0.49799339, 0.14720801, 0.53525827, 0.04859456, 0.96850084],
        [0.80910465, 0.37655071, 0.12621581, 0.51318137, 0.59560873],
        [0.2722631 , 0.9405629 , 0.48563593, 0.43981819, 0.15325878]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [190]:
#Yes becasuse we are multipliying by one.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [208]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


d_mean

1.5489762482815144

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [209]:
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [217]:
'''
Hay algo que no acabo de entender con la asignación de valores a variables en Jupyter. 
No va sobreescribiendo de arriba hacia abajo sobre escribiendo no?? ejecutar una celda 
superior no resetea el valor de la variable?
Suelo tener muchos problemas con este tema, creo que trabajo con un valor y es otro...

Por otro lado, he intentado solucionar este ejercicio por mi cuenta. (no tan spaguetti code)
Como se haría bien??
'''

for dimension in range(len(d)):

    for row in range(len(d[dimension])):

        for val in range(len(d[dimension][row])):
            
            numero = d[dimension][row][val]
            

            if numero > d_min and numero < d_mean:
                f[dimension][row][val] = 25
                
            elif numero > d_mean and numero < d_max:
                f[dimension][row][val] = 75
                
            elif numero == d_mean:
                f[dimension][row][val] = 50
                
            elif numero == d_min:
                f[dimension][row][val] = 0
                
            else:
                f[dimension][row][val] = 100
          
f

array([[[ 25., 100.,  25.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  75.],
        [ 75.,  75.,  75.,  75.,  25.]],

       [[ 25.,  25.,  25.,   0.,  75.],
        [ 75.,  25.,  25.,  25.,  75.],
        [ 25.,  75.,  25.,  25.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [218]:
d,f

(array([[[1.51193263, 1.99532388, 1.41821934, 1.13145257, 1.68269857],
         [1.93930849, 1.92412262, 1.18699939, 1.25821252, 1.63089543],
         [1.8004733 , 1.97605637, 1.85090199, 1.95256526, 1.30036984]],
 
        [[1.49799339, 1.14720801, 1.53525827, 1.04859456, 1.96850084],
         [1.80910465, 1.37655071, 1.12621581, 1.51318137, 1.59560873],
         [1.2722631 , 1.9405629 , 1.48563593, 1.43981819, 1.15325878]]]),
 array([[[ 25., 100.,  25.,  25.,  75.],
         [ 75.,  75.,  25.,  25.,  75.],
         [ 75.,  75.,  75.,  75.,  25.]],
 
        [[ 25.,  25.,  25.,   0.,  75.],
         [ 75.,  25.,  25.,  25.,  75.],
         [ 25.,  75.,  25.,  25.,  25.]]]))

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [225]:
f = np.empty((2,3,5), dtype=str)

for dimension in range(len(d)):

    for row in range(len(d[dimension])):

        for val in range(len(d[dimension][row])):
            
            numero = d[dimension][row][val]
            

            if numero > d_min and numero < d_mean:
                f[dimension][row][val] = 'B'
                
            elif numero > d_mean and numero < d_max:
                f[dimension][row][val] = 'D'
                
            elif numero == d_mean:
                f[dimension][row][val] = 'C'
                
            elif numero == d_min:
                f[dimension][row][val] = 'A'
                
            else:
                f[dimension][row][val] = 'E'
          
f

array([[['B', 'E', 'B', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'D'],
        ['D', 'D', 'D', 'D', 'B']],

       [['B', 'B', 'B', 'A', 'D'],
        ['D', 'B', 'B', 'B', 'D'],
        ['B', 'D', 'B', 'B', 'B']]], dtype='<U1')