# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1 - This method creates an aleatory array
# a=np.random.rand(2,3,5) have the same output
a=np.random.random([2,3,5])
print((a))

[[[0.24799606 0.12356791 0.70268614 0.31813251 0.45561194]
  [0.59167214 0.14024317 0.22442223 0.3207159  0.13579013]
  [0.83650415 0.94182823 0.23909604 0.42257698 0.60927084]]

 [[0.32448904 0.27832227 0.06604922 0.01203428 0.67457379]
  [0.17494267 0.94526874 0.17939841 0.31959612 0.67376195]
  [0.1503299  0.63935384 0.38151711 0.66889355 0.33597925]]]


In [4]:
# Method 2 - This method creates an array containing random integer values between 0 and 40
a=np.random.randint(0, 40, size=(2, 3, 5))
print(a)

[[[39 35 34 29  8]
  [27 11 16 19 17]
  [14  0 29 39  2]]

 [[ 9 35 32  1  9]
  [24 26  5 30  1]
  [20 15  1  3 28]]]


In [5]:
# Method 3 - This method creates an array containing random floating values between 10 and 5
a=np.random.uniform(10,5,(2,3,5))
print(a)


[[[5.86154235 9.24548157 9.04600517 6.345395   7.4948785 ]
  [5.67975236 5.11544794 5.87850396 7.02272966 5.98557893]
  [5.71698846 7.93820659 6.89276723 6.94525871 9.91931996]]

 [[9.87098445 7.22228859 6.49968611 9.84793492 6.65388199]
  [9.96519276 6.24641635 8.38471677 6.85583291 9.00577944]
  [6.55141052 8.02951109 8.75544434 9.88300697 9.99392251]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[5.86154235 9.24548157 9.04600517 6.345395   7.4948785 ]
  [5.67975236 5.11544794 5.87850396 7.02272966 5.98557893]
  [5.71698846 7.93820659 6.89276723 6.94525871 9.91931996]]

 [[9.87098445 7.22228859 6.49968611 9.84793492 6.65388199]
  [9.96519276 6.24641635 8.38471677 6.85583291 9.00577944]
  [6.55141052 8.02951109 8.75544434 9.88300697 9.99392251]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b=np.ones([5,2,3])

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.size)
print(b.size)

a.size==b.size


30
30


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here - It is possible to add a and b, but we have to reshape them first. We either
# - Transform both of them to one-dimesion arrays and add them. If we do not perform the transformation beforehand we get the ValueError showed below
np.concatenate([a,b])
# - Transform one of them to the shape of the other and add both afterwards. This is what we are going to do in the next step.


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
# It could also be done with c=np.reshape(b, a.size)
c=b.transpose(1,2,0)
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here - Now it works because both a and c are in the same dimension/have the same shape
# We could also perform this operation with d=a+c
d=np.add(a,c)
print(d)


[[[ 6.86154235 10.24548157 10.04600517  7.345395    8.4948785 ]
  [ 6.67975236  6.11544794  6.87850396  8.02272966  6.98557893]
  [ 6.71698846  8.93820659  7.89276723  7.94525871 10.91931996]]

 [[10.87098445  8.22228859  7.49968611 10.84793492  7.65388199]
  [10.96519276  7.24641635  9.38471677  7.85583291 10.00577944]
  [ 7.55141052  9.02951109  9.75544434 10.88300697 10.99392251]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here 
# Difference - Array-d's values are exactly a-values' +1 and are located in the same position in both a and d 
# Relation - We should remember that d=a+b and b was made of ones, therefore when you add a and b, d is the expected result
# Array d is equal to array a in size and shape. 
print(a)
print(d)

[[[5.86154235 9.24548157 9.04600517 6.345395   7.4948785 ]
  [5.67975236 5.11544794 5.87850396 7.02272966 5.98557893]
  [5.71698846 7.93820659 6.89276723 6.94525871 9.91931996]]

 [[9.87098445 7.22228859 6.49968611 9.84793492 6.65388199]
  [9.96519276 6.24641635 8.38471677 6.85583291 9.00577944]
  [6.55141052 8.02951109 8.75544434 9.88300697 9.99392251]]]
[[[ 6.86154235 10.24548157 10.04600517  7.345395    8.4948785 ]
  [ 6.67975236  6.11544794  6.87850396  8.02272966  6.98557893]
  [ 6.71698846  8.93820659  7.89276723  7.94525871 10.91931996]]

 [[10.87098445  8.22228859  7.49968611 10.84793492  7.65388199]
  [10.96519276  7.24641635  9.38471677  7.85583291 10.00577944]
  [ 7.55141052  9.02951109  9.75544434 10.88300697 10.99392251]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
# e=a*c
e=np.multiply(a,c)
print(e)

[[[5.86154235 9.24548157 9.04600517 6.345395   7.4948785 ]
  [5.67975236 5.11544794 5.87850396 7.02272966 5.98557893]
  [5.71698846 7.93820659 6.89276723 6.94525871 9.91931996]]

 [[9.87098445 7.22228859 6.49968611 9.84793492 6.65388199]
  [9.96519276 6.24641635 8.38471677 6.85583291 9.00577944]
  [6.55141052 8.02951109 8.75544434 9.88300697 9.99392251]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
# e is equal to a due to the fact that e is made up of 1 values. Thus, we could state that any array multiplied by another built-on-1-values array is equal to itself

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max= np.max(d)
print(d_max)
d_min= np.min(d)
print(d_min)
d_mean= np.mean(d)
print(d_mean)

10.993922506001503
6.115447944733683
8.628462203337538


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f=np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

f=np.where(d==d_min,0,d)
f=np.where(((f>d_min)&(f<d_mean)),25,f)
f=np.where(f==d_mean,50,f)
f=np.where(((f>d_mean)&(f<d_max)),75,f)
f=np.where(f==d_max,100,f)
print(f)


[[[ 25.  75.  75.  25.  25.]
  [ 25.   0.  25.  25.  25.]
  [ 25.  75.  25.  25.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.  75.  75. 100.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print(f)

[[[ 6.86154235 10.24548157 10.04600517  7.345395    8.4948785 ]
  [ 6.67975236  6.11544794  6.87850396  8.02272966  6.98557893]
  [ 6.71698846  8.93820659  7.89276723  7.94525871 10.91931996]]

 [[10.87098445  8.22228859  7.49968611 10.84793492  7.65388199]
  [10.96519276  7.24641635  9.38471677  7.85583291 10.00577944]
  [ 7.55141052  9.02951109  9.75544434 10.88300697 10.99392251]]]
[[[ 25.  75.  75.  25.  25.]
  [ 25.   0.  25.  25.  25.]
  [ 25.  75.  25.  25.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.  75.  75. 100.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [34]:
# your code here
g=np.empty((2,3,5)) 

In [94]:
lista=[]
for i in np.nditer((f)):
    if i==0:
        lista.append(['A'])
    elif i==25:
        lista.append(['B'])
    elif i==50:
        lista.append('C')
    elif i==75:
        lista.append(['D'])
    else:
        lista.append(['E'])
h=np.array(lista).reshape(2,3,5)
print(f)
print(h)

[[[ 25.  75.  75.  25.  25.]
  [ 25.   0.  25.  25.  25.]
  [ 25.  75.  25.  25.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.  75.  75. 100.]]]
[[['B' 'D' 'D' 'B' 'B']
  ['B' 'A' 'B' 'B' 'B']
  ['B' 'D' 'B' 'B' 'D']]

 [['D' 'B' 'B' 'D' 'B']
  ['D' 'B' 'D' 'B' 'D']
  ['B' 'D' 'D' 'D' 'E']]]


In [ ]:
#Thinkful - Logic Drills: Red and bumpy

In [ ]:
#Insert dashes
lista=[]
def insert_dash(num):
    x=list(str(num))
    acumulador=0
    for y in x:
        while acumulador<2:
            if int(y)%2!=0 and int(y)>0:
                acumulador=+1
                lista.append(str(y))
            else:
                lista.append(y)
        if acumulador>=2 and int(y)%2!=0 and int(y)>0:
            y=str(y)+'-'
            lista.append(y)
        else:
            lista.append(str(y))
    return (''.join(lista))

print(insert_dash(4322771))