# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [8]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [9]:
# Method 1
a = np.random.random((2,3,5))

In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [10]:
# your code here
print(a)

[[[0.69041855 0.01150633 0.90170759 0.57111707 0.96686678]
  [0.03584627 0.52725025 0.89042939 0.86876554 0.98138747]
  [0.68777863 0.2957235  0.60473959 0.02430034 0.23254395]]

 [[0.65549692 0.8411211  0.0282136  0.21101122 0.42913185]
  [0.09369617 0.74397909 0.67537829 0.3681362  0.14141584]
  [0.79680445 0.12705223 0.31331724 0.17547084 0.04952399]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [13]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [14]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [15]:
# your code here
if ((a.size)) == int((b.size)):
    print("They have the same size")
else:
    print("They have different size")

They have the same shape


#### 8. Are you able to add *a* and *b*? Why or why not?


In [20]:
# your answer here

try:
    sum_ab = a + b
    print(sum_ab)
except:
    print("Dimmensions are not the same, so this print it an exception")


Dimmensions are not the same, so this print it an exception


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [22]:
# your code here
c = np.transpose(b, (1,2,0))
print((c.shape))

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [23]:
# your code/answer here
d = a + c
print(d)

[[[1.69041855 1.01150633 1.90170759 1.57111707 1.96686678]
  [1.03584627 1.52725025 1.89042939 1.86876554 1.98138747]
  [1.68777863 1.2957235  1.60473959 1.02430034 1.23254395]]

 [[1.65549692 1.8411211  1.0282136  1.21101122 1.42913185]
  [1.09369617 1.74397909 1.67537829 1.3681362  1.14141584]
  [1.79680445 1.12705223 1.31331724 1.17547084 1.04952399]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [41]:
# your code/answer here

print(a)
print(d)

[[[0.69041855 0.01150633 0.90170759 0.57111707 0.96686678]
  [0.03584627 0.52725025 0.89042939 0.86876554 0.98138747]
  [0.68777863 0.2957235  0.60473959 0.02430034 0.23254395]]

 [[0.65549692 0.8411211  0.0282136  0.21101122 0.42913185]
  [0.09369617 0.74397909 0.67537829 0.3681362  0.14141584]
  [0.79680445 0.12705223 0.31331724 0.17547084 0.04952399]]]
[[[1.69041855 1.01150633 1.90170759 1.57111707 1.96686678]
  [1.03584627 1.52725025 1.89042939 1.86876554 1.98138747]
  [1.68777863 1.2957235  1.60473959 1.02430034 1.23254395]]

 [[1.65549692 1.8411211  1.0282136  1.21101122 1.42913185]
  [1.09369617 1.74397909 1.67537829 1.3681362  1.14141584]
  [1.79680445 1.12705223 1.31331724 1.17547084 1.04952399]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [40]:
# your code here
e = a * c
print(e)


[[[0.69041855 0.01150633 0.90170759 0.57111707 0.96686678]
  [0.03584627 0.52725025 0.89042939 0.86876554 0.98138747]
  [0.68777863 0.2957235  0.60473959 0.02430034 0.23254395]]

 [[0.65549692 0.8411211  0.0282136  0.21101122 0.42913185]
  [0.09369617 0.74397909 0.67537829 0.3681362  0.14141584]
  [0.79680445 0.12705223 0.31331724 0.17547084 0.04952399]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [29]:
# your code/answer here

if e.all() == a.all():
    print("Si son iguales")
else:
    print("no son iguales")



Si son iguales


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [43]:
# your code here

d_mean = np.mean(d)
d_max = np.max(d)
d_min = np.min(d)

print(d_mean)
print(d_max)
print(d_min)

1.4646710089530495
1.9813874668870999
1.0115063337487626


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here


h =[]
for i in d:
    for j in i:
        for k in j:
            h.append(k)
            
print(f'Esta es la lista {h}')

print(f' Esta es la media: {d_mean}')
print(f' Este es el máximo: {d_max}')
print(f' Este es el mínimo: {d_min}')
            
result = []            
for i in h:
    if i > d_min and i < d_mean:
        result.append(25)
    elif i > d_mean and i < d_max:
        result.append(75)
    elif i == d_mean:
        result.append(50)
    elif i == d_min:
        result.append(0)
    elif i == d_max:
        result.append(100)

print(f'Esta es la primera: {result}')
    

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here