# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
# Method 1
a = np.random.random((2, 3, 5))
a

array([[[0.99958366, 0.37718501, 0.85784333, 0.18138995, 0.16504141],
        [0.60845717, 0.8701555 , 0.97887472, 0.25537744, 0.80601636],
        [0.21300244, 0.39004844, 0.09378265, 0.47488254, 0.73398402]],

       [[0.45234621, 0.04315573, 0.57040518, 0.61922105, 0.82160695],
        [0.37745154, 0.31276304, 0.07352622, 0.12719983, 0.32954511],
        [0.73549133, 0.82840878, 0.11699116, 0.64304309, 0.89488822]]])

In [12]:
# Method 2
a = np.random.randint(10, size=(2, 3, 5))
a

array([[[1, 9, 4, 0, 5],
        [7, 3, 9, 1, 1],
        [1, 8, 6, 9, 3]],

       [[9, 2, 2, 0, 7],
        [3, 4, 8, 0, 1],
        [6, 0, 9, 8, 1]]])

In [58]:
# Method 3
a = np.empty([2, 3, 5])
a

array([[[ 2., 10.,  5.,  1.,  6.],
        [ 8.,  4., 10.,  2.,  2.],
        [ 2.,  9.,  7., 10.,  4.]],

       [[10.,  3.,  3.,  1.,  8.],
        [ 4.,  5.,  9.,  1.,  2.],
        [ 7.,  1., 10.,  9.,  2.]]])

#### 4. Print *a*.


In [13]:
# your code here
print(a)

[[[1 9 4 0 5]
  [7 3 9 1 1]
  [1 8 6 9 3]]

 [[9 2 2 0 7]
  [3 4 8 0 1]
  [6 0 9 8 1]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [17]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [19]:
# your code here
f'Do a and b have the same size? {a.size == b.size}'

'Do a and b have the same size? True'

#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here

"""
It is not possible add a and b because they have different shapes
"""

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [29]:
# your code here
c = np.reshape(b, (2, 3, 5))
c

""""
It is not possible using c = b.T because it return a 3x2x5 array

After looking at some mates comments it can be done with transpose by this way -> b.transpose(2,1,0) and this is the correct way.
""""

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [34]:
# your code/answer here
d = np.add(a, c)

"""
Now works because both arrays have the same shape
It can also be done with d = a + c
"""
d

array([[[ 2., 10.,  5.,  1.,  6.],
        [ 8.,  4., 10.,  2.,  2.],
        [ 2.,  9.,  7., 10.,  4.]],

       [[10.,  3.,  3.,  1.,  8.],
        [ 4.,  5.,  9.,  1.,  2.],
        [ 7.,  1., 10.,  9.,  2.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [38]:
# your code/answer here
print(a)
print()
print('----------------------------')
print()
print(d)

"""
Both arrays have the same shape but diferent value types. 
a values are integers
d values are floats
"""

[[[1 9 4 0 5]
  [7 3 9 1 1]
  [1 8 6 9 3]]

 [[9 2 2 0 7]
  [3 4 8 0 1]
  [6 0 9 8 1]]]

----------------------------

[[[ 2. 10.  5.  1.  6.]
  [ 8.  4. 10.  2.  2.]
  [ 2.  9.  7. 10.  4.]]

 [[10.  3.  3.  1.  8.]
  [ 4.  5.  9.  1.  2.]
  [ 7.  1. 10.  9.  2.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [41]:
# your code here
e = a * c
e

array([[[1., 9., 4., 0., 5.],
        [7., 3., 9., 1., 1.],
        [1., 8., 6., 9., 3.]],

       [[9., 2., 2., 0., 7.],
        [3., 4., 8., 0., 1.],
        [6., 0., 9., 8., 1.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [45]:
# your code/answer here
print(e == a)
"""
In terms of values, e is equal to a
In term of value types, e is not equal to a
"""

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


'\nIn terms of values, e is equal to a\nIn term of value types, e is not equal to a\n'

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [50]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

10.0
1.0
5.233333333333333


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [97]:
# your code here
f = 0
f = np.empty((2, 3, 5))
f

array([[[  25., 1000.,   25., 1000., 1000.],
        [1000.,   25., 1000.,   25.,   25.],
        [  25., 1000., 1000., 1000.,   25.]],

       [[1000.,   25.,   25., 1000., 1000.],
        [  25.,   25., 1000., 1000.,   25.],
        [1000., 1000., 1000., 1000.,   25.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [98]:
# your code here

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100
        
f

array([[[ 25., 100.,  25.,   0.,  75.],
        [ 75.,  25., 100.,  25.,  25.],
        [ 25.,  75.,  75., 100.,  25.]],

       [[100.,  25.,  25.,   0.,  75.],
        [ 25.,  25.,  75.,   0.,  25.],
        [ 75.,   0., 100.,  75.,  25.]]])

In [81]:
d

array([[[ 2., 10.,  5.,  1.,  6.],
        [ 8.,  4., 10.,  2.,  2.],
        [ 2.,  9.,  7., 10.,  4.]],

       [[10.,  3.,  3.,  1.,  8.],
        [ 4.,  5.,  9.,  1.,  2.],
        [ 7.,  1., 10.,  9.,  2.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [99]:
# your code here
print(d)
print()
print(f)

[[[ 2. 10.  5.  1.  6.]
  [ 8.  4. 10.  2.  2.]
  [ 2.  9.  7. 10.  4.]]

 [[10.  3.  3.  1.  8.]
  [ 4.  5.  9.  1.  2.]
  [ 7.  1. 10.  9.  2.]]]

[[[ 25. 100.  25.   0.  75.]
  [ 75.  25. 100.  25.  25.]
  [ 25.  75.  75. 100.  25.]]

 [[100.  25.  25.   0.  75.]
  [ 25.  25.  75.   0.  25.]
  [ 75.   0. 100.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [105]:
# your code here
g = 0
g = np.empty((2, 3, 5), dtype=str)
g

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [106]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                g[i][j][k] = 'B'
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                g[i][j][k] = 'D'
            elif d[i][j][k] == d_mean:
                g[i][j][k] = 'C'
            elif d[i][j][k] == d_min:
                g[i][j][k] = 'A'
            elif d[i][j][k] == d_max:
                g[i][j][k] = 'E'
        
g

array([[['B', 'E', 'B', 'A', 'D'],
        ['D', 'B', 'E', 'B', 'B'],
        ['B', 'D', 'D', 'E', 'B']],

       [['E', 'B', 'B', 'A', 'D'],
        ['B', 'B', 'D', 'A', 'B'],
        ['D', 'A', 'E', 'D', 'B']]], dtype='<U1')