# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [60]:
# your code here
import numpy as np

In [ ]:
#### 2. Print your NumPy version.

In [14]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [15]:
# Method 1
a = np.random.random((2,3,5))

In [4]:
# Method 2


In [5]:
# Method 3


#### 4. Print *a*.


In [16]:
# your code here
print(a)

[[[0.80096344 0.47458163 0.51954731 0.26453163 0.22841785]
  [0.09040755 0.56108315 0.25876588 0.97427444 0.85110478]
  [0.61954658 0.46585686 0.09340896 0.19909105 0.74863114]]

 [[0.26778867 0.07790109 0.55654427 0.49829066 0.72919818]
  [0.69312827 0.87760441 0.84807751 0.93519878 0.58465027]
  [0.74048891 0.15974571 0.05847395 0.72030696 0.81122173]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [20]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [22]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [23]:
# your code here

a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [24]:
# your answer here
np.add[a,b]
#it's not possible because they have the same shape and the axis doesn't match

TypeError: 'numpy.ufunc' object is not subscriptable

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [25]:
# your code here
c= b.transpose(1,2,0)
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [26]:
# your code/answer here
d = np.add(a,c)
d
#because they have the same shape and the axes match

array([[[1.80096344, 1.47458163, 1.51954731, 1.26453163, 1.22841785],
        [1.09040755, 1.56108315, 1.25876588, 1.97427444, 1.85110478],
        [1.61954658, 1.46585686, 1.09340896, 1.19909105, 1.74863114]],

       [[1.26778867, 1.07790109, 1.55654427, 1.49829066, 1.72919818],
        [1.69312827, 1.87760441, 1.84807751, 1.93519878, 1.58465027],
        [1.74048891, 1.15974571, 1.05847395, 1.72030696, 1.81122173]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [27]:
# your code/answer here
print(a)
print()
print()
print(d)
# "d" has been added +1 en every value.

[[[0.80096344 0.47458163 0.51954731 0.26453163 0.22841785]
  [0.09040755 0.56108315 0.25876588 0.97427444 0.85110478]
  [0.61954658 0.46585686 0.09340896 0.19909105 0.74863114]]

 [[0.26778867 0.07790109 0.55654427 0.49829066 0.72919818]
  [0.69312827 0.87760441 0.84807751 0.93519878 0.58465027]
  [0.74048891 0.15974571 0.05847395 0.72030696 0.81122173]]]


[[[1.80096344 1.47458163 1.51954731 1.26453163 1.22841785]
  [1.09040755 1.56108315 1.25876588 1.97427444 1.85110478]
  [1.61954658 1.46585686 1.09340896 1.19909105 1.74863114]]

 [[1.26778867 1.07790109 1.55654427 1.49829066 1.72919818]
  [1.69312827 1.87760441 1.84807751 1.93519878 1.58465027]
  [1.74048891 1.15974571 1.05847395 1.72030696 1.81122173]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [28]:
# your code here
e = a*c
e

array([[[0.80096344, 0.47458163, 0.51954731, 0.26453163, 0.22841785],
        [0.09040755, 0.56108315, 0.25876588, 0.97427444, 0.85110478],
        [0.61954658, 0.46585686, 0.09340896, 0.19909105, 0.74863114]],

       [[0.26778867, 0.07790109, 0.55654427, 0.49829066, 0.72919818],
        [0.69312827, 0.87760441, 0.84807751, 0.93519878, 0.58465027],
        [0.74048891, 0.15974571, 0.05847395, 0.72030696, 0.81122173]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
#it's the same because we are multiplying * 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [29]:
# your code here
d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

1.9742744447036167
1.0584739489279975
1.5236277205403723


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [55]:
# your code here
f = np.empty([2,3,5])
f


array([[[0.00000000e+000, 1.73059816e-077, 7.90505033e-323,
         0.00000000e+000, 2.12199579e-312],
        [1.16097020e-028, 1.68890714e-052, 2.73785005e-052,
         1.89893724e-052, 5.01163173e+217],
        [8.37170074e-144, 3.38375266e-061, 1.77290155e+160,
         7.42883434e-091, 8.01202552e+165]],

       [[5.01163185e+217, 5.49419094e-143, 9.80058441e+252,
         7.50189709e+247, 1.35617292e+248],
        [1.38976555e+165, 1.56067607e+184, 1.68743722e+160,
         2.69889298e-056, 2.95269806e+179],
        [5.04621361e+180, 8.37170571e-144, 9.30350598e+199,
         5.60230216e-067, 2.10459995e-308]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [119]:
# your code here


for index,value in np.ndenumerate(d):
    if value > d_min and value < d_mean:
        f[index] = 25
    elif value > d_mean and value < d_max:
        f[index] = 75
    elif value == d_mean:
        f[index] = 50
    elif value == d_min:
        f[index] = 0
    elif value == d_max:
        f[index] = 100

        
print(d)
print()
print(f)
    
    
 

[[[1.80096344 1.47458163 1.51954731 1.26453163 1.22841785]
  [1.09040755 1.56108315 1.25876588 1.97427444 1.85110478]
  [1.61954658 1.46585686 1.09340896 1.19909105 1.74863114]]

 [[1.26778867 1.07790109 1.55654427 1.49829066 1.72919818]
  [1.69312827 1.87760441 1.84807751 1.93519878 1.58465027]
  [1.74048891 1.15974571 1.05847395 1.72030696 1.81122173]]]

[[[ 75.  25.  25.  25.  25.]
  [ 25.  75.  25. 100.  75.]
  [ 75.  25.  25.  25.  75.]]

 [[ 25.  25.  75.  25.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  25.   0.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here