# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [63]:
a = np.random.random((2,3,5))

In [64]:
a = np.full((2,3,5), np.random.random())

In [65]:
a = np.empty((2,3,5))

#### 4. Print *a*.


In [66]:
a

array([[[0.5253161 , 0.95671782, 0.05265301, 0.68360436, 0.38937611],
        [0.56387532, 0.98545682, 0.19266634, 0.62269885, 0.51696664],
        [0.28727947, 0.5277015 , 0.40222221, 0.13523375, 0.93079469]],

       [[0.46853841, 0.02577292, 0.76974241, 0.48648575, 0.01874541],
        [0.49742081, 0.43279741, 0.24369898, 0.65079404, 0.65975956],
        [0.55729839, 0.47819906, 0.16760688, 0.74305168, 0.74508521]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [67]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [68]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [69]:
if a.size == b.size:
    print("a and b have the same size")
else:
    print("a and b don't have the same size")

a and b have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [70]:
np.add(a,b)
#You can not add a and b because they have the same size but a and b shape don't match.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [73]:
c = b.transpose(1,2,0) 
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [74]:
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [78]:
print(a)
print()
print(d)
#elements in d equal to elements in a plus elements in b in the same position.

[[[0.5253161  0.95671782 0.05265301 0.68360436 0.38937611]
  [0.56387532 0.98545682 0.19266634 0.62269885 0.51696664]
  [0.28727947 0.5277015  0.40222221 0.13523375 0.93079469]]

 [[0.46853841 0.02577292 0.76974241 0.48648575 0.01874541]
  [0.49742081 0.43279741 0.24369898 0.65079404 0.65975956]
  [0.55729839 0.47819906 0.16760688 0.74305168 0.74508521]]]

[[[1.5253161  1.95671782 1.05265301 1.68360436 1.38937611]
  [1.56387532 1.98545682 1.19266634 1.62269885 1.51696664]
  [1.28727947 1.5277015  1.40222221 1.13523375 1.93079469]]

 [[1.46853841 1.02577292 1.76974241 1.48648575 1.01874541]
  [1.49742081 1.43279741 1.24369898 1.65079404 1.65975956]
  [1.55729839 1.47819906 1.16760688 1.74305168 1.74508521]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [79]:
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [82]:
print(a)  
print()
print(e)
#both arrays are equal because a integer mulplied by one equals to itself)


[[[0.5253161  0.95671782 0.05265301 0.68360436 0.38937611]
  [0.56387532 0.98545682 0.19266634 0.62269885 0.51696664]
  [0.28727947 0.5277015  0.40222221 0.13523375 0.93079469]]

 [[0.46853841 0.02577292 0.76974241 0.48648575 0.01874541]
  [0.49742081 0.43279741 0.24369898 0.65079404 0.65975956]
  [0.55729839 0.47819906 0.16760688 0.74305168 0.74508521]]]

[[[0.5253161  0.95671782 0.05265301 0.68360436 0.38937611]
  [0.56387532 0.98545682 0.19266634 0.62269885 0.51696664]
  [0.28727947 0.5277015  0.40222221 0.13523375 0.93079469]]

 [[0.46853841 0.02577292 0.76974241 0.48648575 0.01874541]
  [0.49742081 0.43279741 0.24369898 0.65079404 0.65975956]
  [0.55729839 0.47819906 0.16760688 0.74305168 0.74508521]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
d_max = 

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here