# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.99942322 0.46126566 0.65010593 0.85090811 0.01166286]
  [0.747434   0.37511558 0.65916511 0.55771309 0.26323483]
  [0.04349796 0.48934009 0.49833201 0.87730761 0.82431527]]

 [[0.64092765 0.94106537 0.04586001 0.21323748 0.07655222]
  [0.02237927 0.19069312 0.04540317 0.63709007 0.05272065]
  [0.15404102 0.16460781 0.20898313 0.37226871 0.52626127]]]


In [4]:
# Method 2
a2 = np.random.rand(2,3,5)
print(a2)

[[[0.96492557 0.28081493 0.14199121 0.10203027 0.19769356]
  [0.0823291  0.31857575 0.53136207 0.69699933 0.11339237]
  [0.79406973 0.73051519 0.06838742 0.91280442 0.53173554]]

 [[0.92576388 0.17069631 0.42456672 0.46306284 0.19961955]
  [0.91171362 0.00967527 0.51609554 0.28023485 0.61562084]
  [0.47960815 0.12964797 0.47057091 0.06131335 0.22913502]]]


In [5]:
# Method 3
a3 = np.random.randn(2,3,5) 
print(a3)

[[[-1.13199521 -0.09156576  1.11714631  0.15292119 -0.29081403]
  [ 0.20408934 -1.19898933  1.2850783  -0.20577872 -0.18181758]
  [ 1.44932528  2.2157022   0.00538974  1.06612767  0.58732941]]

 [[-1.1498579  -0.24575249  0.29232034 -0.59109473  0.45957135]
  [-1.45401716 -0.26326236 -1.09254973  0.84130017  0.42459922]
  [ 0.526451   -0.13404901  1.3701095  -1.05247868  1.15290075]]]


In [6]:
# Method 4
a4= np.random.randint(0,1000,size=(2,3,5))
print(a4)

[[[906 749 106 104 718]
  [296 846 396 306 263]
  [ 62 126 249 158 271]]

 [[870 660 710 709 473]
  [124  78 250 667 680]
  [230 895  16 791 337]]]


In [30]:
# Method 5
a5= np.empty((2,3,5))
print(a5)

[[[0.99942322 0.46126566 0.65010593 0.85090811 0.01166286]
  [0.747434   0.37511558 0.65916511 0.55771309 0.26323483]
  [0.04349796 0.48934009 0.49833201 0.87730761 0.82431527]]

 [[0.64092765 0.94106537 0.04586001 0.21323748 0.07655222]
  [0.02237927 0.19069312 0.04540317 0.63709007 0.05272065]
  [0.15404102 0.16460781 0.20898313 0.37226871 0.52626127]]]


#### 4. Print *a*.


In [7]:
# your code here
print(a)

[[[0.99942322 0.46126566 0.65010593 0.85090811 0.01166286]
  [0.747434   0.37511558 0.65916511 0.55771309 0.26323483]
  [0.04349796 0.48934009 0.49833201 0.87730761 0.82431527]]

 [[0.64092765 0.94106537 0.04586001 0.21323748 0.07655222]
  [0.02237927 0.19069312 0.04540317 0.63709007 0.05272065]
  [0.15404102 0.16460781 0.20898313 0.37226871 0.52626127]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b= np.ones((5,2,3))

#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
print(a.size==b.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here
np.add(a,b)
#no, I don't because they have different shapes a=(2,3,5) and  b=(5,2,3)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [52]:
# your code here
c=np.reshape(b,(2,3,5))
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(3, 2, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [16]:
# your code/answer here
d=np.add(a,c)
d=a+c
print(d)

#you can add now because 'a' and 'c' have the same shape.


[[[1.99942322 1.46126566 1.65010593 1.85090811 1.01166286]
  [1.747434   1.37511558 1.65916511 1.55771309 1.26323483]
  [1.04349796 1.48934009 1.49833201 1.87730761 1.82431527]]

 [[1.64092765 1.94106537 1.04586001 1.21323748 1.07655222]
  [1.02237927 1.19069312 1.04540317 1.63709007 1.05272065]
  [1.15404102 1.16460781 1.20898313 1.37226871 1.52626127]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [17]:
# your code/answer here
print(a)
print(d)

# 'd' is array 'a' + 1.

[[[0.99942322 0.46126566 0.65010593 0.85090811 0.01166286]
  [0.747434   0.37511558 0.65916511 0.55771309 0.26323483]
  [0.04349796 0.48934009 0.49833201 0.87730761 0.82431527]]

 [[0.64092765 0.94106537 0.04586001 0.21323748 0.07655222]
  [0.02237927 0.19069312 0.04540317 0.63709007 0.05272065]
  [0.15404102 0.16460781 0.20898313 0.37226871 0.52626127]]]
[[[1.99942322 1.46126566 1.65010593 1.85090811 1.01166286]
  [1.747434   1.37511558 1.65916511 1.55771309 1.26323483]
  [1.04349796 1.48934009 1.49833201 1.87730761 1.82431527]]

 [[1.64092765 1.94106537 1.04586001 1.21323748 1.07655222]
  [1.02237927 1.19069312 1.04540317 1.63709007 1.05272065]
  [1.15404102 1.16460781 1.20898313 1.37226871 1.52626127]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
# your code here
e= a*c
e=np.multiply(a,c)
print(e)

[[[0.99942322 0.46126566 0.65010593 0.85090811 0.01166286]
  [0.747434   0.37511558 0.65916511 0.55771309 0.26323483]
  [0.04349796 0.48934009 0.49833201 0.87730761 0.82431527]]

 [[0.64092765 0.94106537 0.04586001 0.21323748 0.07655222]
  [0.02237927 0.19069312 0.04540317 0.63709007 0.05272065]
  [0.15404102 0.16460781 0.20898313 0.37226871 0.52626127]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [20]:
# your code/answer here
print(e==a)

# 'e' is equal to 'a' because 'e' is the multiplication of 'a' and 'c' and all the values in 'c' are 1.

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [21]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max)
print(d_min)
print(d_mean)


1.99942321976588
1.0116628595208246
1.4200304093900067


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [29]:
# your code here
f= np.empty((2,3,5))
print(f)

[[[0.99942322 0.46126566 0.65010593 0.85090811 0.01166286]
  [0.747434   0.37511558 0.65916511 0.55771309 0.26323483]
  [0.04349796 0.48934009 0.49833201 0.87730761 0.82431527]]

 [[0.64092765 0.94106537 0.04586001 0.21323748 0.07655222]
  [0.02237927 0.19069312 0.04540317 0.63709007 0.05272065]
  [0.15404102 0.16460781 0.20898313 0.37226871 0.52626127]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [47]:
# your code here
f=[]
for x in d:
    for y in x:
        for z in y:
            if z==d_min:
                f.append(0)
            elif d_min<z<d_mean:
                f.append(25)
            elif z==d_mean:
                f.append(50)
            elif d_mean<z<d_max:
                f.append(75)
            else:
                f.append(100)

f=np.reshape(f,(2,3,5))                
           


[[[100  75  75  75   0]
  [ 75  25  75  75  25]
  [ 25  75  75  75  75]]

 [[ 75  75  25  25  25]
  [ 25  25  25  75  25]
  [ 25  25  25  25  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [48]:
# your code here
print(d)
print(f)

[[[1.99942322 1.46126566 1.65010593 1.85090811 1.01166286]
  [1.747434   1.37511558 1.65916511 1.55771309 1.26323483]
  [1.04349796 1.48934009 1.49833201 1.87730761 1.82431527]]

 [[1.64092765 1.94106537 1.04586001 1.21323748 1.07655222]
  [1.02237927 1.19069312 1.04540317 1.63709007 1.05272065]
  [1.15404102 1.16460781 1.20898313 1.37226871 1.52626127]]]
[[[100  75  75  75   0]
  [ 75  25  75  75  25]
  [ 25  75  75  75  75]]

 [[ 75  75  25  25  25]
  [ 25  25  25  75  25]
  [ 25  25  25  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [50]:
# your code here
f=[]
for x in d:
    for y in x:
        for z in y:
            if z==d_min:
                f.append('A')
            elif d_min<z<d_mean:
                f.append('B')
            elif z==d_mean:
                f.append('C')
            elif d_mean<z<d_max:
                f.append('D')
            else:
                f.append('E')

f=np.reshape(f,(2,3,5)) 
print(f)

[[['E' 'D' 'D' 'D' 'A']
  ['D' 'B' 'D' 'D' 'B']
  ['B' 'D' 'D' 'D' 'D']]

 [['D' 'D' 'B' 'B' 'B']
  ['B' 'B' 'B' 'D' 'B']
  ['B' 'B' 'B' 'B' 'D']]]
