# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [4]:
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [15]:
# Method 1
a = np.random.random((2,3,5))

#Comprobamos la estructura de la matriz con el método .shape
#a.shape

In [63]:
# Method 2
a = np.random.rand(2,3,5)


In [35]:
# Method 3
#a = np.random.normal(size=(2,3,5))
#Este método no parece que devuelva un resultado parecido, ¿qué estoy haciendo mal?


#### 4. Print *a*.


In [64]:
a

array([[[0.29413705, 0.71960884, 0.72913107, 0.86209087, 0.47891553],
        [0.55189821, 0.76651849, 0.33997305, 0.15177338, 0.79895407],
        [0.12056962, 0.08336407, 0.70900291, 0.03445751, 0.59303628]],

       [[0.43347175, 0.01168263, 0.15146898, 0.35898961, 0.49516633],
        [0.45249408, 0.60302138, 0.88575471, 0.27371052, 0.8234949 ],
        [0.37246558, 0.61326549, 0.81941045, 0.16433232, 0.82983135]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [65]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [66]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [67]:
a
x = a.size

b
y = b.size

if x==y:
    print("Yes, both have the same size")
else:
    print("Nope")

#No sabía si utilizar el método shape, pero entiendo que nos pedís el "total de los elementos", no la estructura.

Yes, both have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [68]:
c = a + b

c

#In order to concatenate two arrays they need to have the same shape or find the overlapping range 
#and add the arrays using slicing

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [69]:
c = b.transpose(1,2,0)

print(c)
print(c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [70]:
d = a + c

d

#Because both arrays now have the same size

array([[[1.29413705, 1.71960884, 1.72913107, 1.86209087, 1.47891553],
        [1.55189821, 1.76651849, 1.33997305, 1.15177338, 1.79895407],
        [1.12056962, 1.08336407, 1.70900291, 1.03445751, 1.59303628]],

       [[1.43347175, 1.01168263, 1.15146898, 1.35898961, 1.49516633],
        [1.45249408, 1.60302138, 1.88575471, 1.27371052, 1.8234949 ],
        [1.37246558, 1.61326549, 1.81941045, 1.16433232, 1.82983135]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [71]:
print(a)
print("break")
print(d)

#Since the c array is composed by a random matrix of ones, when adding a + c, the returning array will have a difference
#of 1 in all elements

[[[0.29413705 0.71960884 0.72913107 0.86209087 0.47891553]
  [0.55189821 0.76651849 0.33997305 0.15177338 0.79895407]
  [0.12056962 0.08336407 0.70900291 0.03445751 0.59303628]]

 [[0.43347175 0.01168263 0.15146898 0.35898961 0.49516633]
  [0.45249408 0.60302138 0.88575471 0.27371052 0.8234949 ]
  [0.37246558 0.61326549 0.81941045 0.16433232 0.82983135]]]
break
[[[1.29413705 1.71960884 1.72913107 1.86209087 1.47891553]
  [1.55189821 1.76651849 1.33997305 1.15177338 1.79895407]
  [1.12056962 1.08336407 1.70900291 1.03445751 1.59303628]]

 [[1.43347175 1.01168263 1.15146898 1.35898961 1.49516633]
  [1.45249408 1.60302138 1.88575471 1.27371052 1.8234949 ]
  [1.37246558 1.61326549 1.81941045 1.16433232 1.82983135]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [72]:
e = a * c

e

array([[[0.29413705, 0.71960884, 0.72913107, 0.86209087, 0.47891553],
        [0.55189821, 0.76651849, 0.33997305, 0.15177338, 0.79895407],
        [0.12056962, 0.08336407, 0.70900291, 0.03445751, 0.59303628]],

       [[0.43347175, 0.01168263, 0.15146898, 0.35898961, 0.49516633],
        [0.45249408, 0.60302138, 0.88575471, 0.27371052, 0.8234949 ],
        [0.37246558, 0.61326549, 0.81941045, 0.16433232, 0.82983135]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [73]:
print(a)
print("line break")
print(e)

#Yes, they are the same because we are multiplying by 1 all elements, so they all remain the same

[[[0.29413705 0.71960884 0.72913107 0.86209087 0.47891553]
  [0.55189821 0.76651849 0.33997305 0.15177338 0.79895407]
  [0.12056962 0.08336407 0.70900291 0.03445751 0.59303628]]

 [[0.43347175 0.01168263 0.15146898 0.35898961 0.49516633]
  [0.45249408 0.60302138 0.88575471 0.27371052 0.8234949 ]
  [0.37246558 0.61326549 0.81941045 0.16433232 0.82983135]]]
line break
[[[0.29413705 0.71960884 0.72913107 0.86209087 0.47891553]
  [0.55189821 0.76651849 0.33997305 0.15177338 0.79895407]
  [0.12056962 0.08336407 0.70900291 0.03445751 0.59303628]]

 [[0.43347175 0.01168263 0.15146898 0.35898961 0.49516633]
  [0.45249408 0.60302138 0.88575471 0.27371052 0.8234949 ]
  [0.37246558 0.61326549 0.81941045 0.16433232 0.82983135]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [74]:
d_max = np.max(d)
print(d_max)

d_min = np.min(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)

1.8857547091622127
1.0116826302552164
1.4840663672201493


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [75]:
f = np.empty(shape=(2,3,5))
f

array([[[0.29413705, 0.71960884, 0.72913107, 0.86209087, 0.47891553],
        [0.55189821, 0.76651849, 0.33997305, 0.15177338, 0.79895407],
        [0.12056962, 0.08336407, 0.70900291, 0.03445751, 0.59303628]],

       [[0.43347175, 0.01168263, 0.15146898, 0.35898961, 0.49516633],
        [0.45249408, 0.60302138, 0.88575471, 0.27371052, 0.8234949 ],
        [0.37246558, 0.61326549, 0.81941045, 0.16433232, 0.82983135]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [84]:
print(d)
print("line")

for cell in np.nditer(d):
    if cell > d_min and cell < d_mean:
        cell = 25
    elif cell > d_mean and cell < d_max:
        cell = 75
    elif cell == d_mean:
        cell = 50
    elif cell < d_min:
        cell = 0
    elif cell > d_max:
        cell = 100
new_array = np.asarray(cell)        

f = np.append(new_array, [2,3,5])
f

[[[1.29413705 1.71960884 1.72913107 1.86209087 1.47891553]
  [1.55189821 1.76651849 1.33997305 1.15177338 1.79895407]
  [1.12056962 1.08336407 1.70900291 1.03445751 1.59303628]]

 [[1.43347175 1.01168263 1.15146898 1.35898961 1.49516633]
  [1.45249408 1.60302138 1.88575471 1.27371052 1.8234949 ]
  [1.37246558 1.61326549 1.81941045 1.16433232 1.82983135]]]
line


array([75,  2,  3,  5])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here