# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random((2,3,5))
a

array([[[0.08153739, 0.46174957, 0.98359418, 0.49065927, 0.31952029],
        [0.0778072 , 0.22875488, 0.81958107, 0.30702949, 0.73246752],
        [0.32833995, 0.29715146, 0.79218073, 0.4287299 , 0.27002944]],

       [[0.14294799, 0.09610683, 0.59734441, 0.10486058, 0.21121826],
        [0.2891684 , 0.65491055, 0.94213305, 0.82066521, 0.15757585],
        [0.45624002, 0.27966377, 0.64047671, 0.99818459, 0.19691534]]])

In [4]:
# Method 2

np.random.rand[(2,3,5)]


TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
# Method 3

#### 4. Print *a*.


In [5]:
# your code here
print(a)

[[[0.08153739 0.46174957 0.98359418 0.49065927 0.31952029]
  [0.0778072  0.22875488 0.81958107 0.30702949 0.73246752]
  [0.32833995 0.29715146 0.79218073 0.4287299  0.27002944]]

 [[0.14294799 0.09610683 0.59734441 0.10486058 0.21121826]
  [0.2891684  0.65491055 0.94213305 0.82066521 0.15757585]
  [0.45624002 0.27966377 0.64047671 0.99818459 0.19691534]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [6]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [7]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [8]:
# your code here
a.size == b.size

#else i could print print(a.size) and (b.size)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [9]:
# your answer here
np.add(a,b)

# the shape of both arrays is different, hence some of the items in the array wont have a match in the other array

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [10]:
# your code here

c = b.transpose(1,2,0)
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [11]:
# your code/answer here
d = a+c
d

#It does work because now both shapes match. they do have same dimensions, axis and columns after the transpose of B

array([[[1.08153739, 1.46174957, 1.98359418, 1.49065927, 1.31952029],
        [1.0778072 , 1.22875488, 1.81958107, 1.30702949, 1.73246752],
        [1.32833995, 1.29715146, 1.79218073, 1.4287299 , 1.27002944]],

       [[1.14294799, 1.09610683, 1.59734441, 1.10486058, 1.21121826],
        [1.2891684 , 1.65491055, 1.94213305, 1.82066521, 1.15757585],
        [1.45624002, 1.27966377, 1.64047671, 1.99818459, 1.19691534]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [12]:
# your code/answer here

print(d)
print(a)

#The difference is that "d" is coming from "c" that at the same time is the transpose of a random array of random "ones" in a sum from "b". Hence, the main difference is that "a" is an array with 0 to 1 values, while "d" would be 1 to 2 values

[[[1.08153739 1.46174957 1.98359418 1.49065927 1.31952029]
  [1.0778072  1.22875488 1.81958107 1.30702949 1.73246752]
  [1.32833995 1.29715146 1.79218073 1.4287299  1.27002944]]

 [[1.14294799 1.09610683 1.59734441 1.10486058 1.21121826]
  [1.2891684  1.65491055 1.94213305 1.82066521 1.15757585]
  [1.45624002 1.27966377 1.64047671 1.99818459 1.19691534]]]
[[[0.08153739 0.46174957 0.98359418 0.49065927 0.31952029]
  [0.0778072  0.22875488 0.81958107 0.30702949 0.73246752]
  [0.32833995 0.29715146 0.79218073 0.4287299  0.27002944]]

 [[0.14294799 0.09610683 0.59734441 0.10486058 0.21121826]
  [0.2891684  0.65491055 0.94213305 0.82066521 0.15757585]
  [0.45624002 0.27966377 0.64047671 0.99818459 0.19691534]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [13]:
# your code here
e = a*c
e


array([[[0.08153739, 0.46174957, 0.98359418, 0.49065927, 0.31952029],
        [0.0778072 , 0.22875488, 0.81958107, 0.30702949, 0.73246752],
        [0.32833995, 0.29715146, 0.79218073, 0.4287299 , 0.27002944]],

       [[0.14294799, 0.09610683, 0.59734441, 0.10486058, 0.21121826],
        [0.2891684 , 0.65491055, 0.94213305, 0.82066521, 0.15757585],
        [0.45624002, 0.27966377, 0.64047671, 0.99818459, 0.19691534]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [14]:
# your code/answer here

e == a

#Yes it would be the same because the multiplier is 1, and a value multiplied by 1 will always be the same number. 


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [15]:
# your code here

d_max = d.max()
d_min = d.min()
d_mean = d.mean()


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f = np.empty([2, 3, 5])

# I wasn't able to finish it, but i believe this was the way

for x in d:
    for y in x:
        for z in y:
            if z > d_min:
                print(0)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here



#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here