# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [26]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [27]:
# your code here
print(np.__version__)

1.10.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [28]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[ 0.9644304   0.92929526  0.65199156  0.54890918  0.96837022]
  [ 0.92721871  0.63580993  0.94061508  0.08031249  0.64105141]
  [ 0.48821906  0.59813415  0.74758236  0.24998835  0.07714382]]

 [[ 0.4623921   0.04856094  0.73499811  0.55232756  0.90478901]
  [ 0.10884319  0.19027477  0.92679581  0.76857202  0.94167813]
  [ 0.683181    0.80843337  0.71780363  0.06769583  0.13903856]]]


In [29]:
# Method 2
#x = np.random.rand()
#print(x)

a=np.array([[[np.random.rand() for i in range(5)] for j in range(3)] for k in range(2)])

print(a)

[[[ 0.52724903  0.86212332  0.94275601  0.66277943  0.68261977]
  [ 0.84919644  0.41064895  0.15513988  0.89116084  0.27065725]
  [ 0.09355822  0.71028337  0.52185007  0.92787472  0.705602  ]]

 [[ 0.92934147  0.86655128  0.80733364  0.29840773  0.80722022]
  [ 0.52698067  0.59595451  0.81425242  0.64637023  0.77938047]
  [ 0.78033999  0.88333439  0.9556738   0.67554957  0.35798004]]]


In [30]:
# Method 3

a= np.ones((2,3,5))
for i in range(2):
    for j in range(3):
        for k in range(5): 
            x=np.random.rand()
            a[i][j][k] = a[i][j][k]*x
                             
print(a)

[[[ 0.56739121  0.29403295  0.54607758  0.23603158  0.76343207]
  [ 0.13693541  0.67865012  0.61191929  0.14919127  0.84679253]
  [ 0.46448138  0.59447693  0.92626767  0.84257397  0.50750837]]

 [[ 0.23070866  0.72131413  0.07334796  0.00581471  0.84465431]
  [ 0.34906584  0.70520672  0.04436775  0.0357105   0.0724948 ]
  [ 0.36338878  0.748627    0.99431613  0.24566219  0.83370887]]]


#### 4. Print *a*.


In [31]:
# your code here
print(a)

[[[ 0.56739121  0.29403295  0.54607758  0.23603158  0.76343207]
  [ 0.13693541  0.67865012  0.61191929  0.14919127  0.84679253]
  [ 0.46448138  0.59447693  0.92626767  0.84257397  0.50750837]]

 [[ 0.23070866  0.72131413  0.07334796  0.00581471  0.84465431]
  [ 0.34906584  0.70520672  0.04436775  0.0357105   0.0724948 ]
  [ 0.36338878  0.748627    0.99431613  0.24566219  0.83370887]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [32]:
# your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [33]:
# your code here
print(b)

[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [34]:
# your code here
print(a.size)
print(b.size)
print(a.size == b.size) # Both have the same size.

30
30
True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [37]:
# your answer here
print(a.shape)
print(b.shape)
print(a.shape == b.shape)

# Is not posible because the arrays not fit in the shape . 

(2, 3, 5)
(5, 2, 3)
False


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [53]:
# your code here

c=np.array([b[i].T for i in range(5)]).T


print(b.shape)
print(c.shape)


(5, 2, 3)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [54]:
# your code/answer here
d= a + c
print(d) # The sum is posibel because the shape of both arrays is the same


[[[ 1.56739121  1.29403295  1.54607758  1.23603158  1.76343207]
  [ 1.13693541  1.67865012  1.61191929  1.14919127  1.84679253]
  [ 1.46448138  1.59447693  1.92626767  1.84257397  1.50750837]]

 [[ 1.23070866  1.72131413  1.07334796  1.00581471  1.84465431]
  [ 1.34906584  1.70520672  1.04436775  1.0357105   1.0724948 ]
  [ 1.36338878  1.748627    1.99431613  1.24566219  1.83370887]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [55]:
# your code/answer here
print(a)
print(d)

# The items values in d-array are biggers than a-array. This is because np.random offer values bettewen 0 and 1,
#if we remenber d-array is the result of the random values of a-array plus b-array tranpose, array in wich all items are 1.    

[[[ 0.56739121  0.29403295  0.54607758  0.23603158  0.76343207]
  [ 0.13693541  0.67865012  0.61191929  0.14919127  0.84679253]
  [ 0.46448138  0.59447693  0.92626767  0.84257397  0.50750837]]

 [[ 0.23070866  0.72131413  0.07334796  0.00581471  0.84465431]
  [ 0.34906584  0.70520672  0.04436775  0.0357105   0.0724948 ]
  [ 0.36338878  0.748627    0.99431613  0.24566219  0.83370887]]]
[[[ 1.56739121  1.29403295  1.54607758  1.23603158  1.76343207]
  [ 1.13693541  1.67865012  1.61191929  1.14919127  1.84679253]
  [ 1.46448138  1.59447693  1.92626767  1.84257397  1.50750837]]

 [[ 1.23070866  1.72131413  1.07334796  1.00581471  1.84465431]
  [ 1.34906584  1.70520672  1.04436775  1.0357105   1.0724948 ]
  [ 1.36338878  1.748627    1.99431613  1.24566219  1.83370887]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [56]:
# your code here
e=a*c
print(e)

[[[ 0.56739121  0.29403295  0.54607758  0.23603158  0.76343207]
  [ 0.13693541  0.67865012  0.61191929  0.14919127  0.84679253]
  [ 0.46448138  0.59447693  0.92626767  0.84257397  0.50750837]]

 [[ 0.23070866  0.72131413  0.07334796  0.00581471  0.84465431]
  [ 0.34906584  0.70520672  0.04436775  0.0357105   0.0724948 ]
  [ 0.36338878  0.748627    0.99431613  0.24566219  0.83370887]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [57]:
# your code/answer here
print(a == e) # e and a are equal because c-array only have 1, multiplication by 1 is the same number.

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [67]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean=np.mean(d)
print("The maximun value of d:",d_max)
print("The minimun value of d:",d_min)
print("The mean value of d:",d_mean)


The maximun value of d: 1.9943161303
The minimun value of d: 1.00581471135
The mean value of d: 1.48113835578


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [79]:
# your code here
f=np.empty([2,3,5])
print(f)


[[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [84]:
# your code here


for i in range(2):
    for j in range(3):
        for k in range(5): 
            if (d_mean > d[i,j,k] > d_min):
                f[i,j,k] = 25
            elif (d_max > d[i,j,k] > d_mean):
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                 f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                 f[i,j,k] = 100
                    
                   

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [85]:
# your code here
print(d) 
print(f) 

[[[ 1.56739121  1.29403295  1.54607758  1.23603158  1.76343207]
  [ 1.13693541  1.67865012  1.61191929  1.14919127  1.84679253]
  [ 1.46448138  1.59447693  1.92626767  1.84257397  1.50750837]]

 [[ 1.23070866  1.72131413  1.07334796  1.00581471  1.84465431]
  [ 1.34906584  1.70520672  1.04436775  1.0357105   1.0724948 ]
  [ 1.36338878  1.748627    1.99431613  1.24566219  1.83370887]]]
[[[  75.   25.   75.   25.   75.]
  [  25.   75.   75.   25.   75.]
  [  25.   75.   75.   75.   75.]]

 [[  25.   75.   25.    0.   75.]
  [  25.   75.   25.   25.   25.]
  [  25.   75.  100.   25.   75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [92]:
# your code here

f_list=list(f)

for i in range(2):
    f_list[i]=list(f_list[i])
    for j in range(3):
        f_list[i][j]=list(f_list[i][j])
       

for i in range(2):
    for j in range(3):
        for k in range(5): 
            if (d_mean > d[i,j,k] > d_min):
                f_list[i][j][k] = "B"
            elif (d_max > d[i,j,k] > d_mean):
                f_list[i][j][k] = "D"
            elif d[i,j,k] == d_mean:
                f_list[i][j][k] = "C"
            elif d[i,j,k] == d_min:
                 f_list[i][j][k] = "A"
            elif d[i,j,k] == d_max:
                 f_list[i][j][k] = "E"
print(d)
print(np.array(f_list))

[[[ 1.56739121  1.29403295  1.54607758  1.23603158  1.76343207]
  [ 1.13693541  1.67865012  1.61191929  1.14919127  1.84679253]
  [ 1.46448138  1.59447693  1.92626767  1.84257397  1.50750837]]

 [[ 1.23070866  1.72131413  1.07334796  1.00581471  1.84465431]
  [ 1.34906584  1.70520672  1.04436775  1.0357105   1.0724948 ]
  [ 1.36338878  1.748627    1.99431613  1.24566219  1.83370887]]]
[[['D' 'B' 'D' 'B' 'D']
  ['B' 'D' 'D' 'B' 'D']
  ['B' 'D' 'D' 'D' 'D']]

 [['B' 'D' 'B' 'A' 'D']
  ['B' 'D' 'B' 'B' 'B']
  ['B' 'D' 'E' 'B' 'D']]]
