# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))

In [4]:
# Method 2
a= np.random.randint(2,3,5)

In [5]:
# Method 3
a = np.random.rand(2,3,5)

#### 4. Print *a*.


In [6]:
# your code here
a

array([[[0.77079405, 0.75564644, 0.84675218, 0.79319966, 0.09049997],
        [0.25813771, 0.75784039, 0.16083371, 0.03268156, 0.32359093],
        [0.74219668, 0.24985395, 0.66169655, 0.96281043, 0.81007308]],

       [[0.84254202, 0.3417983 , 0.12520466, 0.23479864, 0.69258043],
        [0.78999209, 0.20197241, 0.63006122, 0.14712673, 0.84125947],
        [0.28008397, 0.03654858, 0.47181213, 0.97042068, 0.69384366]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
# I can prove if a and b have the same size with an if statement
if a.size == b.size:
    print(True)
else:
    print(False)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
a + b
# You can not add a and b because they have a different shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
print(b.shape)
c = b.transpose((1, 2, 0))
print(c.shape)
print(a.shape)

(5, 2, 3)
(2, 3, 5)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = a + c
# Now it works because the shape of a and c is the same

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)

print()

print(d)

print()
print(f'The difference between a and d is that in d we have add the unit in every term of a')

[[[0.77079405 0.75564644 0.84675218 0.79319966 0.09049997]
  [0.25813771 0.75784039 0.16083371 0.03268156 0.32359093]
  [0.74219668 0.24985395 0.66169655 0.96281043 0.81007308]]

 [[0.84254202 0.3417983  0.12520466 0.23479864 0.69258043]
  [0.78999209 0.20197241 0.63006122 0.14712673 0.84125947]
  [0.28008397 0.03654858 0.47181213 0.97042068 0.69384366]]]

[[[1.77079405 1.75564644 1.84675218 1.79319966 1.09049997]
  [1.25813771 1.75784039 1.16083371 1.03268156 1.32359093]
  [1.74219668 1.24985395 1.66169655 1.96281043 1.81007308]]

 [[1.84254202 1.3417983  1.12520466 1.23479864 1.69258043]
  [1.78999209 1.20197241 1.63006122 1.14712673 1.84125947]
  [1.28008397 1.03654858 1.47181213 1.97042068 1.69384366]]]

The difference between a and d is that in d we have add the unit in every term of a


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
if e.all() == a.all():
    print(True)
else:
    print(False)
    
print()

print('a and e are the same because in order to obtain e we have multiply a by a matrix of ones')

True

a and e are the same because in order to obtain e we have multiply a by a matrix of ones


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(f'The maximum value of d is {d_max}, the minimum value is {d_min} and the mean is {d_mean}')

The maximum value of d is 1.9704206752962476, the minimum value is 1.0326815605150867 and the mean is 1.5172217427295267


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))
f

array([[[1.77079405, 1.75564644, 1.84675218, 1.79319966, 1.09049997],
        [1.25813771, 1.75784039, 1.16083371, 1.03268156, 1.32359093],
        [1.74219668, 1.24985395, 1.66169655, 1.96281043, 1.81007308]],

       [[1.84254202, 1.3417983 , 1.12520466, 1.23479864, 1.69258043],
        [1.78999209, 1.20197241, 1.63006122, 1.14712673, 1.84125947],
        [1.28008397, 1.03654858, 1.47181213, 1.97042068, 1.69384366]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100 

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
#your code here
print(d)

print()

print(f)

[[[1.77079405 1.75564644 1.84675218 1.79319966 1.09049997]
  [1.25813771 1.75784039 1.16083371 1.03268156 1.32359093]
  [1.74219668 1.24985395 1.66169655 1.96281043 1.81007308]]

 [[1.84254202 1.3417983  1.12520466 1.23479864 1.69258043]
  [1.78999209 1.20197241 1.63006122 1.14712673 1.84125947]
  [1.28008397 1.03654858 1.47181213 1.97042068 1.69384366]]]

[[[ 75.  75.  75.  75.  25.]
  [ 25.  75.  25.   0.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 75.  25.  25.  25.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  25.  25. 100.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
f = f.tolist()
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i][j][k] = 'B'
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i][j][k] = 'D'
            elif d[i,j,k] == d_mean:
                f[i][j][k] = 'C'
            elif d[i,j,k] == d_min:
                f[i][j][k] = 'A'
            elif d[i,j,k] == d_max:
                f[i][j][k] = 'E' 
            

print(f)

[[['D', 'D', 'D', 'D', 'B'], ['B', 'D', 'B', 'A', 'B'], ['D', 'B', 'D', 'D', 'D']], [['D', 'B', 'B', 'B', 'D'], ['D', 'B', 'D', 'B', 'D'], ['B', 'B', 'B', 'E', 'D']]]
