# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
a = np.random.random((2, 3, 5))
print(a)

[[[0.15585079 0.27721706 0.64797007 0.71398536 0.28965147]
  [0.47280794 0.14983879 0.18819348 0.15728517 0.16363326]
  [0.16694944 0.53211392 0.84262562 0.65362804 0.85822867]]

 [[0.57451852 0.48550201 0.74680289 0.42415147 0.23276563]
  [0.21712741 0.64945176 0.75878371 0.2616375  0.68254793]
  [0.73350096 0.34538102 0.37676132 0.33296756 0.01617401]]]


In [30]:
# Method 2
a2 = np.random.sample((2, 3, 5))
print(b)

[[[0.15481707 0.7394096  0.08794748 0.72426132 0.42580051]
  [0.82992651 0.5558669  0.62083258 0.79115624 0.22583854]
  [0.48555025 0.92604711 0.10213789 0.19994796 0.48673008]]

 [[0.23589521 0.94165341 0.55901215 0.28716803 0.05456964]
  [0.66932408 0.65807106 0.22657997 0.75365846 0.03390141]
  [0.26838675 0.36506817 0.85357924 0.85086516 0.21649218]]]


In [31]:
# Method 3
a3 = np.random.rand(2, 3, 5)
print(c)

[[[0.72939527 0.8918644  0.59695774 0.79208606 0.85579478]
  [0.69959184 0.79949398 0.28068786 0.43843773 0.90785403]
  [0.41277727 0.96146607 0.23627607 0.86581087 0.99767248]]

 [[0.82457759 0.24736875 0.91762963 0.26129332 0.08179539]
  [0.42503409 0.64279285 0.3159151  0.26221932 0.56150464]
  [0.98213885 0.83192353 0.42041974 0.63408609 0.67268869]]]


#### 4. Print *a*.


In [32]:
# your code here
print(a)

[[[32.31884113 78.60336706 69.19725332 85.87815929 44.08012557]
  [12.9696993  26.60823444  8.94037366 93.0478331  94.92332486]
  [28.17307679 37.34114852 61.02556262 16.09599271  8.16393781]]

 [[66.76268724 15.15080387 97.61674454 30.066971   99.72728869]
  [22.26407792 70.27040754 36.49116447 59.49894369 23.61283409]
  [97.99333395 39.39659916 79.56983137 53.05966535 26.30382693]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [40]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [41]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [46]:
# your code here
size_a = a.size
size_b = b.size
size_a = size_b

#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [54]:
# your code here
#5x2x3
c = b.transpose(1, 2, 0)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [56]:
# your code/answer here
d = np.add(a,c)
print(d)

[[[ 33.31884113  79.60336706  70.19725332  86.87815929  45.08012557]
  [ 13.9696993   27.60823444   9.94037366  94.0478331   95.92332486]
  [ 29.17307679  38.34114852  62.02556262  17.09599271   9.16393781]]

 [[ 67.76268724  16.15080387  98.61674454  31.066971   100.72728869]
  [ 23.26407792  71.27040754  37.49116447  60.49894369  24.61283409]
  [ 98.99333395  40.39659916  80.56983137  54.05966535  27.30382693]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [58]:
# your code/answer here
print(a)
print()
print(d)
#d = 

[[[32.31884113 78.60336706 69.19725332 85.87815929 44.08012557]
  [12.9696993  26.60823444  8.94037366 93.0478331  94.92332486]
  [28.17307679 37.34114852 61.02556262 16.09599271  8.16393781]]

 [[66.76268724 15.15080387 97.61674454 30.066971   99.72728869]
  [22.26407792 70.27040754 36.49116447 59.49894369 23.61283409]
  [97.99333395 39.39659916 79.56983137 53.05966535 26.30382693]]]

[[[ 33.31884113  79.60336706  70.19725332  86.87815929  45.08012557]
  [ 13.9696993   27.60823444   9.94037366  94.0478331   95.92332486]
  [ 29.17307679  38.34114852  62.02556262  17.09599271   9.16393781]]

 [[ 67.76268724  16.15080387  98.61674454  31.066971   100.72728869]
  [ 23.26407792  71.27040754  37.49116447  60.49894369  24.61283409]
  [ 98.99333395  40.39659916  80.56983137  54.05966535  27.30382693]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
# your code here
e = 

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here