# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [5]:
# your code here
print((np.__version__))                        # we use atribute __version__


1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
# Method 1
a1 = np.random.random((2,3,5))        # The easiest way for random numbers between 0 and 1 in an array
print(a1)

[[[0.26153456 0.40253041 0.4194276  0.47997848 0.38253765]
  [0.1368703  0.81813101 0.15690463 0.9646997  0.08085413]
  [0.03380308 0.29103219 0.37509703 0.03477868 0.44754431]]

 [[0.81953422 0.099306   0.06493103 0.32564229 0.18424231]
  [0.94256296 0.39035416 0.54748145 0.2956745  0.53511135]
  [0.75007081 0.08651783 0.94645081 0.82777823 0.78139971]]]


In [7]:
# Method 2

a2 = np.random.randint(0,10,(2,3,5))        # This is a random with integers numbers in array between 0 and 9
print(a2)

[[[1 1 2 1 1]
  [1 8 7 1 6]
  [4 5 2 6 9]]

 [[2 1 0 0 8]
  [5 5 6 7 3]
  [7 2 5 0 4]]]


In [8]:
# Method 3
a3=np.random.randn(2,3,5)                           # random with real numbers
print(a3)

[[[ 0.69642395  0.64002964 -0.64893574 -0.13926308 -0.86272669]
  [ 1.43795194  1.84047012 -0.64187212 -1.54591361  1.38022171]
  [ 1.7485917   0.67323267 -0.38824809  0.45727955  0.06729568]]

 [[ 0.97640954  0.0810441   0.73470941 -1.53398936  0.14136018]
  [-0.02294689 -1.97146793 -0.66476361 -0.14711032  0.06127221]
  [-0.35035096  0.42789212 -0.01760926  0.31430052  0.72084375]]]


In [9]:
# Method 4
a4=(10-1)*np.random.rand(2,3,5) + 1   ## This are a random array between 1 and 10
print(a4)

[[[5.46433387 5.61189379 7.6317567  2.3255175  4.8343378 ]
  [2.25849395 6.95542494 5.01449228 7.85248931 9.86534206]
  [4.81303583 6.07373213 7.24034592 4.30585781 5.18697109]]

 [[9.99236731 4.48985764 7.34484956 8.54644921 2.07501373]
  [4.32232107 3.72626684 8.9042208  3.32926242 7.08629781]
  [4.53737252 6.95818926 2.70872321 1.03371359 1.84380887]]]


In [10]:
# Method 5                    # From a list of 30 random numbers
a5=np.reshape([np.random.choice(x) for x in np.random.random((30,1))],(2,3,5))
print(a5)

[[[0.14778435 0.75081733 0.84243748 0.8003459  0.5863914 ]
  [0.10967169 0.55697696 0.33297973 0.48816214 0.94354375]
  [0.43972867 0.00449299 0.27878655 0.31017114 0.97398274]]

 [[0.02710864 0.53328508 0.1881613  0.45342863 0.08879724]
  [0.45814043 0.57881275 0.63732552 0.4628058  0.72517053]
  [0.95378471 0.03344735 0.93880582 0.51930381 0.94200404]]]


#### 4. Print *a*.


In [11]:
# your code here
a=np.random.random((2,3,5))
print(a)

[[[0.31691227 0.6020775  0.65936819 0.87368338 0.51035804]
  [0.0903947  0.60862679 0.175014   0.33070284 0.58801598]
  [0.41892626 0.6480461  0.6517817  0.87258078 0.44670598]]

 [[0.49601464 0.35481241 0.4029047  0.11112621 0.08644512]
  [0.63870538 0.69713469 0.68452803 0.20691036 0.31527184]
  [0.52317873 0.49222384 0.47491489 0.42273781 0.05692027]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
# your code here
b=np.ones((5,2,3))


#### 6. Print *b*.


In [13]:
# your code here
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [22]:
# your code here
size_a=a.size
size_b=b.size
print(f'Is the size of a ({size_a}) the same of size b ({size_b}) ? => ', size_a==size_b)

Is the size of a (30) the same of size b (30) ? =>  True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [23]:
# your answer here
a+b
# It is not possible to add a+b because the dimensions of both arrays are different (2,3,5) and (5,3,2)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [33]:
# your code here
c=b.T                     # If you transpose array b, you get an array with shape (3,2,5)
print(c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [36]:
# your code/answer here
a+c    # This sum also doesn't work because the shape are different (2,3,5) and (3,2,5)
c=np.reshape(b,(2,3,5)) # To get an array with same shape of a array we can do a reshape of b.
print(c)
d=a+c    # This sum now works because both arrays have the same shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [37]:
# your code/answer here
print(a)
print(d) # Each element of d is the correspond element of a plus 1.

[[[0.31691227 0.6020775  0.65936819 0.87368338 0.51035804]
  [0.0903947  0.60862679 0.175014   0.33070284 0.58801598]
  [0.41892626 0.6480461  0.6517817  0.87258078 0.44670598]]

 [[0.49601464 0.35481241 0.4029047  0.11112621 0.08644512]
  [0.63870538 0.69713469 0.68452803 0.20691036 0.31527184]
  [0.52317873 0.49222384 0.47491489 0.42273781 0.05692027]]]
[[[1.31691227 1.6020775  1.65936819 1.87368338 1.51035804]
  [1.0903947  1.60862679 1.175014   1.33070284 1.58801598]
  [1.41892626 1.6480461  1.6517817  1.87258078 1.44670598]]

 [[1.49601464 1.35481241 1.4029047  1.11112621 1.08644512]
  [1.63870538 1.69713469 1.68452803 1.20691036 1.31527184]
  [1.52317873 1.49222384 1.47491489 1.42273781 1.05692027]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [47]:
# your code here
e=a*c
e

array([[[0.31691227, 0.6020775 , 0.65936819, 0.87368338, 0.51035804],
        [0.0903947 , 0.60862679, 0.175014  , 0.33070284, 0.58801598],
        [0.41892626, 0.6480461 , 0.6517817 , 0.87258078, 0.44670598]],

       [[0.49601464, 0.35481241, 0.4029047 , 0.11112621, 0.08644512],
        [0.63870538, 0.69713469, 0.68452803, 0.20691036, 0.31527184],
        [0.52317873, 0.49222384, 0.47491489, 0.42273781, 0.05692027]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [59]:
# your code/answer here
   # The e array is equal to a array, because each element of e array is correspond element o a array multiply by 1
print(f'Does e array equal to a array? => ', np.array_equal(a,e))

Does e array equal to a array? =>  True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [64]:
# your code here
d_mean=np.mean(d)
d_max=np.max(d)
d_min=np.min(d)
print(d)
print(f'max={d_max} min={d_min} mean={d_mean}')

[[[1.31691227 1.6020775  1.65936819 1.87368338 1.51035804]
  [1.0903947  1.60862679 1.175014   1.33070284 1.58801598]
  [1.41892626 1.6480461  1.6517817  1.87258078 1.44670598]]

 [[1.49601464 1.35481241 1.4029047  1.11112621 1.08644512]
  [1.63870538 1.69713469 1.68452803 1.20691036 1.31527184]
  [1.52317873 1.49222384 1.47491489 1.42273781 1.05692027]]]
max=1.8736833759553595 min=1.0569202748229616 mean=1.4585674465353342


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [68]:
# your code here
f=np.empty_like(d)
print(f)

[[[1.31691227 1.6020775  1.65936819 1.87368338 1.51035804]
  [1.0903947  1.60862679 1.175014   1.33070284 1.58801598]
  [1.41892626 1.6480461  1.6517817  1.87258078 1.44670598]]

 [[1.49601464 1.35481241 1.4029047  1.11112621 1.08644512]
  [1.63870538 1.69713469 1.68452803 1.20691036 1.31527184]
  [1.52317873 1.49222384 1.47491489 1.42273781 1.05692027]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [72]:
# your code here
print(d)

for x in range (2):
    for y in range(3):
        for z in range(5):
            if (d[x][y][z]> d_min and d[x][y][z]< d_mean):
                f[x][y][z]=25
            elif (d[x][y][z]< d_max and d[x][y][z]> d_mean):
                f[x][y][z]=75
            elif d[x][y][z]== d_mean:
                f[x][y][z]=50
            elif d[x][y][z]== d_max:
                f[x][y][z]=100
            elif d[x][y][z]== d_min:
                f[x][y][z]=0

print(f)

[[[1.31691227 1.6020775  1.65936819 1.87368338 1.51035804]
  [1.0903947  1.60862679 1.175014   1.33070284 1.58801598]
  [1.41892626 1.6480461  1.6517817  1.87258078 1.44670598]]

 [[1.49601464 1.35481241 1.4029047  1.11112621 1.08644512]
  [1.63870538 1.69713469 1.68452803 1.20691036 1.31527184]
  [1.52317873 1.49222384 1.47491489 1.42273781 1.05692027]]]
[[[ 25.  75.  75. 100.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  75.  75.  75.  25.]]

 [[ 75.  25.  25.  25.  25.]
  [ 75.  75.  75.  25.  25.]
  [ 75.  75.  75.  25.   0.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [73]:
# your code here
print(d)
print(f)

[[[1.31691227 1.6020775  1.65936819 1.87368338 1.51035804]
  [1.0903947  1.60862679 1.175014   1.33070284 1.58801598]
  [1.41892626 1.6480461  1.6517817  1.87258078 1.44670598]]

 [[1.49601464 1.35481241 1.4029047  1.11112621 1.08644512]
  [1.63870538 1.69713469 1.68452803 1.20691036 1.31527184]
  [1.52317873 1.49222384 1.47491489 1.42273781 1.05692027]]]
[[[ 25.  75.  75. 100.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  75.  75.  75.  25.]]

 [[ 75.  25.  25.  25.  25.]
  [ 75.  75.  75.  25.  25.]
  [ 75.  75.  75.  25.   0.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [76]:
# your code here
print(d)
f=np.empty(d.shape,dtype='object')   # create a new array pattern for f with data type as string to avoid errors

for x in range (2):
    for y in range(3):
        for z in range(5):
            if (d[x][y][z]> d_min and d[x][y][z]< d_mean):
                f[x][y][z]='B'
            elif (d[x][y][z]< d_max and d[x][y][z]> d_mean):
                f[x][y][z]='D'
            elif d[x][y][z]== d_mean:
                f[x][y][z]='C'
            elif d[x][y][z]== d_max:
                f[x][y][z]='E'
            elif d[x][y][z]== d_min:
                f[x][y][z]='A'

print(f)

[[[1.31691227 1.6020775  1.65936819 1.87368338 1.51035804]
  [1.0903947  1.60862679 1.175014   1.33070284 1.58801598]
  [1.41892626 1.6480461  1.6517817  1.87258078 1.44670598]]

 [[1.49601464 1.35481241 1.4029047  1.11112621 1.08644512]
  [1.63870538 1.69713469 1.68452803 1.20691036 1.31527184]
  [1.52317873 1.49222384 1.47491489 1.42273781 1.05692027]]]
[[['B' 'D' 'D' 'E' 'D']
  ['B' 'D' 'B' 'B' 'D']
  ['B' 'D' 'D' 'D' 'B']]

 [['D' 'B' 'B' 'B' 'B']
  ['D' 'D' 'D' 'B' 'B']
  ['D' 'D' 'D' 'B' 'A']]]
