# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np
import random

#### 2. Print your NumPy version.

In [2]:
# your code here

(np.__version__)

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random((2,3,5))

print(a, '\n\n', a.shape)

[[[0.82450112 0.06613666 0.71291519 0.82495308 0.03376257]
  [0.98534251 0.41827334 0.60355838 0.74955435 0.38709707]
  [0.22292379 0.8381496  0.37885306 0.94978976 0.07937722]]

 [[0.41136121 0.37836947 0.42039567 0.53232312 0.57905173]
  [0.36208394 0.33202798 0.10946172 0.29885158 0.47567318]
  [0.26714822 0.61168253 0.85954485 0.77878637 0.43481003]]] 

 (2, 3, 5)


In [4]:
# Method 2

In [5]:
# Method 3

#### 4. Print *a*.


In [6]:
# your code here

print(a)

[[[0.82450112 0.06613666 0.71291519 0.82495308 0.03376257]
  [0.98534251 0.41827334 0.60355838 0.74955435 0.38709707]
  [0.22292379 0.8381496  0.37885306 0.94978976 0.07937722]]

 [[0.41136121 0.37836947 0.42039567 0.53232312 0.57905173]
  [0.36208394 0.33202798 0.10946172 0.29885158 0.47567318]
  [0.26714822 0.61168253 0.85954485 0.77878637 0.43481003]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b= np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here

print(b, '\n\n', b.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]] 

 (5, 2, 3)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

print((a.shape) == (b.shape))

False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

# a and b doesn't have the same shape (the same number of colunms and rows)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = b.transpose(1,2,0)
print(c, '\n\n', c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] 

 (2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

# d = a + c
d = np.add(a,c)
print(d, '\n\n', d.shape)

# Transposing and changing the dimensions on matrix c to the same dimension as a, we're able to sum both of them.

[[[1.82450112 1.06613666 1.71291519 1.82495308 1.03376257]
  [1.98534251 1.41827334 1.60355838 1.74955435 1.38709707]
  [1.22292379 1.8381496  1.37885306 1.94978976 1.07937722]]

 [[1.41136121 1.37836947 1.42039567 1.53232312 1.57905173]
  [1.36208394 1.33202798 1.10946172 1.29885158 1.47567318]
  [1.26714822 1.61168253 1.85954485 1.77878637 1.43481003]]] 

 (2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print(a, '\n\n', a.shape)
print()
print(d, '\n\n', d.shape)

# Both have the same dimensions and d; d matrix is equal to adding 1 to every element from matrix a.

[[[0.82450112 0.06613666 0.71291519 0.82495308 0.03376257]
  [0.98534251 0.41827334 0.60355838 0.74955435 0.38709707]
  [0.22292379 0.8381496  0.37885306 0.94978976 0.07937722]]

 [[0.41136121 0.37836947 0.42039567 0.53232312 0.57905173]
  [0.36208394 0.33202798 0.10946172 0.29885158 0.47567318]
  [0.26714822 0.61168253 0.85954485 0.77878637 0.43481003]]] 

 (2, 3, 5)

[[[1.82450112 1.06613666 1.71291519 1.82495308 1.03376257]
  [1.98534251 1.41827334 1.60355838 1.74955435 1.38709707]
  [1.22292379 1.8381496  1.37885306 1.94978976 1.07937722]]

 [[1.41136121 1.37836947 1.42039567 1.53232312 1.57905173]
  [1.36208394 1.33202798 1.10946172 1.29885158 1.47567318]
  [1.26714822 1.61168253 1.85954485 1.77878637 1.43481003]]] 

 (2, 3, 5)


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

# e = a*c
e = np.multiply(a,c)

print(e, '\n\n', e.shape)

[[[0.82450112 0.06613666 0.71291519 0.82495308 0.03376257]
  [0.98534251 0.41827334 0.60355838 0.74955435 0.38709707]
  [0.22292379 0.8381496  0.37885306 0.94978976 0.07937722]]

 [[0.41136121 0.37836947 0.42039567 0.53232312 0.57905173]
  [0.36208394 0.33202798 0.10946172 0.29885158 0.47567318]
  [0.26714822 0.61168253 0.85954485 0.77878637 0.43481003]]] 

 (2, 3, 5)


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

# Using * (or np.multiply(x,y)) operator, we're multiplying each element from a with the correspond element from b, so te result is the same as a.

a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(f'The max value is {d_max.round(5)}, the min value in {d_min.round(5)} and the mean value is {d_mean.round(5)}.')

The max value is 1.98534, the min value in 1.03376 and the mean value is 1.49756.


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[0.82450112 0.06613666 0.71291519 0.82495308 0.03376257]
  [0.98534251 0.41827334 0.60355838 0.74955435 0.38709707]
  [0.22292379 0.8381496  0.37885306 0.94978976 0.07937722]]

 [[0.41136121 0.37836947 0.42039567 0.53232312 0.57905173]
  [0.36208394 0.33202798 0.10946172 0.29885158 0.47567318]
  [0.26714822 0.61168253 0.85954485 0.77878637 0.43481003]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [21]:
# your code here

f = []

for i in d.tolist():
    for x in i:
        for y in x:
            
            if y == d_min:
                f.append(0)

            elif y == d_mean:
                f.append(50)

            elif y == d_max:
                f.append(100)

            elif d_mean < y < d_max:
                f.append(75)

            elif d_min < y < d_mean:
                f.append(25)
    

f = np.array(f).reshape(2,3,5)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [24]:
# your code here
print(f)
f.size

[[[ 75  25  75  75   0]
  [100  25  75  75  25]
  [ 25  75  25  75  25]]

 [[ 25  25  25  75  75]
  [ 25  25  25  25  25]
  [ 25  75  75  75  25]]]


30

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [26]:
# your code here
f = []

for i in d.tolist():
    for x in i:
        for y in x:
            
            if y == d_min:
                f.append('A')

            elif y == d_mean:
                f.append('C')

            elif y == d_max:
                f.append('E')

            elif d_mean < y < d_max:
                f.append('D')

            elif d_min < y < d_mean:
                f.append('B')
    

f = np.array(f).reshape(2,3,5)

print(f)

[[['D' 'B' 'D' 'D' 'A']
  ['E' 'B' 'D' 'D' 'B']
  ['B' 'D' 'B' 'D' 'B']]

 [['B' 'B' 'B' 'D' 'D']
  ['B' 'B' 'B' 'B' 'B']
  ['B' 'D' 'D' 'D' 'B']]]
