# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [102]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [103]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [104]:
# Method 1
a= np.random.random((2,3,5))

In [105]:
# Method 2
a = np.arange(0,3,0.1).reshape(2,3,5)

In [106]:
# Method 3
a = np.random.randint(0,100, size=(2,3,5))

#### 4. Print *a*.


In [107]:
# your code here
a

array([[[73, 69,  8, 19,  6],
        [81, 11, 30, 56, 89],
        [72, 89, 14, 14, 73]],

       [[98, 67, 28, 33, 49],
        [ 0, 76, 45, 14, 77],
        [37,  9, 72, 56,  0]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [108]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [109]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [110]:
# your code here
if a.size == b.size:
    print(f'The array a with size {a.size} does the same size as the array b with size {b.size}')
else:
    print(f'The array a with size {a.size} does not equal size as the array b with size {b.size}')

The array a with size 30 does the same size as the array b with size 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [111]:
# your answer here
np.add(a,np.reshape(b,(2,3,5)))

print(np.add(a,np.reshape(b,(2,3,5))),'\n'*2,'The shape of both arrays must be the same. Then I reshape an array (in this case the array b) to apply the addition between them.')

[[[74. 70.  9. 20.  7.]
  [82. 12. 31. 57. 90.]
  [73. 90. 15. 15. 74.]]

 [[99. 68. 29. 34. 50.]
  [ 1. 77. 46. 15. 78.]
  [38. 10. 73. 57.  1.]]] 

 The shape of both arrays must be the same. Then I reshape an array (in this case the array b) to apply the addition between them.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [112]:
# your code here
c = np.reshape(b,(2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [113]:
# your code/answer here
d = np.add(a,c)
d

print(d,'\n'*2,'After we reshape the array b into variable c, we can do the addition between them because the shape of both are the same.')

[[[74. 70.  9. 20.  7.]
  [82. 12. 31. 57. 90.]
  [73. 90. 15. 15. 74.]]

 [[99. 68. 29. 34. 50.]
  [ 1. 77. 46. 15. 78.]
  [38. 10. 73. 57.  1.]]] 

 After we reshape the array b into variable c, we can do the addition between them because the shape of both are the same.


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [114]:
# your code/answer here
print(a,'\n'*4,d,'\n'*2,'The relation of the two array is given by the value of matrix c, which in turns is given by the matrix b with a new shape or resizing. Then, it can be confirm that a = np.subtract(d,c)')

[[[73 69  8 19  6]
  [81 11 30 56 89]
  [72 89 14 14 73]]

 [[98 67 28 33 49]
  [ 0 76 45 14 77]
  [37  9 72 56  0]]] 



 [[[74. 70.  9. 20.  7.]
  [82. 12. 31. 57. 90.]
  [73. 90. 15. 15. 74.]]

 [[99. 68. 29. 34. 50.]
  [ 1. 77. 46. 15. 78.]
  [38. 10. 73. 57.  1.]]] 

 The relation of the two array is given by the value of matrix c, which in turns is given by the matrix b with a new shape or resizing. Then, it can be confirm that a = np.subtract(d,c)


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [115]:
# your code here
e =np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [116]:
# your code/answer here
if np.array_equal(e,a) == True:
    print('both arrays are equal because the array "e" is defined by the array "a" multiplied by an array whose elements are of value 1. Then, I can affirm that array "e" is equal to the array "a".')
else:
    print('both arrays are not equal between them.')

both arrays are equal because the array "e" is defined by the array "a" multiplied by an array whose elements are of value 1. Then, I can affirm that array "e" is equal to the array "a".


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [117]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [165]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [166]:
# your code here
f_lst= f.tolist()
result=[]
for array in f_lst:
    for element in array:
        for number in element:
            if d_min < number < d_mean:
                result.append(25)
            elif d_mean < number < d_max:
                result.append(75)
            elif number == d_mean:
                result.append(50)
            elif number == d_max:
                result.append(100)
            elif number == d_min:
                result.append(0)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [167]:
# your code here
f=np.array(result).reshape(2,3,5)
print(f'This is the array d: \n{d} \n\n and this is the array f: \n{f}')

This is the array d: 
[[[74. 70.  9. 20.  7.]
  [82. 12. 31. 57. 90.]
  [73. 90. 15. 15. 74.]]

 [[99. 68. 29. 34. 50.]
  [ 1. 77. 46. 15. 78.]
  [38. 10. 73. 57.  1.]]] 

 and this is the array f: 
[[[ 75  75  25  25  25]
  [ 75  25  25  75  75]
  [ 75  75  25  25  75]]

 [[100  75  25  25  75]
  [  0  75  25  25  75]
  [ 25  25  75  75   0]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [180]:
# your code here
letters = []
for array in f_lst:
    for element in array:
        for number in element:
            if number == d_min:
                letters.append('A')
            elif d_min < number < d_mean:
                letters.append('B')
            elif number == d_mean:
                letters.append('C')
            elif d_mean < number < d_max:
                letters.append('D')
            elif number == d_max:
                letters.append('E')
bonus = np.array(letters).reshape(2,3,5)
bonus

array([[['D', 'D', 'B', 'B', 'B'],
        ['D', 'B', 'B', 'D', 'D'],
        ['D', 'D', 'B', 'B', 'D']],

       [['E', 'D', 'B', 'B', 'D'],
        ['A', 'D', 'B', 'B', 'D'],
        ['B', 'B', 'D', 'D', 'A']]], dtype='<U1')