# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [6]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1
a = np.random.random((2, 3, 5))
print(a)

[[[0.14247429 0.37692877 0.2157967  0.171652   0.55694069]
  [0.67871984 0.81698928 0.7707842  0.41948864 0.62058537]
  [0.15067217 0.58642457 0.66804612 0.56682815 0.86656187]]

 [[0.41983617 0.25718479 0.18149868 0.77159355 0.96791845]
  [0.14079814 0.40342065 0.82720836 0.57899599 0.3830565 ]
  [0.82406501 0.44596629 0.13246808 0.37404968 0.14560131]]]


In [9]:
# Method 2
a2 = np.random.sample((2, 3, 5))
print(a2)

[[[0.62553071 0.12019114 0.25715642 0.81166745 0.96904358]
  [0.76383904 0.61095343 0.26072538 0.45944393 0.62022092]
  [0.22421243 0.33576645 0.185126   0.69375296 0.34858808]]

 [[0.36487719 0.04955564 0.61035153 0.89835156 0.76674189]
  [0.04754842 0.33922468 0.4473835  0.36449613 0.81656876]
  [0.33574625 0.63700188 0.23475314 0.0980913  0.11454634]]]


In [10]:
# Method 3
a3 = np.random.rand(2, 3, 5)
print(a3)

[[[0.04912656 0.17166974 0.63561459 0.01270162 0.76304319]
  [0.15023216 0.73275185 0.25397969 0.9493729  0.6010961 ]
  [0.96806102 0.80430746 0.89235465 0.61705235 0.84450748]]

 [[0.54005322 0.88529564 0.62122572 0.85013869 0.07515177]
  [0.73026092 0.14952772 0.69514077 0.71360206 0.47527697]
  [0.652354   0.73469803 0.33327183 0.47444397 0.78573476]]]


#### 4. Print *a*.


In [11]:
# your code here
print(a)

[[[0.14247429 0.37692877 0.2157967  0.171652   0.55694069]
  [0.67871984 0.81698928 0.7707842  0.41948864 0.62058537]
  [0.15067217 0.58642457 0.66804612 0.56682815 0.86656187]]

 [[0.41983617 0.25718479 0.18149868 0.77159355 0.96791845]
  [0.14079814 0.40342065 0.82720836 0.57899599 0.3830565 ]
  [0.82406501 0.44596629 0.13246808 0.37404968 0.14560131]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [13]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [40]:
# your code here
size_a = a.size
size_b = b.size
size_a == size_b
#Yes, they have the same size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [39]:
# your answer here
a_b = np.add(a,b)
print(a_b)

#No, because they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [16]:
# your code here
#5x2x3
c = b.transpose(1, 2, 0)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [17]:
# your code/answer here
d = np.add(a,c)
print(d)

[[[1.14247429 1.37692877 1.2157967  1.171652   1.55694069]
  [1.67871984 1.81698928 1.7707842  1.41948864 1.62058537]
  [1.15067217 1.58642457 1.66804612 1.56682815 1.86656187]]

 [[1.41983617 1.25718479 1.18149868 1.77159355 1.96791845]
  [1.14079814 1.40342065 1.82720836 1.57899599 1.3830565 ]
  [1.82406501 1.44596629 1.13246808 1.37404968 1.14560131]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [71]:
# your code/answer here
print(a)
print()
print(d)


[[[0.14247429 0.37692877 0.2157967  0.171652   0.55694069]
  [0.67871984 0.81698928 0.7707842  0.41948864 0.62058537]
  [0.15067217 0.58642457 0.66804612 0.56682815 0.86656187]]

 [[0.41983617 0.25718479 0.18149868 0.77159355 0.96791845]
  [0.14079814 0.40342065 0.82720836 0.57899599 0.3830565 ]
  [0.82406501 0.44596629 0.13246808 0.37404968 0.14560131]]]

[[[1.14247429 1.37692877 1.2157967  1.171652   1.55694069]
  [1.67871984 1.81698928 1.7707842  1.41948864 1.62058537]
  [1.15067217 1.58642457 1.66804612 1.56682815 1.86656187]]

 [[1.41983617 1.25718479 1.18149868 1.77159355 1.96791845]
  [1.14079814 1.40342065 1.82720836 1.57899599 1.3830565 ]
  [1.82406501 1.44596629 1.13246808 1.37404968 1.14560131]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [19]:
# your code here
e = np.multiply(a,c)
print(e)

[[[0.14247429 0.37692877 0.2157967  0.171652   0.55694069]
  [0.67871984 0.81698928 0.7707842  0.41948864 0.62058537]
  [0.15067217 0.58642457 0.66804612 0.56682815 0.86656187]]

 [[0.41983617 0.25718479 0.18149868 0.77159355 0.96791845]
  [0.14079814 0.40342065 0.82720836 0.57899599 0.3830565 ]
  [0.82406501 0.44596629 0.13246808 0.37404968 0.14560131]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [38]:
# your code/answer here
e == a
#yes! they are equal because e is a*c and all values in C are 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [27]:
# your code here
d_mean = np.mean(d)
d_max = np.amax(d)
d_min = np.amin(d)
print(d_mean)
print(d_max)
print(d_min)

1.4820851434658162
1.967918454465862
1.13246807550394


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [52]:
# your code here
f = np.empty((2,3,5))
print(f.shape)

(2, 3, 5)


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [65]:
# your code here
for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x][y][z] > d_min and d[x][y][z] < d_mean:
                f[x][y][z] = (25)
            elif d[x][y][z] > d_mean and d[x][y][z] < d_max:
                f[x][y][z] = (75)
            elif d[x][y][z] == d_mean:
                f[x][y][z] = (50)
            elif d[x][y][z] == d_min:
                f[x][y][z] = (0)
            elif d[x][y][z] == d_max:
                f[x][y][z] = (100)
            
        
print(f)
    

[[[ 25.  25.  25.  25.  75.]
  [ 75.  75.  75.  25.  75.]
  [ 25.  75.  75.  75.  75.]]

 [[ 25.  25.  25.  75. 100.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  25.   0.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [58]:
# your code here
print(d)
print()
print(f)

[[[1.14247429 1.37692877 1.2157967  1.171652   1.55694069]
  [1.67871984 1.81698928 1.7707842  1.41948864 1.62058537]
  [1.15067217 1.58642457 1.66804612 1.56682815 1.86656187]]

 [[1.41983617 1.25718479 1.18149868 1.77159355 1.96791845]
  [1.14079814 1.40342065 1.82720836 1.57899599 1.3830565 ]
  [1.82406501 1.44596629 1.13246808 1.37404968 1.14560131]]]

[[[ 25.  25.  25.  25.  75.]
  [ 75.  75.  75.  25.  75.]
  [ 25.  75.  75.  75.  75.]]

 [[ 25.  25.  25.  75. 100.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  25.   0.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [72]:
# your code here
