# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [5]:
# your code here
np.version.version

'1.18.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [11]:
# Method 1
# 2 grupos, 3 filas, 5 columnas
a = np.random.random((2,3,5))
a

array([[[0.99859869, 0.92745813, 0.73869105, 0.37038091, 0.38839193],
        [0.83981073, 0.41937794, 0.80063593, 0.15248663, 0.00542012],
        [0.63864128, 0.87830444, 0.71845548, 0.92431133, 0.72199218]],

       [[0.14308844, 0.44846574, 0.43177867, 0.33782542, 0.40310598],
        [0.69155368, 0.0489409 , 0.99210527, 0.03063949, 0.63810522],
        [0.54503663, 0.63053936, 0.37565485, 0.10158482, 0.6775649 ]]])

In [16]:
# Method 2
a = np.array(np.random.random((2,3,5)))
a

array([[[0.83508814, 0.47548745, 0.18543945, 0.56687747, 0.62388485],
        [0.15921054, 0.74633075, 0.05880851, 0.68660116, 0.69278125],
        [0.07425031, 0.43359373, 0.08799751, 0.33296361, 0.30379391]],

       [[0.76400352, 0.13934424, 0.38067215, 0.83929363, 0.81888597],
        [0.49960193, 0.71175717, 0.32924569, 0.29098428, 0.5254125 ],
        [0.98034589, 0.57433168, 0.65488693, 0.08757405, 0.80535445]]])

In [20]:
# Method 3
a = np.random.uniform(low=1, high=10, size=(2,3,5))
a

array([[[9.81894317, 5.99499926, 1.34475681, 9.96752174, 8.89486034],
        [7.71993989, 7.90235561, 2.45485732, 7.11279697, 5.34192367],
        [6.72262826, 5.84774456, 2.83752343, 1.23393318, 9.16866163]],

       [[4.11045899, 1.07838798, 8.03101133, 1.49301913, 1.16858896],
        [8.95476371, 2.64308148, 1.64689369, 7.31521926, 1.07941222],
        [4.67322231, 8.9962894 , 9.80216563, 3.73184996, 3.87128318]]])

#### 4. Print *a*.


In [36]:
# your code here
print(a)
print(a.shape)

[[[9.81894317 5.99499926 1.34475681 9.96752174 8.89486034]
  [7.71993989 7.90235561 2.45485732 7.11279697 5.34192367]
  [6.72262826 5.84774456 2.83752343 1.23393318 9.16866163]]

 [[4.11045899 1.07838798 8.03101133 1.49301913 1.16858896]
  [8.95476371 2.64308148 1.64689369 7.31521926 1.07941222]
  [4.67322231 8.9962894  9.80216563 3.73184996 3.87128318]]]
(2, 3, 5)


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [35]:
# your code here
b = np.ones((5,2,3))
print(b)
b.shape

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


(5, 2, 3)

#### 6. Print *b*.


In [24]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [26]:
# your code here
# for shape 
# a.shape == b.shape
# for size
a.size == b.size
# Outcome 'True' so no, they have same size. 

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [32]:
# your answer here
# I cant because they dont have the same shape - 
print(a.shape)
print()
print(b.shape)
c = a + b 
# Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

(2, 3, 5)

(5, 2, 3)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [37]:
# your code here
c = b.reshape(2,3,5)
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [42]:
# your code/answer here
d = a + c
print(d.shape)
# works cause the have same shape
print(a.shape == c.shape)

(2, 3, 5)
True


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [40]:
# your code/answer here
print(a)
print()
print(d)
# in d we have added 1 (from b array, transposed to c) to all a array elements 

[[[9.81894317 5.99499926 1.34475681 9.96752174 8.89486034]
  [7.71993989 7.90235561 2.45485732 7.11279697 5.34192367]
  [6.72262826 5.84774456 2.83752343 1.23393318 9.16866163]]

 [[4.11045899 1.07838798 8.03101133 1.49301913 1.16858896]
  [8.95476371 2.64308148 1.64689369 7.31521926 1.07941222]
  [4.67322231 8.9962894  9.80216563 3.73184996 3.87128318]]]

[[[10.81894317  6.99499926  2.34475681 10.96752174  9.89486034]
  [ 8.71993989  8.90235561  3.45485732  8.11279697  6.34192367]
  [ 7.72262826  6.84774456  3.83752343  2.23393318 10.16866163]]

 [[ 5.11045899  2.07838798  9.03101133  2.49301913  2.16858896]
  [ 9.95476371  3.64308148  2.64689369  8.31521926  2.07941222]
  [ 5.67322231  9.9962894  10.80216563  4.73184996  4.87128318]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [44]:
# your code here
e = a*c
e

array([[[9.81894317, 5.99499926, 1.34475681, 9.96752174, 8.89486034],
        [7.71993989, 7.90235561, 2.45485732, 7.11279697, 5.34192367],
        [6.72262826, 5.84774456, 2.83752343, 1.23393318, 9.16866163]],

       [[4.11045899, 1.07838798, 8.03101133, 1.49301913, 1.16858896],
        [8.95476371, 2.64308148, 1.64689369, 7.31521926, 1.07941222],
        [4.67322231, 8.9962894 , 9.80216563, 3.73184996, 3.87128318]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [49]:
# your code/answer here
print(e == a)
print()
print(e)
print()
print(a)
# yes it does as c array elements are all 1, so the a array elements
# are all multipled by one, so stay same. 

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]

[[[9.81894317 5.99499926 1.34475681 9.96752174 8.89486034]
  [7.71993989 7.90235561 2.45485732 7.11279697 5.34192367]
  [6.72262826 5.84774456 2.83752343 1.23393318 9.16866163]]

 [[4.11045899 1.07838798 8.03101133 1.49301913 1.16858896]
  [8.95476371 2.64308148 1.64689369 7.31521926 1.07941222]
  [4.67322231 8.9962894  9.80216563 3.73184996 3.87128318]]]

[[[9.81894317 5.99499926 1.34475681 9.96752174 8.89486034]
  [7.71993989 7.90235561 2.45485732 7.11279697 5.34192367]
  [6.72262826 5.84774456 2.83752343 1.23393318 9.16866163]]

 [[4.11045899 1.07838798 8.03101133 1.49301913 1.16858896]
  [8.95476371 2.64308148 1.64689369 7.31521926 1.07941222]
  [4.67322231 8.9962894  9.80216563 3.73184996 3.87128318]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [52]:
# your code here
# max
d_max = np.max(d)

# min
d_min = np.min(d)

# mean
d_mean = np.mean(d)

print(d_max,d_min,d_mean)

10.96752174090386 2.0783879800175225 6.365303102504345


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [55]:
# your code here
f = np.empty([2,3,5])
f

array([[[9.81894317, 5.99499926, 1.34475681, 9.96752174, 8.89486034],
        [7.71993989, 7.90235561, 2.45485732, 7.11279697, 5.34192367],
        [6.72262826, 5.84774456, 2.83752343, 1.23393318, 9.16866163]],

       [[4.11045899, 1.07838798, 8.03101133, 1.49301913, 1.16858896],
        [8.95476371, 2.64308148, 1.64689369, 7.31521926, 1.07941222],
        [4.67322231, 8.9962894 , 9.80216563, 3.73184996, 3.87128318]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [58]:
# your code here
print(d)

for x in range(len(d)):
    j = 0
    for y in d[x]:
        k=0
        for item in d[x][j]:
            if item > d_min and item < d_mean:
                f[x][j][k] = 25
            elif item > d_mean and item < d_max:
                f[x][j][k] = 75
            elif item == d_mean:
                f[x][j][k] = 0
            elif item == d_max:
                f[x][j][k] = 100
            k+=1    
        j+=1

[[[10.81894317  6.99499926  2.34475681 10.96752174  9.89486034]
  [ 8.71993989  8.90235561  3.45485732  8.11279697  6.34192367]
  [ 7.72262826  6.84774456  3.83752343  2.23393318 10.16866163]]

 [[ 5.11045899  2.07838798  9.03101133  2.49301913  2.16858896]
  [ 9.95476371  3.64308148  2.64689369  8.31521926  2.07941222]
  [ 5.67322231  9.9962894  10.80216563  4.73184996  4.87128318]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [59]:
# your code here
print(d)
print(f)

[[[10.81894317  6.99499926  2.34475681 10.96752174  9.89486034]
  [ 8.71993989  8.90235561  3.45485732  8.11279697  6.34192367]
  [ 7.72262826  6.84774456  3.83752343  2.23393318 10.16866163]]

 [[ 5.11045899  2.07838798  9.03101133  2.49301913  2.16858896]
  [ 9.95476371  3.64308148  2.64689369  8.31521926  2.07941222]
  [ 5.67322231  9.9962894  10.80216563  4.73184996  4.87128318]]]
[[[ 75.          75.          25.         100.          75.        ]
  [ 75.          75.          25.          75.          25.        ]
  [ 75.          75.          25.          25.          75.        ]]

 [[ 25.           1.07838798  75.          25.          25.        ]
  [ 75.          25.          25.          75.          25.        ]
  [ 25.          75.          75.          25.          25.        ]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here