# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 2
a = np.random.random((2,3,5))
print(a)

[[[0.49872344 0.4999289  0.88704525 0.272882   0.62096164]
  [0.4441639  0.84474384 0.94756832 0.69398859 0.32271014]
  [0.6784195  0.49718946 0.14776589 0.74146683 0.73452772]]

 [[0.87092333 0.1240663  0.47914171 0.53735191 0.19294705]
  [0.0384297  0.92713102 0.30697384 0.15228882 0.47707781]
  [0.43144264 0.80904408 0.3656515  0.38480054 0.27002107]]]


In [4]:
# Method 2
b = np.empty((2,3,5))
print(b)

[[[0.49872344 0.4999289  0.88704525 0.272882   0.62096164]
  [0.4441639  0.84474384 0.94756832 0.69398859 0.32271014]
  [0.6784195  0.49718946 0.14776589 0.74146683 0.73452772]]

 [[0.87092333 0.1240663  0.47914171 0.53735191 0.19294705]
  [0.0384297  0.92713102 0.30697384 0.15228882 0.47707781]
  [0.43144264 0.80904408 0.3656515  0.38480054 0.27002107]]]


In [5]:
# Method 3
e = np.arange(20)
np.random.choice(e, (2,3,5))

array([[[ 4, 12, 14,  4, 19],
        [ 0, 12, 18, 14, 10],
        [15, 12, 10,  4, 11]],

       [[11,  0, 15,  0,  7],
        [ 5,  8, 10, 11,  5],
        [17, 16,  6, 10, 11]]])

#### 4. Print *a*.


In [6]:
print(a)

[[[0.49872344 0.4999289  0.88704525 0.272882   0.62096164]
  [0.4441639  0.84474384 0.94756832 0.69398859 0.32271014]
  [0.6784195  0.49718946 0.14776589 0.74146683 0.73452772]]

 [[0.87092333 0.1240663  0.47914171 0.53735191 0.19294705]
  [0.0384297  0.92713102 0.30697384 0.15228882 0.47707781]
  [0.43144264 0.80904408 0.3656515  0.38480054 0.27002107]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
print(len(a))
print(len(b))
print(a.size)
print(b.size)
print(a.shape)
print(b.shape)

2
5
30
30
(2, 3, 5)
(5, 2, 3)


In [10]:
if a.size == b.size:
    print(True)
else:
    print(False)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
try:
    np.add(a,b)
except ValueError:
    print("It not possible to add elements with differents shape")

It not possible to add elements with differents shape


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
c = np.transpose(b, (1, 2, 0))
print(c.shape)
print(c)

(2, 3, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here
d = np.add(a,c)
print(a.shape == c.shape)

True


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
print(a)
print(d)

print(" We are adding 1.0 to each value")

[[[0.49872344 0.4999289  0.88704525 0.272882   0.62096164]
  [0.4441639  0.84474384 0.94756832 0.69398859 0.32271014]
  [0.6784195  0.49718946 0.14776589 0.74146683 0.73452772]]

 [[0.87092333 0.1240663  0.47914171 0.53735191 0.19294705]
  [0.0384297  0.92713102 0.30697384 0.15228882 0.47707781]
  [0.43144264 0.80904408 0.3656515  0.38480054 0.27002107]]]
[[[1.49872344 1.4999289  1.88704525 1.272882   1.62096164]
  [1.4441639  1.84474384 1.94756832 1.69398859 1.32271014]
  [1.6784195  1.49718946 1.14776589 1.74146683 1.73452772]]

 [[1.87092333 1.1240663  1.47914171 1.53735191 1.19294705]
  [1.0384297  1.92713102 1.30697384 1.15228882 1.47707781]
  [1.43144264 1.80904408 1.3656515  1.38480054 1.27002107]]]
 We are adding 1.0 to each value


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
e = np.multiply(a,c)
print(e)

[[[0.49872344 0.4999289  0.88704525 0.272882   0.62096164]
  [0.4441639  0.84474384 0.94756832 0.69398859 0.32271014]
  [0.6784195  0.49718946 0.14776589 0.74146683 0.73452772]]

 [[0.87092333 0.1240663  0.47914171 0.53735191 0.19294705]
  [0.0384297  0.92713102 0.30697384 0.15228882 0.47707781]
  [0.43144264 0.80904408 0.3656515  0.38480054 0.27002107]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
np.array_equal(e,a)

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9475683213493968
1.038429698664612
1.5066458922200683


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
f = np.empty((2,3,5))
print(f)
type(f)

[[[0.49872344 0.4999289  0.88704525 0.272882   0.62096164]
  [0.4441639  0.84474384 0.94756832 0.69398859 0.32271014]
  [0.6784195  0.49718946 0.14776589 0.74146683 0.73452772]]

 [[0.87092333 0.1240663  0.47914171 0.53735191 0.19294705]
  [0.0384297  0.92713102 0.30697384 0.15228882 0.47707781]
  [0.43144264 0.80904408 0.3656515  0.38480054 0.27002107]]]


numpy.ndarray

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [19]:
# your code here
shape_d = d.shape
for x in range(shape_d[0]):
    for y in range(shape_d[1]):
        for z in range(shape_d[2]):
            if d[x][y][z] == d_min:
                f[x][y][z] = 0
            elif d[x][y][z] < d_mean:
                f[x][y][z] = 25
            elif d[x][y][z] == d_mean:
                 f[x][y][z] = 50
            elif d[x][y][z] < d_max:
                 f[x][y][z] = 75
            else:
                 f[x][y][z] = 100
print(f)
type(f)

[[[ 25.  25.  75.  25.  75.]
  [ 25.  75. 100.  75.  25.]
  [ 75.  25.  25.  75.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [  0.  75.  25.  25.  25.]
  [ 25.  75.  25.  25.  25.]]]


numpy.ndarray

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
print(d)
print(f)

[[[1.49872344 1.4999289  1.88704525 1.272882   1.62096164]
  [1.4441639  1.84474384 1.94756832 1.69398859 1.32271014]
  [1.6784195  1.49718946 1.14776589 1.74146683 1.73452772]]

 [[1.87092333 1.1240663  1.47914171 1.53735191 1.19294705]
  [1.0384297  1.92713102 1.30697384 1.15228882 1.47707781]
  [1.43144264 1.80904408 1.3656515  1.38480054 1.27002107]]]
[[[ 25.  25.  75.  25.  75.]
  [ 25.  75. 100.  75.  25.]
  [ 75.  25.  25.  75.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [  0.  75.  25.  25.  25.]
  [ 25.  75.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [34]:
print("I made many attemps, but it didn't work, finally i found a solution in stackoverflow but i don't fully understand it")
label_dict = {0:'A', 25:'B', 50:'C', 75:'D', 100:'E'}
def label_mapping(item):
    print(type(item))
    return label_dict[item]
label_mapping(f)
#list(map(lambda item: label_dict[item], f))



I made many attemps, but it didn't work, finally i found a solution in stackoverflow but i don't fully understand it
<class 'numpy.ndarray'>


TypeError: unhashable type: 'numpy.ndarray'

In [30]:
np.vectorize(label_dict.get)(f)

array([[['B', 'B', 'D', 'B', 'D'],
        ['B', 'D', 'E', 'D', 'B'],
        ['D', 'B', 'B', 'D', 'D']],

       [['D', 'B', 'B', 'D', 'B'],
        ['A', 'D', 'B', 'B', 'B'],
        ['B', 'D', 'B', 'B', 'B']]], dtype='<U1')