# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
from numpy import random
a = random.rand(2, 3, 5)


In [6]:
# Method 2
a= np.random.random((2, 3, 5))


In [3]:
# Method 3
a = np.random.sample((2,3,5))

#### 4. Print *a*.


In [7]:
# your code here
print(a)

[[[0.62307699 0.42753027 0.86727638 0.12829398 0.12269526]
  [0.67557508 0.99754949 0.35055356 0.48428129 0.55925252]
  [0.36501236 0.8637045  0.78652245 0.01351863 0.84711834]]

 [[0.80451991 0.8919122  0.00892594 0.31197869 0.23056855]
  [0.52232    0.76856451 0.93891037 0.89364966 0.02767953]
  [0.11274919 0.6858805  0.91777417 0.58152577 0.25469733]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here
# you cannot add a and b, because they have different shapes.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
print(a.shape)
print(b.shape)
c = b.reshape(2,3,5)
print(c.shape)

(2, 3, 5)
(5, 2, 3)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
# now it can be added, because the two arrays have the same shape.

d = a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
# for every value in a the value 1 of b has been added. The shape remains the same.

print(a)
print(d)

[[[0.81368893 0.34833931 0.61717101 0.89402906 0.6315455 ]
  [0.41149688 0.96586588 0.83036587 0.32290033 0.86017713]
  [0.28765971 0.86594639 0.62850357 0.93546604 0.27605093]]

 [[0.48089998 0.99725316 0.16866672 0.59682839 0.65618304]
  [0.65837441 0.86172368 0.4101617  0.08112969 0.06637897]
  [0.19186399 0.03976458 0.83731168 0.60478095 0.90733652]]]
[[[1.81368893 1.34833931 1.61717101 1.89402906 1.6315455 ]
  [1.41149688 1.96586588 1.83036587 1.32290033 1.86017713]
  [1.28765971 1.86594639 1.62850357 1.93546604 1.27605093]]

 [[1.48089998 1.99725316 1.16866672 1.59682839 1.65618304]
  [1.65837441 1.86172368 1.4101617  1.08112969 1.06637897]
  [1.19186399 1.03976458 1.83731168 1.60478095 1.90733652]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [13]:
# your code here
e = a*c
print(e)

[[[0.62307699 0.42753027 0.86727638 0.12829398 0.12269526]
  [0.67557508 0.99754949 0.35055356 0.48428129 0.55925252]
  [0.36501236 0.8637045  0.78652245 0.01351863 0.84711834]]

 [[0.80451991 0.8919122  0.00892594 0.31197869 0.23056855]
  [0.52232    0.76856451 0.93891037 0.89364966 0.02767953]
  [0.11274919 0.6858805  0.91777417 0.58152577 0.25469733]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
# all values in the array c are one. Multiplying each values in the array a with 1, the values of the new 
# array e will not change.
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [14]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max, d_min, d_mean)


1.9975494862821666 1.008925943940533 1.5354539143506272


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [15]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [16]:
# your code here
m=[]
for dd in d:
    for ddd in dd:
        for dddd in ddd:
            if d_min < dddd < d_mean:
                m.append(25)
            if d_mean < dddd < d_max:
                m.append(75)
            if dddd == d_min:
                m.append(0)
            if dddd == d_mean:
                m.append(50)
            if dddd == d_max:
                m.append(100)
h = np.array(m)   

f = h.reshape(2,3,5)

print(f)
print (d)


[[[ 75  25  75  25  25]
  [ 75 100  25  25  75]
  [ 25  75  75  25  75]]

 [[ 75  75   0  25  25]
  [ 25  75  75  75  25]
  [ 25  75  75  75  25]]]
[[[1.62307699 1.42753027 1.86727638 1.12829398 1.12269526]
  [1.67557508 1.99754949 1.35055356 1.48428129 1.55925252]
  [1.36501236 1.8637045  1.78652245 1.01351863 1.84711834]]

 [[1.80451991 1.8919122  1.00892594 1.31197869 1.23056855]
  [1.52232    1.76856451 1.93891037 1.89364966 1.02767953]
  [1.11274919 1.6858805  1.91777417 1.58152577 1.25469733]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [17]:
# your code here
print(d)
print(f)

[[[1.62307699 1.42753027 1.86727638 1.12829398 1.12269526]
  [1.67557508 1.99754949 1.35055356 1.48428129 1.55925252]
  [1.36501236 1.8637045  1.78652245 1.01351863 1.84711834]]

 [[1.80451991 1.8919122  1.00892594 1.31197869 1.23056855]
  [1.52232    1.76856451 1.93891037 1.89364966 1.02767953]
  [1.11274919 1.6858805  1.91777417 1.58152577 1.25469733]]]
[[[ 75  25  75  25  25]
  [ 75 100  25  25  75]
  [ 25  75  75  25  75]]

 [[ 75  75   0  25  25]
  [ 25  75  75  75  25]
  [ 25  75  75  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
mB=[]
for dd in d:
    for ddd in dd:
        for dddd in ddd:
            if d_min < dddd < d_mean:
                mB.append("B")
            if d_mean < dddd < d_max:
                mB.append("D")
            if dddd == d_min:
                mB.append("A")
            if dddd == d_mean:
                mB.append("C")
            if dddd == d_max:
                mB.append("E")
hB = np.array(mB)   

fB = hB.reshape(2,3,5)

print(fB)
print (d)



[[['D' 'B' 'D' 'B' 'B']
  ['D' 'E' 'B' 'B' 'D']
  ['B' 'D' 'D' 'B' 'D']]

 [['D' 'D' 'A' 'B' 'B']
  ['B' 'D' 'D' 'D' 'B']
  ['B' 'D' 'D' 'D' 'B']]]
[[[1.62307699 1.42753027 1.86727638 1.12829398 1.12269526]
  [1.67557508 1.99754949 1.35055356 1.48428129 1.55925252]
  [1.36501236 1.8637045  1.78652245 1.01351863 1.84711834]]

 [[1.80451991 1.8919122  1.00892594 1.31197869 1.23056855]
  [1.52232    1.76856451 1.93891037 1.89364966 1.02767953]
  [1.11274919 1.6858805  1.91777417 1.58152577 1.25469733]]]
