# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))

In [4]:
# Method 2
a = np.random.randint(0,9,(2,3,5))

In [5]:
# Method 3
a = np.random.randn(2,3,5)

#### 4. Print *a*.


In [6]:
# your copde here
print(a)

[[[-1.03871077 -0.56552742 -0.25559267 -0.60957538  0.65156162]
  [-0.34442638 -0.0622914   0.42615569  0.5953877   1.20786226]
  [ 0.4065177   0.97045373  1.45924637  0.03568557 -0.40258214]]

 [[ 1.54863219 -1.5874578   0.43244932  1.62927463  0.86861343]
  [-0.99097162  0.38886767  0.89716399 -0.73874324  0.48806038]
  [ 2.73716919  1.9806301   1.30730263 -0.70052443  1.84349572]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(f"Size a = {a.size}")
print(f"Size b = {b.size}")
f"Both have the same size? {a.size == b.size}"

Size a = 30
Size b = 30


'Both have the same size? True'

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

# a+b
# np.add(a,b)

#You cant sum both because have different dimensions

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.transpose(1,2,0)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a,c)

# Because we'got the same shape.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print(f"Shape a: {a.shape} \n{a}\n")
print(f"Shape d: {d.shape} \n{d}")

# Both have the same dimension (2x3x5) but different values

Shape a: (2, 3, 5) 
[[[-1.03871077 -0.56552742 -0.25559267 -0.60957538  0.65156162]
  [-0.34442638 -0.0622914   0.42615569  0.5953877   1.20786226]
  [ 0.4065177   0.97045373  1.45924637  0.03568557 -0.40258214]]

 [[ 1.54863219 -1.5874578   0.43244932  1.62927463  0.86861343]
  [-0.99097162  0.38886767  0.89716399 -0.73874324  0.48806038]
  [ 2.73716919  1.9806301   1.30730263 -0.70052443  1.84349572]]]

Shape d: (2, 3, 5) 
[[[-0.03871077  0.43447258  0.74440733  0.39042462  1.65156162]
  [ 0.65557362  0.9377086   1.42615569  1.5953877   2.20786226]
  [ 1.4065177   1.97045373  2.45924637  1.03568557  0.59741786]]

 [[ 2.54863219 -0.5874578   1.43244932  2.62927463  1.86861343]
  [ 0.00902838  1.38886767  1.89716399  0.26125676  1.48806038]
  [ 3.73716919  2.9806301   2.30730263  0.29947557  2.84349572]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

e = np.multiply(a,c)
# e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here

e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

3.737169187166859
-0.5874578041354994
1.4192708889413248


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here

f = np.empty((2,3,5))
print(f)


[[[-0.03871077  0.43447258  0.74440733  0.39042462  1.65156162]
  [ 0.65557362  0.9377086   1.42615569  1.5953877   2.20786226]
  [ 1.4065177   1.97045373  2.45924637  1.03568557  0.59741786]]

 [[ 2.54863219 -0.5874578   1.43244932  2.62927463  1.86861343]
  [ 0.00902838  1.38886767  1.89716399  0.26125676  1.48806038]
  [ 3.73716919  2.9806301   2.30730263  0.29947557  2.84349572]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [24]:
# your code here

# cont_fila = 0
# cont_col = 0
# cont_dimension = 0

# for dim in range(d.shape[0]):
#     for raw in range(d.shape[1]):
#         for cols in range(d.shape[2]):
#             if d_mean > d[cont_dimension][cont_fila][cont_col] > d_min:
#                 f[cont_dimension][cont_fila][cont_col] = 25
#                 if cont_col < 5:
#                     cont_col += 1
#             elif d_max > d[cont_dimension][cont_fila][cont_col] > d_mean:
#                 f[cont_dimension][cont_fila][cont_col] = 75
#                 if cont_col < 5:
#                     cont_col += 1
#             elif d[cont_dimension][cont_fila][cont_col] == d_mean:
#                 f[cont_dimension][cont_fila][cont_col] = 50
#                 if cont_col < 5:
#                     cont_col += 1
#             elif d[cont_dimension][cont_fila][cont_col] == d_min:
#                 f[cont_dimension][cont_fila][cont_col] = 0
#                 if cont_col < 5:
#                     cont_col += 1
#             elif d[cont_dimension][cont_fila][cont_col] == d_max:
#                 f[cont_dimension][cont_fila][cont_col] = 100
#                 if cont_col < 5:
#                     cont_col += 1
#         if cont_fila < 3:
#             cont_fila += 1
#         cont_col = 0
#     cont_fila = 0
#     cont_col = 0
#     cont_dimension += 1
    
# Other way using Numpy:
f = [[[25 if d_mean > cols > d_min else 75 if d_max > cols > d_mean else 50 if cols == d_mean else 0 if cols == d_min
       else 100 for cols in raw] for raw in dim] for dim in d]
f=np.asarray(f)


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [25]:
# your code here
print(f"matrix d:\n{d}")
print(f"\nmatrix f:\n{f}")

matrix d:
[[[-0.03871077  0.43447258  0.74440733  0.39042462  1.65156162]
  [ 0.65557362  0.9377086   1.42615569  1.5953877   2.20786226]
  [ 1.4065177   1.97045373  2.45924637  1.03568557  0.59741786]]

 [[ 2.54863219 -0.5874578   1.43244932  2.62927463  1.86861343]
  [ 0.00902838  1.38886767  1.89716399  0.26125676  1.48806038]
  [ 3.73716919  2.9806301   2.30730263  0.29947557  2.84349572]]]

matrix f:
[[[ 25  25  25  25  75]
  [ 25  25  75  75  75]
  [ 25  75  75  25  25]]

 [[ 75   0  75  75  75]
  [ 25  25  75  25  75]
  [100  75  75  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [28]:
# your code here

letters = [[['B' if d_mean > cols > d_min else 'D' if d_max > cols > d_mean else 'C' if cols == d_mean else 'A' if cols == d_min
       else 'E' for cols in raw] for raw in dim] for dim in d]
letters=np.asarray(letters)

print(f"Matrix f:\n{f}")
print(f"\nLetters:\n{letters}")

Matrix f:
[[[ 25  25  25  25  75]
  [ 25  25  75  75  75]
  [ 25  75  75  25  25]]

 [[ 75   0  75  75  75]
  [ 25  25  75  25  75]
  [100  75  75  25  75]]]

Letters:
[[['B' 'B' 'B' 'B' 'D']
  ['B' 'B' 'D' 'D' 'D']
  ['B' 'D' 'D' 'B' 'B']]

 [['D' 'A' 'D' 'D' 'D']
  ['B' 'B' 'D' 'B' 'D']
  ['E' 'D' 'D' 'B' 'D']]]
