# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [58]:
# Method 1

a = np.zeros((2,3,5))

In [59]:
# Method 2
a = np.ones((2,3,5))

In [60]:
# Method 3
a = np.random.random((2,3,5))

#### 4. Print *a*.


In [61]:
# your code here
a

array([[[0.56790494, 0.39421926, 0.92491102, 0.2255944 , 0.96558757],
        [0.50190927, 0.25039895, 0.01620865, 0.82360897, 0.30169522],
        [0.85386711, 0.03946137, 0.63530969, 0.72335533, 0.67033296]],

       [[0.2332001 , 0.16142717, 0.21905934, 0.57388998, 0.28979966],
        [0.28783979, 0.10980558, 0.39824913, 0.88703671, 0.42785908],
        [0.14532981, 0.85339551, 0.84099893, 0.53269038, 0.66992067]]])

In [74]:
a.shape

(2, 3, 5)

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [75]:
# your code here
b = np.ones((5,3,2))

#### 6. Print *b*.


In [76]:
# your code here
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [77]:
b.shape

(5, 3, 2)

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [78]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [79]:
# your answer here

np.add(a,b)

#you aren't able to add one to other as the shape isn't the same in both arrays

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [80]:
# your code here
c = b.T

In [81]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [82]:
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [83]:
# your code/answer here
np.add(a, c)

array([[[1.56790494, 1.39421926, 1.92491102, 1.2255944 , 1.96558757],
        [1.50190927, 1.25039895, 1.01620865, 1.82360897, 1.30169522],
        [1.85386711, 1.03946137, 1.63530969, 1.72335533, 1.67033296]],

       [[1.2332001 , 1.16142717, 1.21905934, 1.57388998, 1.28979966],
        [1.28783979, 1.10980558, 1.39824913, 1.88703671, 1.42785908],
        [1.14532981, 1.85339551, 1.84099893, 1.53269038, 1.66992067]]])

In [84]:
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [93]:
# your code/answer here
print(a)
print('--------')
print(d)

#the array d is values of array a plus 1

[[[0.56790494 0.39421926 0.92491102 0.2255944  0.96558757]
  [0.50190927 0.25039895 0.01620865 0.82360897 0.30169522]
  [0.85386711 0.03946137 0.63530969 0.72335533 0.67033296]]

 [[0.2332001  0.16142717 0.21905934 0.57388998 0.28979966]
  [0.28783979 0.10980558 0.39824913 0.88703671 0.42785908]
  [0.14532981 0.85339551 0.84099893 0.53269038 0.66992067]]]
--------
[[[1.56790494 1.39421926 1.92491102 1.2255944  1.96558757]
  [1.50190927 1.25039895 1.01620865 1.82360897 1.30169522]
  [1.85386711 1.03946137 1.63530969 1.72335533 1.67033296]]

 [[1.2332001  1.16142717 1.21905934 1.57388998 1.28979966]
  [1.28783979 1.10980558 1.39824913 1.88703671 1.42785908]
  [1.14532981 1.85339551 1.84099893 1.53269038 1.66992067]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [95]:
# your code here

e = c * a
e

array([[[0.56790494, 0.39421926, 0.92491102, 0.2255944 , 0.96558757],
        [0.50190927, 0.25039895, 0.01620865, 0.82360897, 0.30169522],
        [0.85386711, 0.03946137, 0.63530969, 0.72335533, 0.67033296]],

       [[0.2332001 , 0.16142717, 0.21905934, 0.57388998, 0.28979966],
        [0.28783979, 0.10980558, 0.39824913, 0.88703671, 0.42785908],
        [0.14532981, 0.85339551, 0.84099893, 0.53269038, 0.66992067]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [96]:
# your code/answer here

e == a
#they are equal, anything multiplied by 1 is the same

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here