# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [14]:
# Method 1
a = np.random.random((2,3,5))

In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [15]:
# your code here
print(a)

[[[0.79615283 0.45138628 0.43076532 0.05565525 0.93232795]
  [0.2968211  0.66579791 0.31206383 0.78970312 0.00866184]
  [0.51934294 0.67481863 0.31411182 0.126678   0.45210299]]

 [[0.81629981 0.69284397 0.54353399 0.08556316 0.51996583]
  [0.31061286 0.96263771 0.40797735 0.96390932 0.61813097]
  [0.90381947 0.76248545 0.10424637 0.11258173 0.18864993]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [43]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [47]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [46]:
# your code here

a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [62]:
# your answer here
np.concatenate([a,b])
#it's not possible because they have the same shape and the axis doesn't match

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [77]:
# your code here
c= b.transpose(1,2,0)
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [88]:
# your code/answer here
d = np.concatenate([a,c])
d
#because they have the same shape and the axes match

array([[[0.79615283, 0.45138628, 0.43076532, 0.05565525, 0.93232795],
        [0.2968211 , 0.66579791, 0.31206383, 0.78970312, 0.00866184],
        [0.51934294, 0.67481863, 0.31411182, 0.126678  , 0.45210299]],

       [[0.81629981, 0.69284397, 0.54353399, 0.08556316, 0.51996583],
        [0.31061286, 0.96263771, 0.40797735, 0.96390932, 0.61813097],
        [0.90381947, 0.76248545, 0.10424637, 0.11258173, 0.18864993]],

       [[1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ]],

       [[1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        , 1.        , 1.        ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [71]:
# your code/answer here
print(a)
print()
print()
print(d)
# "d" has the double of arrays: 4 instead of 2 that "a" has.

[[[0.79615283 0.45138628 0.43076532 0.05565525 0.93232795]
  [0.2968211  0.66579791 0.31206383 0.78970312 0.00866184]
  [0.51934294 0.67481863 0.31411182 0.126678   0.45210299]]

 [[0.81629981 0.69284397 0.54353399 0.08556316 0.51996583]
  [0.31061286 0.96263771 0.40797735 0.96390932 0.61813097]
  [0.90381947 0.76248545 0.10424637 0.11258173 0.18864993]]]


[[[0.79615283 0.45138628 0.43076532 0.05565525 0.93232795]
  [0.2968211  0.66579791 0.31206383 0.78970312 0.00866184]
  [0.51934294 0.67481863 0.31411182 0.126678   0.45210299]]

 [[0.81629981 0.69284397 0.54353399 0.08556316 0.51996583]
  [0.31061286 0.96263771 0.40797735 0.96390932 0.61813097]
  [0.90381947 0.76248545 0.10424637 0.11258173 0.18864993]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.      

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [75]:
# your code here
e = a*c
e

array([[[0.79615283, 0.45138628, 0.43076532, 0.05565525, 0.93232795],
        [0.2968211 , 0.66579791, 0.31206383, 0.78970312, 0.00866184],
        [0.51934294, 0.67481863, 0.31411182, 0.126678  , 0.45210299]],

       [[0.81629981, 0.69284397, 0.54353399, 0.08556316, 0.51996583],
        [0.31061286, 0.96263771, 0.40797735, 0.96390932, 0.61813097],
        [0.90381947, 0.76248545, 0.10424637, 0.11258173, 0.18864993]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
#it's the same because we are multiplying * 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [82]:
# your code here
d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

1.0
0.008661835217974367
0.7469941291203342


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [92]:
# your code here
f = np.empty((2,3,5))
f

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [105]:
# your code here
'''for col in d:
    for row in col:
        for value in row:
            if value > d_min and value < d_mean:'''


                
    


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here