# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a=np.random.random((2,3,5)) #random valors between 0 and 1 (but not included the number 1)


In [4]:
# Method 2
a=np.random.rand(2,3,5)  #other form with rand


In [5]:
# Method 3
a=np.random.ranf((2,3,5)) #other form with ranf


#### 4. Print *a*.


In [6]:
# your code here
a

array([[[0.86727796, 0.74239057, 0.59349874, 0.68442072, 0.81952371],
        [0.71868111, 0.24239272, 0.45945018, 0.0229523 , 0.49586134],
        [0.35789196, 0.22389139, 0.56503513, 0.00395188, 0.89453593]],

       [[0.090906  , 0.11251085, 0.47741232, 0.54362031, 0.61781174],
        [0.5785119 , 0.13466542, 0.80027918, 0.13768054, 0.89667849],
        [0.69055335, 0.80879624, 0.78610832, 0.18966181, 0.34933771]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b=np.ones((5,2,3)) # use np.ones (array with all valors = 1)

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
np.size(a)==np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
#np.add(a,b) 
# we can not add a + be because these arrays has different rows and columns (different "shape")
np.shape(a)==np.shape(b)

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [14]:
# your code here
c=np.transpose(b,(1,2,0))  #we use np.transpose 
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [15]:
# your code/answer here
d=np.add(a,c)
#work because both arrays has the same "shape" (2x3x5)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [46]:
# your code/answer here
print(a)
print('\n\n')
print(d)
#the matrix d has the sum a+c, and the array c is with all values 1. 
#For this reason the values of the array d (in the same position) has 1 unit more than the array a 

[[[0.86727796 0.74239057 0.59349874 0.68442072 0.81952371]
  [0.71868111 0.24239272 0.45945018 0.0229523  0.49586134]
  [0.35789196 0.22389139 0.56503513 0.00395188 0.89453593]]

 [[0.090906   0.11251085 0.47741232 0.54362031 0.61781174]
  [0.5785119  0.13466542 0.80027918 0.13768054 0.89667849]
  [0.69055335 0.80879624 0.78610832 0.18966181 0.34933771]]]



[[[1.86727796 1.74239057 1.59349874 1.68442072 1.81952371]
  [1.71868111 1.24239272 1.45945018 1.0229523  1.49586134]
  [1.35789196 1.22389139 1.56503513 1.00395188 1.89453593]]

 [[1.090906   1.11251085 1.47741232 1.54362031 1.61781174]
  [1.5785119  1.13466542 1.80027918 1.13768054 1.89667849]
  [1.69055335 1.80879624 1.78610832 1.18966181 1.34933771]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [20]:
# your code here
e=np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [21]:
# your code/answer here
print(e==a)
#because the array c all values are 1. If we multiply for 1, we have the same value :)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [34]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(f'The max value in d is {d_max}.\nThe min value in d is {d_min}.\nThe mean value in d is {d_mean}.')

The max value in d is 1.89667848838323.
The min value in d is 1.0039518771165208.
The mean value in d is 1.4968763273991843.


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [51]:
# your code here
f=np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [47]:
# your code here
for i in range(len(d)): #we go through the first value of the shape of array d (2)
    for j in range(len(d[i])): #we go through the second value of the shape of array d (3)
        for k in range(len(d[i][j])): #we go through the third value of the shape of array d (5)
            if d[i][j][k]>d_min and d[i][j][k]<d_mean: #we add the value in f, depend of the conditions:
                f[i][j][k]=25
            elif d[i][j][k]>d_mean and d[i][j][k]<d_max:
                f[i][j][k]=75
            elif d[i][j][k]==d_min:
                f[i][j][k]=0
            elif d[i][j][k]==d_mean:
                f[i][j][k]=50
            else:
                f[i][j][k]=100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [50]:
# your code here
print(d)
print('\n\n')
print(f)

[[[1.86727796 1.74239057 1.59349874 1.68442072 1.81952371]
  [1.71868111 1.24239272 1.45945018 1.0229523  1.49586134]
  [1.35789196 1.22389139 1.56503513 1.00395188 1.89453593]]

 [[1.090906   1.11251085 1.47741232 1.54362031 1.61781174]
  [1.5785119  1.13466542 1.80027918 1.13768054 1.89667849]
  [1.69055335 1.80879624 1.78610832 1.18966181 1.34933771]]]



[[[ 75.  75.  75.  75.  75.]
  [ 75.  25.  25.  25.  25.]
  [ 25.  25.  75.   0.  75.]]

 [[ 25.  25.  25.  75.  75.]
  [ 75.  25.  75.  25. 100.]
  [ 75.  75.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [56]:
# your code here
#we create a new array empty f_bonus of type=string; we put dtype=str
f_bonus=np.empty((2,3,5),dtype=str)

#we change the for loops with the letters: A,B,C,D,E
for i in range(len(d)): #we go through the first value of the shape of array d (2)
    for j in range(len(d[i])): #we go through the second value of the shape of array d (3)
        for k in range(len(d[i][j])): #we go through the third value of the shape of array d (5)
            if d[i][j][k]>d_min and d[i][j][k]<d_mean: #we add the value in f_bonus, depend of the conditions:
                f_bonus[i][j][k]='B'
            elif d[i][j][k]>d_mean and d[i][j][k]<d_max:
                f_bonus[i][j][k]='D'
            elif d[i][j][k]==d_min:
                f_bonus[i][j][k]='A'
            elif d[i][j][k]==d_mean:
                f_bonus[i][j][k]='C'
            else:
                f_bonus[i][j][k]='E'

print(f_bonus)

[[['D' 'D' 'D' 'D' 'D']
  ['D' 'B' 'B' 'B' 'B']
  ['B' 'B' 'D' 'A' 'D']]

 [['B' 'B' 'B' 'D' 'D']
  ['D' 'B' 'D' 'B' 'E']
  ['D' 'D' 'D' 'B' 'B']]]
