# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [38]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [39]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [40]:
# Method 1
import random
l= random.sample(range(30), 30)
a=np.array(l).reshape(2,3,5)

In [41]:
# Method 2
a=np.random.random((2,3,5))

In [42]:
# Method 3
a=np.floor(10*np.random.random((2,3,5)))

#### 4. Print *a*.


In [43]:
# your code here
print(a)

[[[0. 3. 3. 5. 4.]
  [5. 2. 0. 3. 9.]
  [1. 6. 8. 0. 4.]]

 [[9. 7. 8. 3. 4.]
  [5. 0. 5. 2. 4.]
  [2. 3. 3. 4. 7.]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [44]:
# your code here
b=np.ones((5,2,3))

#### 6. Print *b*.


In [45]:
# your code here
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [46]:
# your code here
#size is the number of elements in the array, and there is a numpy function that tells the number of elements in an array
# if both arrays have the same value for this function, they must have the same size

if a.size==b.size:
    print(f"The size of array a is {a.size} and the size of array b is {b.size} so they both have the same size")

The size of array a is 30 and the size of array b is 30 so they both have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [17]:
# your answer here
#Arithmetic operators on arrays apply elementwise. This means that they must have the same size and shape, so  i believe I cannot sum them, bur the bradcasting characteristic of numpy makes me doubt, so I try:
# and i get the error operands could not be broadcast together with shapes (2,3,5) (5,2,3)
#so my final answer is no, because the shape of a and b does not permit broadcasting

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [47]:
# your code here

c=b.reshape (2,3,5)
print (c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [48]:
# your code/answer here
d=a+c
print(d)
# It works because the arrays have exactly the same shape, so the elementwise operation can take place 


[[[ 1.  4.  4.  6.  5.]
  [ 6.  3.  1.  4. 10.]
  [ 2.  7.  9.  1.  5.]]

 [[10.  8.  9.  4.  5.]
  [ 6.  1.  6.  3.  5.]
  [ 3.  4.  4.  5.  8.]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [49]:
# your code/answer here
print ("This is a")
print (a)
print()
print ("And this is d:")
print (d)
# each value in d is the result of adding 1 to its correspondent index value in a, which is the result of adding elementwise the values of b

This is a
[[[0. 3. 3. 5. 4.]
  [5. 2. 0. 3. 9.]
  [1. 6. 8. 0. 4.]]

 [[9. 7. 8. 3. 4.]
  [5. 0. 5. 2. 4.]
  [2. 3. 3. 4. 7.]]]

And this is d:
[[[ 1.  4.  4.  6.  5.]
  [ 6.  3.  1.  4. 10.]
  [ 2.  7.  9.  1.  5.]]

 [[10.  8.  9.  4.  5.]
  [ 6.  1.  6.  3.  5.]
  [ 3.  4.  4.  5.  8.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [50]:
# your code here
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [51]:
# your code/answer here
#Yes it does, because python does not perfom the mathematical matrix operation when multiplying arrays. Instead, it does the multiplication in an element wise way.
#This means that it operates each pair of elements with the same index and since c is a full-ones array, the multiplication gives the same number at every index, which produces an identical array

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [52]:
# your code here
d_max=np.max(d)
print (d_max)
d_min=np.min(d)
print (d_min)
d_mean=np.mean(d)
print (d_mean)


10.0
1.0
4.966666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [53]:
# your code here

f=np.empty((2,3,5))
print(f)


[[[0. 3. 3. 8. 0.]
  [3. 4. 0. 7. 8.]
  [5. 3. 9. 1. 9.]]

 [[4. 8. 9. 8. 7.]
  [8. 6. 1. 0. 9.]
  [7. 9. 9. 2. 4.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [65]:
# your code here
new_d=[]
for element in d.flat:
    if element==d_min:
        new_d.append(0)
    if element==d_max:
        new_d.append (100)
    if element==d_mean:
        newd.append(50)
    if (element>d_min) and (element<d_mean):
        new_d.append(25)
    if (element<d_max) and (element>d_mean):
        new_d.append(75)
print (new_d)
f=np.array((new_d))
f=f.reshape(2,3,5)

[0, 25, 25, 75, 75, 75, 25, 0, 25, 100, 25, 75, 75, 0, 75, 100, 75, 75, 25, 75, 75, 0, 75, 25, 75, 25, 25, 25, 75, 75]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [66]:
# your code here
print (d)
print()
print(f)

[[[ 1.  4.  4.  6.  5.]
  [ 6.  3.  1.  4. 10.]
  [ 2.  7.  9.  1.  5.]]

 [[10.  8.  9.  4.  5.]
  [ 6.  1.  6.  3.  5.]
  [ 3.  4.  4.  5.  8.]]]

[[[  0  25  25  75  75]
  [ 75  25   0  25 100]
  [ 25  75  75   0  75]]

 [[100  75  75  25  75]
  [ 75   0  75  25  75]
  [ 25  25  25  75  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [68]:
# your code here
new_d=[]
for element in d.flat:
    if element==d_min:
        new_d.append("A")
    if element==d_max:
        new_d.append ("E")
    if element==d_mean:
        newd.append("C")
    if (element>d_min) and (element<d_mean):
        new_d.append("B")
    if (element<d_max) and (element>d_mean):
        new_d.append("D")
print (new_d)
f=np.array((new_d))
f=f.reshape(2,3,5)
print (d)
print()
print(f)

['A', 'B', 'B', 'D', 'D', 'D', 'B', 'A', 'B', 'E', 'B', 'D', 'D', 'A', 'D', 'E', 'D', 'D', 'B', 'D', 'D', 'A', 'D', 'B', 'D', 'B', 'B', 'B', 'D', 'D']
[[[ 1.  4.  4.  6.  5.]
  [ 6.  3.  1.  4. 10.]
  [ 2.  7.  9.  1.  5.]]

 [[10.  8.  9.  4.  5.]
  [ 6.  1.  6.  3.  5.]
  [ 3.  4.  4.  5.  8.]]]

[[['A' 'B' 'B' 'D' 'D']
  ['D' 'B' 'A' 'B' 'E']
  ['B' 'D' 'D' 'A' 'D']]

 [['E' 'D' 'D' 'B' 'D']
  ['D' 'A' 'D' 'B' 'D']
  ['B' 'B' 'B' 'D' 'D']]]
