# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np


#### 2. Print your NumPy version.

In [13]:
# your code here
np.version.version

#on bash we could use 'pip freeze | grep "numpy"'

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [21]:
# Method 1
a = np.random.random((2,3,5))

a

array([[[0.36733497, 0.67224969, 0.7869474 , 0.45527218, 0.76432438],
        [0.68951765, 0.96944566, 0.26790486, 0.26156721, 0.99318842],
        [0.58403512, 0.34326469, 0.92102914, 0.84595732, 0.43286215]],

       [[0.36096849, 0.68946345, 0.29251336, 0.48655687, 0.00223098],
        [0.89023068, 0.0704851 , 0.47753732, 0.195914  , 0.10492546],
        [0.09416353, 0.24107219, 0.49308938, 0.41800589, 0.48548138]]])

In [38]:
# Method 2
a2 = np.empty((2,3,5))
a2

array([[[0.9006397 , 0.90864645, 0.88295592, 0.4333856 , 0.94796761],
        [0.27013524, 0.36430349, 0.28086466, 0.05572809, 0.8072747 ],
        [0.23291503, 0.87669865, 0.61089891, 0.63211643, 0.74480141]],

       [[0.52036136, 0.85246746, 0.63144934, 0.5304022 , 0.15762665],
        [0.07011035, 0.6663579 , 0.17969123, 0.53028614, 0.46253536],
        [0.94157957, 0.86721348, 0.06476687, 0.88614268, 0.30336761]]])

In [25]:
# Method 3
a3 = np.random.randint((2,3,5))
a3

array([0, 2, 1])

#### 4. Print *a*.


In [22]:
# your code here
a

array([[[0.36733497, 0.67224969, 0.7869474 , 0.45527218, 0.76432438],
        [0.68951765, 0.96944566, 0.26790486, 0.26156721, 0.99318842],
        [0.58403512, 0.34326469, 0.92102914, 0.84595732, 0.43286215]],

       [[0.36096849, 0.68946345, 0.29251336, 0.48655687, 0.00223098],
        [0.89023068, 0.0704851 , 0.47753732, 0.195914  , 0.10492546],
        [0.09416353, 0.24107219, 0.49308938, 0.41800589, 0.48548138]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [27]:
# your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [26]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [33]:
# your code here
for x in a:
    for m in b:
        if len(a) == len(b):
            print(True)
        else:
            print(False)
            pass

False
False
False
False
False
False
False
False
False
False


In [34]:
len(a) == len(b)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [36]:
# your answer here
np.add(a,b) #<-- this is the method to do it but you can't add them together since they don't have the same number
#of 'matrixes' a has 2 groups and b has 5, so python can't manage them.


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [47]:
# your code here
c = b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [48]:
# your code/answer here
d = np.add(a,c)
d

#now its working because the matrixes have the same shape so numpy understand and can work with 'a' and 'b'.

array([[[1.36733497, 1.67224969, 1.7869474 , 1.45527218, 1.76432438],
        [1.68951765, 1.96944566, 1.26790486, 1.26156721, 1.99318842],
        [1.58403512, 1.34326469, 1.92102914, 1.84595732, 1.43286215]],

       [[1.36096849, 1.68946345, 1.29251336, 1.48655687, 1.00223098],
        [1.89023068, 1.0704851 , 1.47753732, 1.195914  , 1.10492546],
        [1.09416353, 1.24107219, 1.49308938, 1.41800589, 1.48548138]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [51]:
# your code/answer here
print(a)
print()
print(d)

#'d' is adding the 1. from 'b' to 'a' it is making a sum() to the matrixes.

[[[0.36733497 0.67224969 0.7869474  0.45527218 0.76432438]
  [0.68951765 0.96944566 0.26790486 0.26156721 0.99318842]
  [0.58403512 0.34326469 0.92102914 0.84595732 0.43286215]]

 [[0.36096849 0.68946345 0.29251336 0.48655687 0.00223098]
  [0.89023068 0.0704851  0.47753732 0.195914   0.10492546]
  [0.09416353 0.24107219 0.49308938 0.41800589 0.48548138]]]

[[[1.36733497 1.67224969 1.7869474  1.45527218 1.76432438]
  [1.68951765 1.96944566 1.26790486 1.26156721 1.99318842]
  [1.58403512 1.34326469 1.92102914 1.84595732 1.43286215]]

 [[1.36096849 1.68946345 1.29251336 1.48655687 1.00223098]
  [1.89023068 1.0704851  1.47753732 1.195914   1.10492546]
  [1.09416353 1.24107219 1.49308938 1.41800589 1.48548138]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [52]:
# your code here
e = a * c
e
#the output is the same as 'a' because 'c' all the values are ones.

array([[[0.36733497, 0.67224969, 0.7869474 , 0.45527218, 0.76432438],
        [0.68951765, 0.96944566, 0.26790486, 0.26156721, 0.99318842],
        [0.58403512, 0.34326469, 0.92102914, 0.84595732, 0.43286215]],

       [[0.36096849, 0.68946345, 0.29251336, 0.48655687, 0.00223098],
        [0.89023068, 0.0704851 , 0.47753732, 0.195914  , 0.10492546],
        [0.09416353, 0.24107219, 0.49308938, 0.41800589, 0.48548138]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [54]:
# your code/answer here
answer = e == a
print(answer)

#as I said on the previous exercise, its the same because 'c' values are just ones.

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [59]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9931884165579445
1.002230978715763
1.4885846306511872


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [62]:
# your code here
f = np.empty((2,3,5))

f

array([[[0.36733497, 0.67224969, 0.7869474 , 0.45527218, 0.76432438],
        [0.68951765, 0.96944566, 0.26790486, 0.26156721, 0.99318842],
        [0.58403512, 0.34326469, 0.92102914, 0.84595732, 0.43286215]],

       [[0.36096849, 0.68946345, 0.29251336, 0.48655687, 0.00223098],
        [0.89023068, 0.0704851 , 0.47753732, 0.195914  , 0.10492546],
        [0.09416353, 0.24107219, 0.49308938, 0.41800589, 0.48548138]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here