# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.2950792 , 0.20069242, 0.80670576, 0.79165687, 0.49214055],
        [0.22478718, 0.15019248, 0.55666361, 0.38919618, 0.64131195],
        [0.8813294 , 0.12209126, 0.93033666, 0.27352774, 0.0235622 ]],

       [[0.5976319 , 0.3841011 , 0.91296569, 0.41160471, 0.60079363],
        [0.58732521, 0.29320319, 0.86465693, 0.08086109, 0.46175518],
        [0.10696335, 0.81988277, 0.09096855, 0.44855579, 0.70635173]]])

In [4]:
# Method 2
a = np.random.randint(1000, size=(2,3,5))
a

array([[[129, 947,  33, 236, 819],
        [813, 696, 411, 810, 626],
        [512, 751, 783, 864,  29]],

       [[566, 441, 950, 803, 717],
        [896, 789, 401, 939, 695],
        [ 88,  20, 920, 841, 510]]])

In [5]:
# Method 3
a = np.random.rand(2,3,5)
a

array([[[0.96446324, 0.19836034, 0.87924349, 0.85809597, 0.87618198],
        [0.40271629, 0.16987447, 0.24852037, 0.26929028, 0.78318367],
        [0.07205774, 0.5480108 , 0.03991835, 0.40859816, 0.53261905]],

       [[0.64174815, 0.4187394 , 0.04499273, 0.2560781 , 0.9598201 ],
        [0.45465946, 0.55219183, 0.71096617, 0.24364299, 0.7188212 ],
        [0.43131245, 0.97417297, 0.59547435, 0.44097674, 0.77346576]]])

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.96446324 0.19836034 0.87924349 0.85809597 0.87618198]
  [0.40271629 0.16987447 0.24852037 0.26929028 0.78318367]
  [0.07205774 0.5480108  0.03991835 0.40859816 0.53261905]]

 [[0.64174815 0.4187394  0.04499273 0.2560781  0.9598201 ]
  [0.45465946 0.55219183 0.71096617 0.24364299 0.7188212 ]
  [0.43131245 0.97417297 0.59547435 0.44097674 0.77346576]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

True if b.size == a.size else False

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
#we are not able to add a and b because they have different shapes.
a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

c = b.transpose(1,2,0)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
"""
It works because i've trasnposed the array into a new one with the shape of a. Otherwise, you are not able 
to sum them all.
"""
print(a.shape)
print(c.shape)
d = a+c
print(d)

(2, 3, 5)
(2, 3, 5)
[[[1.96446324 1.19836034 1.87924349 1.85809597 1.87618198]
  [1.40271629 1.16987447 1.24852037 1.26929028 1.78318367]
  [1.07205774 1.5480108  1.03991835 1.40859816 1.53261905]]

 [[1.64174815 1.4187394  1.04499273 1.2560781  1.9598201 ]
  [1.45465946 1.55219183 1.71096617 1.24364299 1.7188212 ]
  [1.43131245 1.97417297 1.59547435 1.44097674 1.77346576]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)
"""
Values are proportional. Because D is the result of sum A and C. D is one unit greater than A
"""


[[[0.96446324 0.19836034 0.87924349 0.85809597 0.87618198]
  [0.40271629 0.16987447 0.24852037 0.26929028 0.78318367]
  [0.07205774 0.5480108  0.03991835 0.40859816 0.53261905]]

 [[0.64174815 0.4187394  0.04499273 0.2560781  0.9598201 ]
  [0.45465946 0.55219183 0.71096617 0.24364299 0.7188212 ]
  [0.43131245 0.97417297 0.59547435 0.44097674 0.77346576]]]
[[[1.96446324 1.19836034 1.87924349 1.85809597 1.87618198]
  [1.40271629 1.16987447 1.24852037 1.26929028 1.78318367]
  [1.07205774 1.5480108  1.03991835 1.40859816 1.53261905]]

 [[1.64174815 1.4187394  1.04499273 1.2560781  1.9598201 ]
  [1.45465946 1.55219183 1.71096617 1.24364299 1.7188212 ]
  [1.43131245 1.97417297 1.59547435 1.44097674 1.77346576]]]


'\nValues are proportional. Because D is the result of sum A and C\n'

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a*c
print(e)

[[[0.96446324 0.19836034 0.87924349 0.85809597 0.87618198]
  [0.40271629 0.16987447 0.24852037 0.26929028 0.78318367]
  [0.07205774 0.5480108  0.03991835 0.40859816 0.53261905]]

 [[0.64174815 0.4187394  0.04499273 0.2560781  0.9598201 ]
  [0.45465946 0.55219183 0.71096617 0.24364299 0.7188212 ]
  [0.43131245 0.97417297 0.59547435 0.44097674 0.77346576]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [29]:
# your code/answer here
#they are equal because they have same value on same positions

print(e==a)
comparing = e == a
True if comparing.all() else False

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(f'Max Value of d is: {d_max}.\nMin Value of d is : {d_min}.\nMean of d is: {d_mean}')

Max Value of d is: 1.974172972342891.
Min Value of d is : 1.0399183501688207.
Mean of d is: 1.5156065543809372


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [22]:
# your code here
f= np.empty([2,3,5])
print(f)

[[[ 75.  25.  75.  75.  75.]
  [ 25.  25.  25.  25.  75.]
  [ 25.  75.   0.  25.  75.]]

 [[ 75.  25.  25.  25.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 25. 100.  75.  25.  75.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
#set the conditions
filter_0 = d == d_min
filter_25 = (d_min < d) & (d< d_mean)
filter_50 = d == d_mean
filter_75 = (d_mean<d)&(d<d_max)
filter_100 = d == d_max

#use de filter and asign to 
f[filter_0]=0
f[filter_25]=25
f[filter_50]=50
f[filter_75]=75
f[filter_100]=100

print(f)

[[[ 75.  25.  75.  75.  75.]
  [ 25.  25.  25.  25.  75.]
  [ 25.  75.   0.  25.  75.]]

 [[ 75.  25.  25.  25.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 25. 100.  75.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print("\n")
print(f)

[[[1.96446324 1.19836034 1.87924349 1.85809597 1.87618198]
  [1.40271629 1.16987447 1.24852037 1.26929028 1.78318367]
  [1.07205774 1.5480108  1.03991835 1.40859816 1.53261905]]

 [[1.64174815 1.4187394  1.04499273 1.2560781  1.9598201 ]
  [1.45465946 1.55219183 1.71096617 1.24364299 1.7188212 ]
  [1.43131245 1.97417297 1.59547435 1.44097674 1.77346576]]]


[[[ 75.  25.  75.  75.  75.]
  [ 25.  25.  25.  25.  75.]
  [ 25.  75.   0.  25.  75.]]

 [[ 75.  25.  25.  25.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 25. 100.  75.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [28]:
#your code

#empty array
g= np.empty((2,3,5),dtype=str)
#set the conditions
filter_0 = d == d_min
filter_25 = (d_min < d) & (d< d_mean)
filter_50 = d == d_mean
filter_75 = (d_mean<d)&(d<d_max)
filter_100 = d == d_max

#use de filter and asign to 
g[filter_0]='A'
g[filter_25]='B'
g[filter_50]='C'
g[filter_75]='D'
g[filter_100]='E'

print(g)


[[['D' 'B' 'D' 'D' 'D']
  ['B' 'B' 'B' 'B' 'D']
  ['B' 'D' 'A' 'B' 'D']]

 [['D' 'B' 'B' 'B' 'D']
  ['B' 'D' 'D' 'B' 'D']
  ['B' 'E' 'D' 'B' 'D']]]
