# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
# Method 1
a=np.random.random((2,3,5)) #random valors between 0 and 1 (but not included the number 1)


array([[[0.77971848, 0.75411992, 0.32947419, 0.086805  , 0.25465447],
        [0.63259058, 0.25652846, 0.95954555, 0.7172074 , 0.76912463],
        [0.81733693, 0.90113353, 0.74863535, 0.85072121, 0.12389838]],

       [[0.96788161, 0.82214091, 0.76867446, 0.74661646, 0.52112226],
        [0.84446552, 0.95462288, 0.63706854, 0.60061229, 0.65725745],
        [0.76221016, 0.61846475, 0.96067946, 0.29369564, 0.09410104]]])

In [8]:
# Method 2
a=np.random.rand(2,3,5)  #other form with rand


array([[[0.6816315 , 0.8308217 , 0.72956403, 0.37661743, 0.16870925],
        [0.05324679, 0.17572448, 0.89879332, 0.24764876, 0.0230721 ],
        [0.67579685, 0.83370077, 0.6352837 , 0.13385194, 0.69711416]],

       [[0.95496966, 0.65224071, 0.36353646, 0.28244529, 0.91745757],
        [0.12657856, 0.2926252 , 0.31731294, 0.75202244, 0.76681149],
        [0.5827598 , 0.72736309, 0.88685114, 0.3896766 , 0.58828873]]])

In [10]:
# Method 3
a=np.random.ranf((2,3,5)) #other form with ranf


array([[[0.81106808, 0.7933847 , 0.42465203, 0.32324588, 0.15992546],
        [0.62758339, 0.22614557, 0.78865926, 0.52500277, 0.34414818],
        [0.21488352, 0.69378138, 0.83088975, 0.57259367, 0.50744743]],

       [[0.95467594, 0.74783141, 0.43584678, 0.67215137, 0.47089456],
        [0.18366556, 0.49461761, 0.41472858, 0.82024125, 0.17201177],
        [0.18096096, 0.88108478, 0.12259203, 0.07140517, 0.91674669]]])

#### 4. Print *a*.


In [11]:
# your code here
a

array([[[0.81106808, 0.7933847 , 0.42465203, 0.32324588, 0.15992546],
        [0.62758339, 0.22614557, 0.78865926, 0.52500277, 0.34414818],
        [0.21488352, 0.69378138, 0.83088975, 0.57259367, 0.50744743]],

       [[0.95467594, 0.74783141, 0.43584678, 0.67215137, 0.47089456],
        [0.18366556, 0.49461761, 0.41472858, 0.82024125, 0.17201177],
        [0.18096096, 0.88108478, 0.12259203, 0.07140517, 0.91674669]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
# your code here
b=np.ones((5,2,3)) # use np.ones (array with all valors = 1)

#### 6. Print *b*.


In [13]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [15]:
# your code here
np.size(a)==np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [18]:
# your answer here
#np.add(a,b) 
# we can not add a + be because these arrays has different rows and columns (different "shape")
np.shape(a)==np.shape(b)

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
# your code here
c=np.transpose(b,(5,3,2))  #we use np.transpose 

AxisError: axis 5 is out of bounds for array of dimension 3

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [22]:
# your code/answer here
d=np.add(a,c)

ValueError: operands could not be broadcast together with shapes (2,3,5) (3,2,5) 

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [21]:
# your code/answer here
a
d

NameError: name 'd' is not defined

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
# your code here

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here