# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [90]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [4]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [121]:
# Method 1
a = np.random.random((2,3,5))

In [119]:
# Method 2
from numpy import random
a = random.randint(10, size=(2,3,5))

In [93]:
# Method 3
a = np.random.sample(size =(2, 3, 5))

#### 4. Print *a*.


In [122]:
# your code here
print(a)

[[[0.24962081 0.34141279 0.98501023 0.34154448 0.92589365]
  [0.03710126 0.65247812 0.0556457  0.00693992 0.6244539 ]
  [0.00292377 0.34736299 0.45152964 0.5668194  0.79430475]]

 [[0.55897627 0.30578527 0.50704593 0.03822821 0.8786177 ]
  [0.6946388  0.65451701 0.35080738 0.76157517 0.26993644]
  [0.22542617 0.37096626 0.04832145 0.23042063 0.20650289]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [123]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [124]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [97]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [85]:
# your answer here

"""We won't be able to sum two arrays that are shaped in a different way, if we could, the python command would be the following: 
np.add(a,b)"""

"We won't be able to sum two arrays that are shaped in a different way, if we could, the python command would be: \nnp.add(a,b)"

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [125]:
# your code here
c = b.transpose((1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [99]:
# your code/answer here
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [134]:
# your code/answer here
print(a)
print(d)

"""D's values are A's + 1"""

[[[0.24962081 0.34141279 0.98501023 0.34154448 0.92589365]
  [0.03710126 0.65247812 0.0556457  0.00693992 0.6244539 ]
  [0.00292377 0.34736299 0.45152964 0.5668194  0.79430475]]

 [[0.55897627 0.30578527 0.50704593 0.03822821 0.8786177 ]
  [0.6946388  0.65451701 0.35080738 0.76157517 0.26993644]
  [0.22542617 0.37096626 0.04832145 0.23042063 0.20650289]]]
[[[1.46513455 1.0825428  1.89641631 1.01778714 1.61458556]
  [1.10653626 1.0581088  1.42831668 1.08745889 1.93675689]
  [1.61616022 1.57606541 1.91405757 1.90480595 1.95329725]]

 [[1.18698163 1.93843721 1.17756404 1.23993344 1.58744507]
  [1.76337405 1.62386595 1.22330561 1.85386151 1.54236301]
  [1.75140962 1.45397397 1.66102174 1.81939087 1.58953095]]]


"D's values are A's + 1"

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [131]:
# your code here
e = a * c
print(e)

[[[0.24962081 0.34141279 0.98501023 0.34154448 0.92589365]
  [0.03710126 0.65247812 0.0556457  0.00693992 0.6244539 ]
  [0.00292377 0.34736299 0.45152964 0.5668194  0.79430475]]

 [[0.55897627 0.30578527 0.50704593 0.03822821 0.8786177 ]
  [0.6946388  0.65451701 0.35080738 0.76157517 0.26993644]
  [0.22542617 0.37096626 0.04832145 0.23042063 0.20650289]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# your code/answer here
a == e

"""A equals e because e it's the result of multiplying a * 1, which brings the same result"""

"A equals e because e it's the result of multiplying a * 1, which brings the same result"

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [135]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("The maximum value of d is:", d_max)
print("The minimum value of d is:", d_min)
print("The mean of d is:", d_mean)

The maximum value of d is: 1.9532972514803921
The minimum value of d is: 1.0177871439023103
The mean of d is: 1.5356829649578827


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [136]:
# your code here
f = np.empty([2,3,5])
print(f)

[[[1.46513455 1.0825428  1.89641631 1.01778714 1.61458556]
  [1.10653626 1.0581088  1.42831668 1.08745889 1.93675689]
  [1.61616022 1.57606541 1.91405757 1.90480595 1.95329725]]

 [[1.18698163 1.93843721 1.17756404 1.23993344 1.58744507]
  [1.76337405 1.62386595 1.22330561 1.85386151 1.54236301]
  [1.75140962 1.45397397 1.66102174 1.81939087 1.58953095]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [145]:
# your code here
for x in f:
    x[(x > d_min) & (x < d_mean)] = "25"
    x[(x > d_mean) & (x < d_max)] = "75"
    x[x == d_mean] = "50"
    x[x == d_min] = "0"
    x[x == d_max] = "100"

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [168]:
# your code here
print(d)
print(f)

[[[1.46513455 1.0825428  1.89641631 1.01778714 1.61458556]
  [1.10653626 1.0581088  1.42831668 1.08745889 1.93675689]
  [1.61616022 1.57606541 1.91405757 1.90480595 1.95329725]]

 [[1.18698163 1.93843721 1.17756404 1.23993344 1.58744507]
  [1.76337405 1.62386595 1.22330561 1.85386151 1.54236301]
  [1.75140962 1.45397397 1.66102174 1.81939087 1.58953095]]]
[[[ 25.  25.  75.   0.  75.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  75.  75.  75. 100.]]

 [[ 25.  75.  25.  25.  75.]
  [ 75.  75.  25.  75.  75.]
  [ 75.  25.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [174]:
# your code here